# Photos and Eulogy {#photos-eulogy}

## Photos

Carmen: Pasadena Audubon Society is over in Bayer now, I actually have
the news clipping still from then (Bland was 12).
I gave my oldest daughter a lot of the old pictures and,
which reminds me, if you wanted the pictures of childhood.

We’ll have to get you to cross paths with Michelle in San Jose
cuz she’s got the trunk of the, and Bland, oh god he was so cute
when he was little. Well he’s still cute, but I mean he actually won
awards for some of the pictures that were taken of him when he was
4 and 5 years old. They put him in some kind of contest and he won
awards because he was so adorable, just picture perfect, so we’ve
got some of those pictures in that trunk over there in San Jose.
Let’s see, what else can I think about Bland? Oh, teenager-hood for
me, and he was there and the way that worked out was we were living
with my aunt and uncle when I was in 6th grade, this is my mother’s
younger sister Lila and Edward and my two cousins, and to make ends
meet while I was in 6th grade.

## Present Time

Wed 20 jul 2022

Jim Barbieri retired in 2009, and we have stayed in touch, off and on.
My own plans for retirement aim for Summer 2023.
This work with Bland Ewing is one project at the top of my retirement
bucket list, and I am getting a head start.
Next month, I will visit Jim in California,
and we will examine the wealth of material about Bland's life and work.

Wed 31 may 2006

Bland Ewing died on Wednesday 22 March 2006 after a bout of pneumonia.
Toward the end, he agreed to move to a nursing home in Paradise, CA.
Soon after, he was largely bedridden.
In the last few weeks, Bland had several treatments for a bacterial
infection and for internal and external yeast infections.
He had some physical therapy but did not really improve.
He was in some pain, and was put on morphine even though he never liked
painkillers as they messed up his mind.
He went peacefully. Jim Barbieri and I had a good talk with him on the
Monday before (he could not speak words, but he definitely connected).
We chatted with him by phone a few times in those last weeks.
Bland made us laugh, and told us in his garbled speech that he loved us.

The funeral service was 31 May 2006 in Stinson Beach, Bland's favorite
place, in the home of a friend.
After the service, a group went down to Limantour Spit in Bolinas to
spread his ashes.
Here is the eulogy composed by Brian and Jim:

Bland Ewing 1931-2006

Judith Bland and Frederick Jr. Ewing produced Bland Ewing on
13 February 1931 in Pasadena, CA.
Seventy five years, one month and nine days later,
at midnight on 22 March 2006, Bland passed on.
Bland had active symptoms of Huntington’s disease for nearly two decades.
About five years ago, he developed prostate cancer.
Pneumonia took him peacefully in the night at the end.
He is survived by his younger sister along with her children and grandchildren.
His legacy is in the hearts and minds of his friends.

Bland had a colorful life, touching on many great moments of the 20th century.
Albert Einstein played violin in his grandfather’s home
while Bland hid under the dining room table.
His mother studied cello under Pablo Casals,
and became a famous visual artist, with a bust displayed in the National Gallery.
His father was Linus Pauling’s x-ray crystallographer in the ‘40s and ‘50s,
racing against Rosalind Franklin to discover the form of DNA.
Pauling’s twin sons often babysat the Ewing kids.
Bland grew up chatting science with Caltech greats,
especially Pauling and Richard Feynman,
the Noble laureate who unraveled the Challenger disaster.

Bland worked at JPL in the late ‘50s on some of the earliest, building-sized computers.
He mapped orbital paths for our first successful satellite, Explorer,
which went up after the Sputnik scare of 1957.
[He etched his initials BE on the Explorer batteries.]
He took courses at Caltech, then later at UC-Riverside,
where he is known for the “Ewing effect”,
freezing water in an open thermos overnight in the desert.
He was in the first graduating class of ten at UC-Irvine in 1966,
majoring in math and biology.
Later he moved to UC-Berkeley to teach the “Man in the Environment” course
at the invitation of David Wood.
He stayed as academic staff at Berkeley under Wood for a decade.
During that time he worked with Jim Barbieri and Brian Yandell
on innovative ideas to model how bark beetles live with pine trees.
He moved to Stinson Beach in 1979, where he lived for a couple of years.
His favorite activity was running up and down the beach in the early morning.

In the late ‘70s, Bland formed his first company, Micrographics,
out of his living room. He planned his second company, Synertek,
while living in Stinson Beach. In 1980 he set up shop in Silicon Valley,
and in 1982, he founded GraphOn.
He developed the first microprocessor-driven graphical workstation,
which was demoed to acclaim at SigGraph 1984.
During these heady early years of the computer age, Bland was a full supplier to Apple,
helping them with ideas for the first Macintosh.
GraphOn made Bland a millionaire on paper, but the company was not sold
in time for him to benefit.

In the late ‘80s, Bland moved to Chico, then ultimately Paradise,
to live near his sister, Carmen.
He was showing the early signs of Huntington’s disease—chorea,
or uncontrolled motion, and depression—the disease that felled his father and his grandfather.
In 1995, his friends learned of his plight.
Jim Barbieri visited Bland, and in 1996, Brian Yandell and Dave Baasch visited him.
For the next ten years, Jim and Brian regularly called or visited Bland.
They published a refereed scientific paper in Ecological Modelling in 2002,
with Bland as first author, based on his seminal work from the ‘70s.

Bland was a quiet person, but he loved a good laugh.
While he lived in the Pasadena area, he was full of mischief.
He once dumped lithium down the sewer to see what would happen—
it blew the manhole covers for many blocks, sending up blue flames,
and backing up many toilets in the area.
Another time, he dribbled mercaptan (skunk essence) down the halls
of a dorm at Whittier College, leading to immediate evacuation.

Bland affected many people deeply throughout his life.
He helped many of us see our own lives more clearly,
and realize the options before us in new ways.
He gave us confidence about our own abilities and creativity,
urging us gently to go where we might not have gone otherwise.
We will all miss him.

## The Bland I knew

There is a custom among the Navajo people,
that at dawn each member of the Dine’ faces East
– the rising sun - and says a prayer.
The prayer goes like this:

> With beauty before me I walk,
> With beauty to the right of me I walk,
> With beauty to the left of me a walk,
> With beauty behind me I walk,
> With beauty above and below me I walk,
> In beauty I walk, 
> In beauty it is finished.

Actually, the word beauty in the Navajo language is
_hozro_ which suggests not only beauty,
but a oneness and a sense of completeness
– a sense of peace with one’s surroundings. 

Bland walked this earth in beauty.

Brian, Bland, Bob Luck, Dave Baasch,
and I worked on QPE in Berkeley and his honesty, integrity,
and intelligence was manifest.
However, it was his sense of beauty that made his life magical to each of us.

I have seen Bland spend hours in our Walnut Creek home
quietly watching a raven that was recovering from an injury.
Bland was at peace with his surroundings and saw only beauty.

Twenty-five years later I visited Bland in Paradise,
and it was obvious that Huntington’s had started to take its terrible course,
yet Bland was at home with his destiny and still saw only beauty.

In Bland’s final months he had almost lost the ability to speak, yet with great effort he would still say “love you, guys”

It was Bland who taught us a new way to see the world around us.

It was Bland who taught us to see beauty.

It was Bland who taught us about patience, perseverance, and peace.

It was Bland who showed us love.

Bland is my friend. I will not miss Bland, for he is forever in my heart….

jimb

Sun 24 sep 2000

I have been visiting Bland for over four years now.
Just about three years ago,
I decided, with strong urging from my sister Lynn,
to write Bland's biography.
Now a year after giving him the draft,
I have no further work of consequence on his life story.
That is not completely true.
I have recorded some stories of import,
particularly about his father.

So let me write about recent times.
I visited Bland and Carmen toward the end of May.
Things were really bad then.
Bland had fallen several times,
with one very serious fall that took him to the emergency room,
followed by meds that left him unable to read
and very unsteady on his feet.
It looked like it was time to put him in a nursing home.
That's what his doctor said,
and that's what Carmen thought as well.
But he fought back.
I called him on a Saturday evening to say I didn't know what I could do.
At that point, GraphOn had not come through with any stock or cash,
and I could not see any way to cover his expenses.

Thu 23 sep 1999

I visited Bland in July and shared with him what I had found
about the Explorer program, including a video called
"X Minus 80 Days" by Henry Richter, his former boss at JPL.
Bland was quite moved seeing this.
It clearly brought back lots of memories,
filling in some gaps.
I returned home to find a tape from Richter,
along with some manuscripts.
I have transcribed these, but have not passed them on the Bland.
Some of Henry's comments contradict Bland,
and I am not sure what to do about that.

After that visit, Bland seemed ready to move on to other chapters in his life,
in particular the population ethology work we shared at Berkeley.
I arranged a conference call with Jim Barbieri at Bland's insistence.
Our first conference had to be delayed a week,
and the word did not get to Bland in time.
Jim and I had relied on email, but Carmen only checks that occasionally.
Anyway, I ended up having a pleasant visit with Bland,
and later with Carmen, that Wednesday.
As a result, I decided to start calling Bland every Wednesday at 4pm his time,
regardless of other events. That is now a priority for me.

The next week, on the 8th of September, Jim, Bland and I talked.
It soon became clear that Bland had really been rereading the modeling work.
Jim and I were impressed,
and I promised to send Bland the current versions of papers.
Bland's insights were truly amazing,
providing new understanding for me of things I had been staring at for quite awhile.
I got motivated and revised the two drafts on my desk,
sent them out by FedEx to Bland and emailed Jim.
On the 15th, we talked again, with more depth and clarity.

As I prepared for our third conference call on the 22nd,
I got a little surprise.
But first some background.
In early September, Dave Baasch called me.
He had just learned that GraphOn, the company Bland helped to found, was going public.
I had known they had risen from the ashes of bankruptcy
and seemed from their web page to have some interesting products,
but I had stayed clear of contacting them.
Some lawyer advice, and my own ambivalence,
kept me from calling to say I was a friend of Bland's.
What would they say?
Would they be willing to talk about Bland's involvement in the company for my book,
or would they worry about being sued?
Would they offer to help Bland or say he lost out in the bankruptcy and that was it?

Dave offered to call Walt Keller, whom he knew.
I was greatly relieved that he was willing to do this,
and passed on the news to Carmen but not to Bland.
We both took a wait and see attitude,
and when nothing happened in two weeks,
I think we both figured that was that.
I began wondering if I should call Dave to see if he had found out anything,
but I kept putting it off.

On Wednesday the 22nd at around 2pm,
I was heading out the door to do some errands.
The phone rang, and a person asked if I was Brian.
I said, "Yes", thinking this was a phone solicitation.
She introduced herself as Robin Ford, a friend of Bland.
My next reaction was to think this was one of Bland's long lost friends
that I am supposed to interview.
However, she then said she worked at Graphon
and was married to Walt Keller.
My interest heightened, but so did my guard.
What did she want?
Robin said that they had heard Carmen had breast cancer
and assumed she had died.
They had heard a confused report from a coworker about Bland at one time,
but thought he had left thinking the company had shut him out,
probably on the basis of bad advice from a lawyer.
I reassured her that nothing of the sort had happened,
filling her in briefly in the intervening years.
She said she wanted to help, which I thought was nice.
Again I was a bit guarded--hopeful but not overly optimistic.

I went on to my errands, now emotionally on a roller coaster.
What should I do about our phone conference at 4pm (6pm my time)?
It was hard to concentrate, but at least all I had to do was photocopy.
Around 5 my time, I called Carmen.
She had just gotten in and had not received any message.
I shared what I knew, and we agreed not to involve Bland just yet.
She said, "We'll see." Like me, she was unwilling to get her hopes up
based on a vague promise.
She did remember Robin and was certainly intrigued.
I gave her Robin's phone number, but apparently she did not call.

I called Bland and Jim at 6/4, and we had a very lively, rich research conference.
I was, however, distracted.
At times I thought Bland was way off base,
and commented to Jim about this.
He contradicted me, making it clear that some of this was material I had not known about.
And it turns out that Jim still has some of the material,
the computer code, for the research work.
I began getting even more hopeful that something would come of the research
besides a few papers.

After the call, I immediately called Robin to let her know Carmen was home.
That is when I learned Carmen had not called, which was not surprising.
Apparently Robin called right away and talked with Carmen for an hour.
Later Carmen called me and relayed the gist.
GraphOn had crashed after the bankruptcy,
along with many companies in the technology recession of 1991-92.
However, they managed to hang on due to a patent that Bland had filed on RasterOps.
Sun Microsystems took an interest in this, as did some others,
and it basically supported a skeleton crew for several years.
Lately these ideas have been taking off,
leading to the pending IPO.

Robin said she and Walt had talked with their lawyers and wanted to,
and legally could, give both Carmen and Bland money and stock in the company.
Robin wrote a check for $10,000 to Carmen that night,
and promised funds on a continuing basis for the rest of their lives.
While the details are being worked out,
the thrill is here in force.
Carmen was ecstatic.
Now they may be able to afford a modest home
where she and Bland and a caretaker can live.
And they can now pay a decent wage to a caretaker
so they won't have to keep finding new people.
Carmen shared the news with Bland right away,
setting him to cry profusely.

And Robin and Walt want to go visit Bland in the next week.
This all happened very fast.
Dave Baasch called me later that night to check in.
He had only just located Robin that afternoon.
She must have called me immediately after she got off the phone with him.
And then she and Walt must have consulted with their lawyers that afternoon.
This seems like such a happy ending,
or at least transition, to a tragic tale.

Of course, Bland is still dying.
His energy level is low.
It takes him until 2 or 4pm to finish his "morning" routine
of coffee, breakfast, toothbrushing and general cleanup.
That is why my conference calls are in the late afternoon.
If he has a bath, then there probably would not be any time to talk.
I am not sure how late he stays up,
but I imagine his day shortening at either end,
eventually meeting in the middle.
I dread that day when he runs out of time to function.
Will that be the end, or just another transition?
Still, he enjoys reading and thinking,
and he enjoys talking.
We have that to share now,
along with tears and laughter.
I wish I could call him now to share the good news,
but it seems better to let him absorb it for a couple of days.
I know Carmen and Bland will keep me in the loop,
and my heart is with them.

Sat 13 mar 1999

*I wanted to ask you about a couple things
and I wanted to show you the book.  

Great.

*Why don’t I show you this.
This is the first half, and here’s the second half.

Whoa.  Why don’t you grab me my glasses
so I can at least glance at the book.

*Which ones?

Brown case, smooth.  That one, great.

*This is the first one here and there’s an outline.

Whoa.

*There’s other stuff like that in here too.
Other little gems, little things of your life.
I’m going to leave this here and there’s
also some stuff about Carmen’s life in there as well.

Great.  That needs to be done too.

*You can read that at your leisure.
There’s still a lot of work to do.
I still have a lot of work to do
but I’ve got all of it organized now.
There’s some places where there are gaps in the dialogue.
I need to go back to the tapes and listen to that
but I have all that material.

That’s wonderful.  Thank you.
Thank you again and again and again.
Anyway, this what I just gave you is some new stuff for Silicon Valley.

I got lots of email back and from Jim,
and also really nice cards from Maxine.
Lovely.

*Great, great.

It was interesting to hear both about the meeting with you.
They sent me pictures and cards and emails about all this.
It was kind of interesting reflecting back on some of that stuff again.

*Yeah, Jim and I are working on a couple papers.
In fact I’ve got drafts here.
Three or four papers.

I can believe it.
There’s a lot of work there.

*That’s right.

It struck me that some pieces of the work
just got left in mid-stride.
That some aspects such as the hexagonal system
for keeping track of area and direction
and things like that.

*Yeah, well that will be one paper.

That’s very reasonable because it involves a lot of ideas
that could even in this day and age
make a big difference in how fast the computers
could execute the model. 
