# The Papers {#papers}

## Papers

### Finding the Papers

*Now I took these papers, this work here, your work,
and I put them together into a binder.
I had them on my shelf while I was a graduate student at Berkeley.
I didn’t want to look at them.
I knew if I looked at them, I wasn’t going to finish.
I had them on my shelf in Madison
while I was working towards tenure.
About a dozen years ago, I decided I couldn’t keep them there any more
so I mailed them to Jim.
I didn’t have this last section—that I got from Jim this summer—
but I mailed the rest of it to Jim.
I said “Jim, keep this for me.”  

*I got back in touch with him and asked him to find you in the early 90s.
Later when I saw you, the summer of 96,
I started getting interested,
realizing I was ready to look at this.
I thought I was ready to look at this stuff.
I started asking Jim for it.
He couldn’t find it,
and then he found it
and he tried to send it to me,
but it came back.
It got lost on his desk.
Various things happened to it.

*In August this year, I went to visit him in Kernville.
We were getting ready to go to Big Pine
and I said, “Jim, by the way,
what happened to that book of Bland’s stuff?”
He said “Oh, I’ve got it in the back here.”
I went back and I got it.
I had it in my hand again,
after more than 10 years, about a dozen years.
I said, “You told me there was some other stuff.”
We both got down on our hands and knees
and we started pulling out papers
and that’s where we found the last section.

That’s really the last stuff that was done where
I was interacting with the problems and stuff
that needed to be done and I was still doing the pieces at Berkeley.

*Yeah.  But I don’t think I was ready to look at this until now.
I don’t think I’ve been ready.
Too many other things, but I’m ready.

You have to also realize
it can make you a hell of a lot of trouble.

*Well, I don’t think so.

I meant at the time of the work.
Maybe you’re right, the time is right.
Maybe the time is right, I don’t know.

*We’ll see, we’ll see.
I think there are people who are ready to listen to these ideas.
The interesting thing is I know some of these people.
We’ll see what happens.
I’m pretty excited to be visiting it again.
I’m real excited to get your thoughts on it and get them down.

Well I thank you again for the opportunity.
I want to thank you again for the opportunity
to say something about some of the things in my life
that were really important to me.
I would have felt really bad
if I had either died
or I had degenerated past the point
where I couldn’t do what I’m doing now.

*I heard this Fall that you weren’t doing so well.
I was talking to my sister and she said,
“You’ve got to do it.
You’ve got to go visit him.”
I looked at her and I thought,
“She has MS, multiple sclerosis.
She has friends who have declined
to the point where they are in the hospital
and there’s no going back.
That’s going to happen to her some day.
I can’t wait any longer.”

### Book Plan

*Yeah, you’ve got a lot of different time scales going on there.
Let me just talk a bit about what I plan to do with this.
I’m going to take this back home
and I’ll try to get the parts having to do with the reports
so that the latter part transcribed first.
Ultimately I will get it all transcribed
and rearrange things a little bit.
Like the high school stuff we talked about today,
that goes with some of the stuff earlier,
so put that all together and try to.

Blocks together.

*Take the blocks and put them together and give them section headings.
I will get you a transcript so that you can look it over.
We can talk about it and if you’ve got changes or additions.
I can hook this machine up to my telephone
so we can do stuff over the telephone
so you know you don’t have to write the stuff down.
I mean we can just, I can get your feedback that way
and we’ll just go along.
I don’t know how much I’ll get done in the next 3 weeks.
I think I’ll probably just get started.

*I haven’t really had the time yet to look carefully at the systems modeling.
I’m planning to go see Jim Barbieri in January
and spend a week out with him.
We’re talking about that.
That will be a chance to really get immersed
in the modeling part, some of the writing.
I’ve been organizing the tapes,
organizing the transcripts of the tapes
and trying to divide it into chapters
and put it in chronological order and subject order.
That’s moving along.
I feel like I have a vision about what I want to do with this.

*I want to sort of weave the present,
our conversations about now and about the technology and so on,
and my trips coming up here,
in with your personal and scientific history
and marching through your decades.
Remember once we talked about
how your life has sort of been in decades.
The 30s and the 40s and the 50s,
and different things have happened pretty much by decade.
For this book project,
I will take the modeling
and come up with some synopsis.
I’m going to try to synthesize the material
from all of those papers.

### Writing The Papers

+They will be interesting stories.
I was really surprised when I looked at this.
This first report called population ecology, you remember that?
When we wrote that thing, Peter Rausch did not like it
because he felt it was too dense.

*It starts out with this general thing
and then it goes immediately into splines.

+He thought it was too dense.
What we did is after the 16,000th iteration.
Bland is going, “Oh god, I don’t want to do this any more.”
We ended up writing the second report,
which basically took out the idea of population ecology.
Most of the really core stuff was in the back.
It was kind of funny looking over this
while Bland was getting ready this morning.
I liked the first report better, much better.
I mean if you’re going to hit them between the eyes,
you might as well hit them right in the beginning.

Everyone counts.
I never believed the right thing worked in writing.
I never liked to.
Everyone has to count.

+I didn’t know it when we wrote that report,
but a lot of the things that were in there
are really talking about projecting out a solution.

You’re taking essentially a Hilbert space
and projecting out a solution.

I’ve always had my biased ___, I just lost it.

*The Hilbert space?

No.  What’s the physics based on?

+Quantum mechanics.

Quantum mechanics is what I ___, that’s crazy.
I couldn’t ___ quantum mechanics.
Quantum mechanics is what I ___.
I’ve always had that sort of a bias anyway.

+Bland and I used to go over,
I think this was before you arrived on the scene
because I think at that time
it was just Bland and I and Peter Roberts.

*I was probably down at Caltech at school.

+Yeah, cuz I think you came in the middle of—

*A year and I’d been there the previous summer.

+Bland and I wrote that, we made the first pass at it.
We used to go over to Sprawl Hall.

During the student riots and all that.

+Yeah they had all of the donut shops located
right at Telegraph Avenue there.
We discussed that particular thing
about the fact that that’s exactly what quantum mechanics does.
They project out a solution
out of an infinite number of variables literally.
I can remember Peter Rausch saying
we don’t want to do that.
We don’t want to build the world with quantum mechanics.

He was so wrong.

+Yeah, I know.  

+I think Bland and Dave Baasch wrote their first set of algorithms
for doing dynamic storage allocation and linked rings and stuff like that.

-Dynamic storage calculations?

+Allocations.

*I wrote the doubly-linked prestructure.

+You did it?  OK.  You also did the stuff on random?

*Yeah, ___ random number generators.  That was my stuff.

+Bland found out that the random number generator on the VAX computer was ___.  

___ It was our random number generator?

*Yes, the one you used for fallout.

Seven, the magic number 17, remember you used ___
the methodology of the problem, it was 17,
it would blow every ___.

+Who wrote the routine that graphed the random number generators?
Was that ___.

*Probably, yeah, Bland wrote it.

+And it had a really banded structure.

Yeah.

+And I think we said oops.

*You wrote the basic plot routine and then I adapted it somewhat
and got it to work and did the calculations.

+25 years ago.  I’ll be really honest with you,
I really think the first paper is better written than the second paper.
The reason that we wrote the second paper, as I mentioned before,
is because of the density.
We literally put everything in the first,
we put everything in the first 3 pages of that thing.

*Yeah, those are beautiful.

+We basically defined the theory.
Peter Rausch, bless his heart, said that it was much too dense.
We must have had—Bland how was it?—something on the order of 50 iterations
before we got the second paper out.
It was so bad that there was a period of time
when I think Bland was going to kill either me or Peter at any given time.

*I do remember a certain amount of tension that summer.

+We got into some horrible, because I didn’t want to throw anything out.
Bland read it, and my recollection is that after Bland read it,
he made a number of corrections that were obvious corrections.
Things like this particular part say on the splines is really incoherent.
We’ve got to rewrite that and we’ve got to do a better job
over here in the event space. 

+But he never tore up the front part of the paper.
That front part of the paper, once we got rid of the typos.
Obviously we never got rid of all of the typos.
It was just incredible.
After a large number of iterations with Peter,
we came up with the second paper,
which is also very good,
but I don’t think it has the power of the first paper.

+We put many more of the ideas in the first paper
than we put in the second.
I think we coined an important thing.
In the second paper we lost the term population ethology.
We lost that.
I think that what we really were talking about
is not population biology, not population anything.
We’re talking about studying, the science of studying small populations.

-Right here it says a long linear system of models
in which the relationships ___ each of the models is defined.  That’s what you studied.

*It’s a network.  It’s a dynamic ___.

+I really think we lost that term.
I would have liked to have stayed with that.
If you’re going to do something stupid like
invent a whole new field of biology,
you might as well hit them between the eyes the first time.
If you’re going to get rejected, you get rejected right away.
There is nothing in those documents
that is not grounded on really good science.

-It’s amazing, ___ part of it ___ as a lay person.

*Yeah, just skip over the math sections.

+Even the math sections.

-I can understand a little bit of those too but.

+Even the math sections were incredibly well done.

-There should be something done to it.
It’s a really good tool.

*Oh yeah, we’re going to publish it.  Make a book out of it.

-Cuz somebody else can use this.

*Yeah.  There’s nothing like it.

-Really?

+No.

-I was just  ___.
You mean there’s nothing like this right now?

*There’s some people doing individual modeling.
But I don’t think they’ve got.
It’s piecemeal.
It’s patched together.

-It’s fascinating.

### Model Building Blocks

+We found that once we started this particular paper,
that there were things from a mathematical standpoint
that we really needed to redefine.
Bland did the cubic spline.
We took a look at rational functions at that particular point,
where rational functions naturally lead into something
called complex variables.
They’ve got poles and singularities so they have attractor islands to them.
You’re getting into attractor theory but you don’t know how you did it.
You’re into dynamical systems.

+Dynamical systems don’t work.
Every time you try to do them,
you make the initial conditions a little bit fuzzy,
they go chaos on you,
unless you’re really, really lucky.
As we went through each one of the mathematical techniques
that were applicable,
we found other mathematical techniques
that were available, or applicable,
like the fuzzy logic.
We don’t know plus or minus, is it one or a zero?
We kind of put it into kind of a membership
but what does that mean?
It means that our measurement technique was fuzzy to start with.

+We didn’t know the complete definition of the problem.
What it literally comes out with is that
not only is this stuff, that’s printed in this article or in this series of articles.
Not only are those important in themselves,
but basically the whole field of population ethology
now becomes something that has great growth potential.
There’s only probably 10 to the nth different directions
that you can go in.
You can take a look at how fuzzy logic affects this,
how catastrophe theory affects this,
chaos theory affects this.

+I remember the first time Bland gave me a lecture
on Mandelbrot sets and what you do with fractional spaces.
If you take a look at the solutions that come out of that,
you begin to see the same sort of thing that we would expect to see.

The field at that point was so rich,
which is one of the things that killed us I think in some ways.

The field was so rich that every time we looked at something new,
we were kind of like—

*You were doing ___ ground zero.

+We were doing like billiard things.
Oh man, this shit over here is really,
pardon the expression, really good.
We’d wander off and work someplace else.
What we really needed to do,
and I think Bland agrees,
was to solve one problem and then apply the techniques as we grew.

*You don’t have the elegant solution for all the aspects.

+Bland is nothing if he isn’t elegant, so.

*But now a lot of those pieces are in place.
Some of them we have down there,
some of them have been developed in the literature over the last.

+A lot of the pieces are there.
Some of the pieces are still missing,
but the theoretical and philosophical ideas
I have never seen anywhere else.
That doesn’t mean that they’re not there.
It means that when Bland went to Graphon
and I went to Big Pine
and you went off and finished up your Ph.D.
and Bob Luck went south.

*And Dave Baasch went to Oregon.

### Missing Pieces

+There’s two other things that you don’t have.
I’ve got to get them to you.
Bland didn’t write them.
It turned out that they were progress reports
on the work that Bland and I was doing
that I wrote for the Livermore people.

*They’re in the back, aren’t they?

+No, these are two different ones.

*OK, well that’s the stuff you gave me.

+There were progress reports in there.
There’s also a thing that Rick Pollock and I wrote
on numerical models for population biology.

*I saw the reference to that, yeah.

+Bland had a big hand in that,
but it was an internal report.
We couldn’t include Bland in it.
It was on part of the old EPA study
that San Bernardino National Forest one.

___ pollution problems with the trees
and all the other things going on.

+It’s really nice to see this coming out.
I’ll be really honest with you, I forgot.

*I did a lot of work.  It was a lot of work.

And then there are just a few missing pieces
that I would like to see.

+We ought to include those.

I’m almost sure that what I added  ___ normal variables,
I also got a distribution by some weird coincidence
that also is cubic spline, ___ just three.
You could transform it around the transformer
and then could ___ back for being either a normal distribution.
Biologists always ___.

+Did we write that stuff down?
I remember what you were talking about but I don’t.

I couldn’t find any copy and ___ the copy
that I got ___ all vanished, it’s all vanished.

The thing is cuz I gave a real quick ___ variables, and discrete.
You just spread it out and relocated it
and then it just hands it back
so the only ___ basically are the overhead on your computer
when you ran it ___.  Still only the overhead of the thing
so adding 3 to get but ___ still be ___.

+I remember that one.

Weirdly enough for the first case ___ distribution
to also cubic spline.

+My recollection, Bland, is that we didn’t write that down.
I remember discussing that with you
and I don’t think we had ever written anything down on that.
I think I have all of those notes.
Did you throw anything away when?

A big chunk of stuff disappeared, a big chunk.
Huge chunk, in fact all of the last work that I did
hasn’t shown up anywhere.

+Would the other guy, what’s his name,
the guy that’s still in Berkeley?

*Dave Wood.

+No, the young kid.  Ken Lindahl.

*Well there’s some stuff that is described in his thesis.
I talked to Dave Wood and he knows where stuff is
and I’m going to see him in January
so I’ll track down what I can.

+You’re going to see Dave in January?
Would you tell Dave that I,
ask him if it would be OK for me to come up and visit him?

*Oh I’m sure it would.  Come on up.

-I don’t know if he would want to see you.
You’re so old.
He wouldn’t even recognize you.

*You have to dye your hair.

+Probably look like him now.

*Yeah, he’s gotten kind of white.

+We’d better get on the road.

But anyway, I wanted to throw that one piece out because it might.

+My recollection Bland is that I never had any notes on that.
I remember you and I discussing that at length
in one of our many trips over to the doughnut place.
I do remember that.

It was such a quick and easy way of creating what needed to be done
in both the continuous and discrete ___.

+Yeah, my recollection was that we had already written
a cubic spline formulation in here.
This was what we thought was a completed piece.
We were going to add that later.

*I can’t think of anything right off hand.
I think I need to get to the next phase of pulling
all this material together,
which I think will happen by the summer time.
That’s my schedule.
Then I’ll have a different level of understanding
about what’s there and what isn’t,
but my sense is we’ve done a pretty good job
of covering the different decades of your life
and in some detail the modeling efforts.
I don’t really have a good sense about what you did
after I left the program.

You talked a little bit about this basing.

There was a bunch of work I did that was,
for example, the addition of three normals,
I mean three uniform distributions
to get a h__ shaped thing
that was actually supposably.

*Piece wise quadratic.
We talked about that while I was still with you.

I’m curious.  Did you end up digging very much?
Did Don Dahlsten ever factor in what he is down, what was left?

*I did see him last summer in July.
He showed me some stuff that he had but it was mostly the data,
mostly the data from Blodgett.
Unless there’s a box that he’s not aware of,
he didn’t have the notes and stuff.
It may be that Dave still has some of that stuff
in one of his file cabinets.
I talked to Dave about a month ago
and asked him to look in his stuff again.

I can visualize it.
I was writing that stuff on the back of computer printout sheets.
That’s what I see in my memory.
If Yoder spots any computer sheets __ then hang onto them.
If they happen to be, obviously they’re computer __ and probably not all of them.
If you dig some __ like that out of __ and file those things that he __ of the original data he broke into, then by all means hang onto them.

*Yeah, will do.
Yeah, I won’t see him on this trip
but I plan another trip in the spring.

Great.  

*Then I’ll have a more focused idea about exactly what I need.

### Jim and Bob

It sounds like Jim’s planning to come back up here in February.
Is that what he said?  It sounded like.

Yeah, he sounded like he was going to.

*That’s a good date to shoot for.
I’m thinking of coming back here in the beginning of January,
like January, Sunday the 3rd, Monday the 4th,
or is it Monday the 5th I guess.
Sunday the 4th, Monday the 5th.
I’ll be out in California again for a week.
I can come back at that time and just come up and visit.
It will be just a short visit then.
Not another marathon.
So we’ll just do this a piece at a time.

+There’s only two attempts that I know of where we actually tried to apply this.
One was with Bob Luck’s scale problem,
and that fell on dead ears rather rapidly,
mainly because we didn’t have the computer techniques available to us.
Now, I’ll be really honest with you,
I think I could probably sit down
and in a reasonable period of time
write a solution to this.

### Misc

So you ___ me.
At any rate, there was a wildly practical data that he was plotting
into Excel to be able to calculate mean and variables
and ___ again to ___ normal distribution.

*Take two numbers and average them.

So it seems the more the world changes the more it stays the same.
This was just a few years ago.

*Yeah, well I see it all the time.

What?

*I see it all the time.

That’s some of that other ___ fractal type ___.
Anyway ___.
Sometimes I think ___ and people lose on the ___
putting together here.
Some people say ___ in their dynamics and plants and animals
but anyway.


