# Early Life {#early-life}

## Bland's Personal Journey

## Early Life

### Grandparents / Ancestry

My father’s death, my mother’s death, all of my relatives from that period are dead. Noone left whatsoever.

Our paternal grandparents James Frederick Ewing, born in Ewing, VA, moved to Iowa and married Nellie Bailey. Nellie was a farm girl and became a midwife after finishing 3rd grade. They moved to CO and eventually to Pasadena, CA, where James worked for the Parks Department. At some point, he was beaten by vandals, resulting in injuries that were confounded by Huntington's Disease that manifested later and led to his death.

When Bland was 11 or 12, he took Carmen to see their paternal grandparents. That’s the only memory of them. Grandfather raised up on one arm and he looked and said, “Oh this is Carmensita.” That’s the only remembrance I have of our paternal grandfather and grandmother.

Their son, our father, Frederick Jr. Ewing, was born in 1905 in Denver, CO, with siblings Hoyde and Gertrude. Fred graduated valedictorian from HS at age 14, attending Caltech at 15. He won a 3-year Blacker Scholarship. At 18 he won a Jr. Travel Prize, traveling to Europe to climb the Matterhorn, walk in the Black Forest, and climb the Eiffel Tower. He studied in Munich, Germany, with Dr. Carl Anderson, who later won the Nobel Prize. 

Our maternal grandparents were Flavilla "Villa" Annis Corson and Reginald Walter Bland. Flavilla graduated with a degree in architecture at Troop Memorial (later Caltech), and was the first woman to win the CA Bousart award. Reginald studied science at Armour Institute of Technology, Chicago, IL, for 3 years. He quit school to study violin with Valuane (sp?) in Chicago, and started the first Symphony Orchestra in Pasadena. They produced Judith Bland, our mother, along with Flora Ann, Carmen and Reginald.

### Childhood

In 1926, Frederick Jr. Ewing married Judith Bland and produced Bland Ewing. They were 25 at the time. Bland was Born in Pasadena at Huntington Memorial Hospital on 13 February, 1931. When Carmen was born seven years later, Bland was very attentive. They gave him a Betsy-Wetsy type doll and he changed the baby and did everything that my mother was doing for me.

And so life goes. And goes, and goes, and goes, numbers on my toes. Did you ever read any of the books? Nobody Knows How Cold My Toes are Growing. Pooh Corner and things like that.

The kind of person I eventually became is strongly influenced by my grandparents and what they were doing there at 609 North Hill. Their home bordered on the north side of Caltech. 609 North Hill was where I had my childhood. They had what was a summer house out back, a latticework wooden structure with vines growing over the top and a cement floor. It had benches that were built into it around the edges. Bland and Carmen played with dolls there.

They had a very open house for Caltech and, as I understood it, the first Troop Institute actually was co-educational originally before it became Caltech. That’s where my grandmother went to school and majored in architecture and music. But then she went on to raise a family. She was a person that was very much the key person in my own life in terms of my own values both on how I did things and what I felt about people and so forth.

In those days we had our milk delivered in glass bottles. Bland gets a quart milk bottle and he puts a tablespoon of flour into the bottle and he lays it on the kitchen sink. He says, “Come here Carmen, I want to show you this really neat trick. Come here, blow on it really hard.” I blew in the milk bottle really hard and flour all over everything. So he could be naughty at times.

### Divorce / Living with Grandparents

When Bland was 9, in 1940, his parents got divorced and the kids were raised by their maternal grandmother. They went around with getting divorced and not getting divorced and it’s very hard on a child. This would have been just before the second world war. Bland and Carmen ended up staying with my mother. She had full custody because of things that happened in the divorce. In those days if you wanted to get divorced, you really had to prove infidelity. It was very messy, very hard on me. My mother was into physical punishment for getting people to do what they should do. My father just wasn’t around that much when I was a youngster.

It was only a couple years after my sister was born, so she basically has no memory of my father except my mother’s tales about him—good, bad or indifferent. She was born basically into a divorced family and one that really had a hard time getting on at that time. That was right smack then in the middle of the war years.

My grandfather was an inventor and a conductor of the Pasadena Civic Orchestra. They always had just an open house before Caltech. I used to go underneath the table because it had such a long tablecloth. I used to hide under there before they would have these long arguments about—this is just when quantum mechanics was hitting physics and chemistry. This is when Pauling was doing his first original work in quantum chemistry and consequently all of the arguments about whether God threw dice were just part of life. They were just part of life.

We lived quite a bit of the time with my maternal grandparents for financial reasons of course. My grandmother just had incredible patience. The kids were bored when the weather was bad because they were incredibly outdoor persons. We wanted to be outside if we could possibly be. When housebound, grandmother would say, “Come on, let’s make some salt and flour clay.” She’d mix it up for me to play in, and we’d bake it in the oven and I could paint it with watercolor paints. Or she said, “Go get your dolls, let’s have a tea party.” She’d make a pot of tea and some cookies and stuff and we’d have a tea party. Just incredible patience.

She always was this incredibly good cook also like my mother. She always managed to stretch a dinner for however many people showed up--artists, musicians, a lot of people from Caltech. Mostly it was people that had supported my grandfather or my mother in the music field. They played in the symphonies. Grandmother was this incredible cook and housekeeper. The house was always immaculate. Every morning she had to vacuum and keep up the living room perfectly for my grandfather to give music lessons.

My grandfather taught there in the house. I was never allowed to bring any friends home because we would make too much noise. I couldn’t bring the neighbor kids because my grandfather was always teaching. When relatives showed up, it was a different situation. My mother’s younger sister, Aunt Lila, brought her two boys Sabin and Thayer. And Hilary would come. They were like siblings. We were so close together and sharing stuff. It was probably on the weekends when he didn’t teach. We could play house or horses. Carmen would fix these fancy bridles up and put a pencil in their mouth for a bit, and tell them to giddy up. Hillary was 5 years younger than Carmen, Sabin was 3 years younger, Thayer 5 or 6 year. Carmen was always the leader in that group. That was fun.

I just remember my grandmother having infinite patience. Grandfather to some extent, but he scolded kids for playing with the telephone.

My grandfather and uncle on my mother’s side and my grandmother pretty much did most of my raising when I was young. I would say the person who was my grandmother, Grandmother Bland on my mother’s side that was my saving person. She was the one who always had time for me, always was truly wonderful, a great person and incredibly supportive of anything I did.

I played chess with my grandfather who always won. They made a big thing out of playing chess. Although I was taught the game, my memory mostly was being forced to do it. So I didn’t become much of a chess enthusiast.

It was a pretty competitive environment all the way around. There was no space anywhere. I had three strengths. They were mathematics which I did all sorts of different ways, and I had no competition from my family at all, except for when I mentioned the wrong approach to my father.

### Albert Einstein

Albert Einstein came a couple of times I understand. I don’t really remember him but I guess he played the violin then. He came a few times and of course afterwards they used to comment on both him and Pauling and the other people there. Feynman a few times, not that often. He was more into drums and things like that. But he certainly dropped by, and there were other people that seemed to work very directly with Richard Feynman. Later, I lived right next door to where Bob Leighton used to live in Altadena. His son, Ralph Leighton, co-authored books with Feynman.

+Do we have any pictures of, are there any pictures of you and Einstein?

-You’re not supposed to make him laugh.

*Oh you told him about it?  OK I’ll tell him.  I’ll tell him.

He’s never read, we need to listen to the tape.

*Yeah, you need to listen to the tape so he doesn’t have any memory of Einstein from growing up but there’s a story that was told of his father playing, or his grandfather playing, you know they had a little concert and then the violin was passed to Einstein and he just started playing like a ___.

+Yeah, I heard that story.  Bland told me that story many many years ago, back in 1970 or so.

*But that’s a story that was, you learn later on, I mean you ___ through your life.

Right.

+There’s another story that Bland told me about that didn’t involve Bland but Bland told me what graduate students were for and that’s when Einstein visited Caltech and if Einstein is crossing a street, graduate students were supposed to throw themselves in front of cars if he got too close.

*He was not too attentive to those kind of details.

+No.  I think that was a separate.

### Father Fred

Judith largely supported Frederick while he was going through college. At 20, Fred received a BS with a major in physics, minor in chemistry, studying crystal structure analysis with Linus Pauling. He taught at Caltech for three years, getting a PhD magna cuma laude under Linus Pauling in 1933. Lived in Santa Rosa sep-jun 1934. Worked in industry for 4 years. Honorary Colonel in WWII. He suffered 2 heart attacks.

Fred would come now and then to visit, but was this total stranger bringing a gift. He would come on holidays or whatever was the proper time for a father to show up, right? They’d say your father is downstairs, and I’d just be petrified to have to go downstairs and see him. 

My father was a chemist with Linus Pauling. He was Pauling’s student and was very much into his professional life. My mother was a professional cellist and sculptor at a time when women just didn’t do that. And consequently they were much more into professional things where my grandparents were much more into people and the arts and supporting the arts.

<more stuff about him and Pauling, and Werner von Braun at end of WW2>

### Mother Judith

The other thing that our mother went out of her way to do—I called her Judith because she didn’t want to be called mother—was to teach me how to be an incredible homemaker because she didn’t want to do it. She taught me to keep house, she taught me how to sew, she taught me how to cook, and then she just kept giving me more and more responsibility the older I got. 

She just didn’t want to do a lot of this stuff. She wanted to do her artwork. She wasn’t ill. She had indefinitely ongoing depression a lot of different times in her life that I realize now she was coping with, having had it myself.

*Now she was a cellist and also a sculptor?

Right. She started doing her sculpting work in about 1940 and then she got really into it. She went through major surgery. She did have an illness, no doubt about it, because she was diagnosed with cancer of the ovaries and not expected to live when I was 8. She went through the surgery and she went through extensive radiation therapy. In fact they goofed up the therapy and gave her too much. She was operated on in one hospital and then had the therapy in another hospital in Orange County where we were living. In one sense of the word, it was a blessing because it definitely did in cancer but in another sense she had ongoing problems with her intestinal tract the rest of her life. That’s part of what would happen to her. She was ill in some ways, but in some ways it was hypochondria I think. It just seemed like she was never a really happy person for a good part of her life.

*Was she still doing the cello at that time?

Yeah. By the time I left for school, she had two permanent students that she was teaching all the time. The Cassals method of cello, which is a certain fingering that’s different from the standard fingering for teaching cello. She did study under either somebody who was a Cassals student or maybe she even studied under Pablo Cassals for a little while. I can’t remember. Bland would remember that better than I would. Anyway, incredibly talented lady. She taught me to be extremely loving and demonstrative. She taught me to love color. She taught me to love animals, she taught me to be extremely responsible, she taught me to cook, and to sew. There were a lot of things that she did for me that I will always be indebted for. There were a lot of sad things too. I remember that she was ill a lot of the time, or at least she thought she was ill. That used to just frustrate both Bland and I. She used to ask Bland and I to do more and more stuff, either financially for Bland and physically for me.

Bland actually paid money to keep our household going when he was working. He was trying to save to go back to school. It got to be very uncomfortable at different times. She just used the money in silly ways instead of paying the rent or paying the tax. I forgot she did buy that place in Altadena. First, we rented it and later on she did purchase it. When money came for the taxes, she’d use the money in some other way. Bland would have to pay the taxes on the place or something like that. It was not easy.

Well, you had to remember I was the oldest son, the first son, the only son in a family that was very male-oriented. They were convinced that if they just gave me enough training I, my grandfather got me a 16th size violin in the hope that I would be another, who’s the famous violinist? Menuen?

If I just had enough practice. But the only problem is by the time I was six, I was burned out on violin, and switched to piano instead. I played piano for a while and cello for a while. There was no getting out from under my family, and they were too good. My father and my mother were professional and boy was she professional. Cellist musician at a time when women weren’t professionals. And then a professional sculptor later on. In 1931 at my birth, she listed herself as a professional musician. Fred listed himself as a professional chemist, and they were very serious about their professional work.

That was probably a downside. There was no way in that environment that I could go anywhere and compete in any way. Hollinger was a very good flutist, and taught me the flute. I took flute toward the end of my teens and that was kind of fun but I ended up dropping it. Again, overload time.

I’d also been taught to be an artist and a musician. I went back down to a sort of niche to visualize painting and stuff without really quite picking it up. I tried the edges of photography too because I’d been a photographer often in the research I was doing, if it was biology or physics, or physical experiments.

### Judith and Clyde

Yeah, 82.  Coincident with Clyde’s suicide.

*With what?

Clyde’s suicide.  Coincident, almost to the day.  So ___ started my company, get it up and running ___ by Clyde’s suicide but I come down and help.  That was a real tragedy because ___ better treatment for ___ depression.  But at that time his problem with depression went basically untreated, and then he just couldn’t drive himself to ___ place, made a number of investments as to how he would have prints of his stuff made, never sold, and that was the final blow, but if that hadn’t happened, he and my mother could have had a very happy ___ life for a number of years, and so consequently needless to say, when my sister had depression, I take it seriously because __ somebody come through ___.  Do you remember the ___ at Riverside?  His wife and family history on his wife’s side had terrible problems with depression too, and he was so paralyzed about what he might do or could do, or how the medical profession is progressing ___ made some progress ___.  So.

My mother was a superb teacher.  She made her whole life, all of her life teaching master classes of the cello because she went and __ study I guess the greatest cellist of all time, was Pablo Casals, and she even studied the fingering that he did just one step remote from actually going to ___ followed all the students and then she would lay out all the bowing and all the other stuff, just exactly as he did it because he was such a great artist.

*She worked with some of his students?

Not master class type, you know the student who is ___ they have absolutely nothing more to learn about a cello than ___ people that she learned ___ Vandenberg who had gone so far ___ classical techniques with Casals’ techniques of fingering and bowing and all that good stuff and emphasizing ___ cuz he was partly Bach, partly ___, but at any rate, so she never failed to ___ herself but always was ___ teaching the techniques of all the stuff.  A superb teacher ___.

My grandfather, her father, my maternal grandfather there and that you see that was where I ___ was also a superb teacher and he taught both violin and he also got the group together to, the Pasadena City Orchestra work, and did all the sort of stuff that needed to be done. ___ so people could come together as an orchestra and do some degree of quality so he was a superb teacher both of violin and of the situation who, you need to teach people that worked there as an orchestra which is kind of different, cuz they’re good at both.  ___ then he also spent his time as sort of an inventor because he was, you know, mechanics and sciences, engineering, across the board.  So there have been people.

But as you notice I don’t say that my father was a great teacher.  Later on when my mother remarried and when she married Clyde ___ who was a wonderful teacher of art and ___ teaching art to people.  So not only did they have a ___ both were professional arts but they also were professional artists that were superb teachers both.  So anyway those kind of things just, I wanted to say something about them because they’ve been so very important in my life.

At the beginning of 1982 our mother had gotten extremely ill.  Oh, well, let’s go back to 1980.  I think it was, let’s see, or was it 82, when did Clyde die?  82, wasn’t it?  OK, it was 82.  Just as the twins are going to graduate from college, Judith had remarried in the early 70s to an artist, Clyde Zolsch, and really had a fantastic, happy marriage for a while.  I mean she really did have a time in her life where for the most part she was you know really had a good time.  She came into an inheritance, it was an old trust that was set up by our great grandmother that when my grandfather and his two sisters died, that the trust would be dissolved and she inherited about $72,000 at that point and she and Clyde rebuilt this beautiful home in Corona del Mar for their home and went to the South Pacific twice, something my mother had always dreamd of.  Where did they go, Bland?  It wasn’t Tahiti, it was one of the other.  Anyway, went down to one of the lesser toured places in the South Pacific, something that my mother, our mother always dreamed of doing.  She got to do that twice.

They had their own gallery for 10 years in Corona del Mar on the Pacific Coast highway.  It was called Clyde Sells Originals and it became a landmark site in Corona del Mar on the Pacific Coast highway there and then in the early 80s of course Reaganomics took place and we went into a recession and people weren’t buying art any more as a way of whatever, way of life I guess, and my stepdad got into, Clyde got into financial problems and in 1982 in April he committed suicide and because of our mother being the type of person that she was, it totally devastated her in more ways than one.

She never really, never really came back from it.  She was severely depressed the rest of her life to the point, and now, you know I couldn’t understand the fact that she couldn’t ever go back to her art work and she just couldn’t.  It just wasn’t there, you know, all the creativity died with Clyde and then she started having serious ill, you know, physical problems too, so one of the illnesses that she had was that she had to go in for some abdominal surgery.  She swallowed a toothpick of all things and it lodged in her intestines and they had to go in and take out a section of intestines, so I went down there when she went through the surgery and I was supposed to be able to come right back home.

She came out of the hospital and was all excited about you know being able to do things and whatever and she overtaxed herself with some physical therapy that the physical therapist had given her that was incorrect.  He really didn’t check with the doctor what she could and couldn’t do, and she fractured her spine.  So I got to stay there for 4 months while she recovered from this spine fracture, from January to May when Jim and Debbie got married, and so that was the D-day when Jim and Debbie got married.

I was going to go back to Madeira and meanwhile Diana and Gordon were living up there.  You know Diana is going to high school and Gordon in Madeira trying to communicate with each other, and Diana was always a rebel.  She was the only one out of the 3 kids that would really backtalk her father and he, Gordon had some real problems.  He was a rage-aholic, his discipline was way over what any discipline should be, and he was extremely hard on all of us emotionally, and the fact that he did not give any positive regard, it was very much the other way, what they call reverse psychology I guess.  So it was tough for the children all the way through.  They all I’m sure had scars in one way or another because he was very much into corporal punishment and many times the punishment did not fit the crime.  It really didn’t.

So if you want to turn the thing off, I’ll get Bland another muffin.

So anyway D-day was that, for Jim’s wedding, so that went very well and Judith actually made it and nobody got a picture of her and I’m so sad because she just dressed to the nines.  It was the first time that Judith and my former mother-in-law ever met in the whole 25, almost 25 years Gordon and I were married, and it just ended up being a super day.  A lot of people came down from Madeira to the wedding that were close friends, even some old friends of my former spouse’s from college days showed up at the wedding and it just, it was a trip.  It was beautiful, and then Jim and Deb paid for it all because we sure couldn’t afford it and it was just a really happy day.  So then I go back to Madeira.

*I’m confused here for a moment.  So the wedding was in May of 82?

Right.

*And Clyde died in April?

Yeah.

*While your mother was in the hospital?

Well maybe, no wait a minute, you’re right, you’re right, that’s not true.  Take it back.  That’s 83, 83.  Clyde died in 82.

-It was 82 definitely that Clyde died.

### Primary School

It was a really interesting time, but the start of it was that I invited my own friend Lattie Lamb there because his father had pulled him out of entomology. We sort of found each other. We were two kids in about the fifth grade charging around with butterfly nets collecting butterflies. In fifth grade it’s pretty hard to miss somebody else doing the same thing in the same way. My other side went in the direction of ecology and things like that. Mathematics and ecology have sort of been a parallel thing, they were always there in my life. Living things and mathematical things and stuff like that. 

After they shut down the school for gifted children which I think was around my third grade, something like that, because I sort of remember being then transferred back to Jefferson Grammar School through sixth grade, one through six. They split up in that area. One through six and a junior high and a high school and the beginning of college was the way that they tended to divide the school.

I remember being frustrated that I couldn’t figure out how long division worked and so I went to try to find out how. I made a fuss about it, and the vice principal finally took me into the principal and said “Look, it’s time to listen to the way you do this stuff, you just follow these directions here, ta-dah ta-dah, and the multiplication division table. You’ll only use parts of these other things some other time and so on.” None of the reasons why I was learning the multiplication and division tables really follow out of problems of long division. If you try to do long division of big numbers, you need to memorize some of those values on the way there, OK? Things like trial divisors and stuff. I was always headed into it from sort of a twisted direction and getting into trouble for it.

I always had this very fascinating interest with probability theories and numbers and how those kinds of things worked. I had it growing up. Very early in childhood, I used to hide under the dining room table, when they didn’t rout me out, and listen to people going on and on about probability theory and what it really was doing and so on. So those are the reasons that I’m sure for the whole orientation of the work that I ended up doing later on in the university. It was just the direction that followed naturally from my own interests and what I studied. 

I tried to make sense of three-valued logic, multiple-valued logic. Somehow you could factor in the variability of the objects in life systems, ecology. I was always echoing back into ecology. Lattie Lamb and I were reminiscing over the fact that back at thirteen, I just graduated from sixth grade at Jefferson and I was going to John Marshall High School.

All of a sudden I discovered this thing and then that echoed through my life, it turned out this was before the great Marine book came out, “Between Pacific Tides”. I was a very difficult teen. Teenage is difficult for anybody, but if you had a divorced family and you had also been pushed on as hard as I had been to perform, it’s just doubly hard. But I met the McGinties at the Kerckhoff Marine Lab, who were wonderful to me at that time when I visited there.

### High School

I had some pretty bizarre reading habits. I remember it was the end of high school when I finally got a library card in Pasadena. Libraries were incredible resources. In about 11th grade, I was in Pasadena City College on Colorado Boulevard taking Boolean algebra. I tried to check out Boolean algebra from the local library and they were sent to the Los Angeles library. They didn’t have it. So they went to the LA Library. They said well they thought it would probably pay some moderate fees for shipping and handling and postage, they would search the state, they searched the state and they didn’t find it. This is Boob Bool’s original works on Boolean. They were sent to the Library of Congress and I got 2 of the 3 original books. At that time there were no copying machines. At that time, the Library of Congress was still circulating things like Bool’s original books. Mind boggling.

One of the instructors in the chemistry course was showing me his big secret trick for managing to solve these things using a slide rule. The slide rule just was my constant companion after my first one was given to me by my father at the end of high school. I just thought it was an incredibly valuable tool to help me solve tables to look up. The problem was getting one digit more precision, to the fourth place in there, beyond a graphical table. You had to add on. I used to carry that graphical table and a Japanese style slide rule where you could raise things to odd powers and take roots and everything like that with the table logs.

Every time you thought you were going to deal with real numbers, it was a hassle of high degree that you had to find some way around, tricks or whatever it was. Or go to some kind of table, tables always seemed like they were for the wrong function or the wrong thing for the wrong thing. People spent their entire life doing variation and normal distribution and linear theory of one-dimensional variables via tables. My entire lifetime was always spent with these problems. Half of the people’s brain is so poor at working at mathematics, even if you make a real effort at it, compared to machines, compared to computers.

It’s a weird thing. On one hand, I could do theoretical mathematics and do well. And when I took geometry in high school, I took all the extra problems and worked on them. We had a break mid semester in Newport Beach. The teacher actually got up and gave a lecture to us that I was his most valuable student and that I thought that it was the neatest thing. It was so neat to see some hard problems and do them. There was a really neat attitude to him. So I went on to Newport Beach for the geometry course. I was doing the extra problems and doing all the extra work and dealing directly with it. And guess what? At the end he got up and complimented me again for lots of the stuff that I had done in that class and gave me at least an A. Or it may have been an A+.

It happens that it’s the same point, I was taking an algebra trigonometry course. The person teaching it was the gym teacher at my high school, and I hated the way he taught it, I hated the gym teacher himself. He would teach on the side to get some extra money, trigonometry, and mathematics of any type. But he taught this and it was the most terrible course I ever had. I flunked it cold for two years running. That was still sitting on my record when I tried to graduate from high school. I was determined to never pass it, and I never graduated. So who’s right? I found out later on that I needed the high school graduation to be able to get myself into college.

I graduated from high school finally, and several people went out of their way to help me. I was always a weird student, as far as more formal ways of teaching were concerned. Some people would not think that I was wonderful, other people would very much like me, so it was quite a spectrum. It never was really easy for me to move through school anyway. There’s always been key people in my life and that’s really wonderful.

This is what happened, around 1950. I was given some additional tests by the department wide psychometrist Mrs. Barison. She was the key person that oversaw tests or had special tests given. She asked me if I would be willing to come down and take a few GED tests that are normally given to people who are returning to school. I aced them all. But, it turns out there’s a certain time you have to spend in the seat learning in grammar school and high school. If you don’t spend so many hours attending class, real hours, you also don’t get credit. It turns out that I had to take a summer course in trigonometry that another teacher was teaching at Pasadena City College, during the summer. She insisted I pass the exam out of her class and then she’d get credit for hours. For a week jamming, getting ready for the final, I managed to pass that test, and did OK.
