# Personal Challenges {#challenges}

## Ecology and Wild Animals

I always go back to things related to the environment,
related to ecology my whole life.
I've always liked plants and animals;
they had a special effect on my work.
Really enjoyed working with all kinds of them.
I even enjoy domestic cats and dogs.
My special favorites always were wild animals, my special love.

One of my haunts was Kerckhoff Marine Labs at Caltech
when I was growing up as a teenager.
The other one was the Whittier Narrows area
where they have all the quicksand and upwelling
before they pumped out the water table
and everything in the peat bogs died.

### Bland’s Pets

I can certainly remember that before grade school I was interested in collecting things.
We had a very elaborate fish pond. Everything was rare and wild.
I had a pet tortoise and bullfrog.
You name it, I had them.
Several kinds of tarantulas.
The only time people said no to me was when I brought home a rattlesnake.
They said no way are you going to keep a rattlesnake.
But that really was about the only no.

I had lots of very bizarre animals that I used to rear.
Cigar boxes from the drug store would work very well for rearing caterpillars and stuff,
to watch their development.
I'd trade with another friend that collected insects.
I liked the eggs just laid on milkweed
and I'd raise them through all the different larval stages
to the pupae which would turn into a monarch butterfly.
I did that regularly as a young child.

My maternal grandmother was the one who put up with all these crazy animals,
and wild animals.
She would even take on the night feeding,
at 2 a.m. when I was too tired as the birds had to be fed.
I was working for the Audubon Society when I was growing up.
At 12 I raised a banded pigeon when there weren’t any around yet. 

I had an incredible menagerie of animals. I raised owls, blue jays, and pigeons.
The pigeon Prancer Dancer was all over the house and thought she was a person.
My grandparents’ house had a really high ceiling and the kitchen cabinets only went up so far,
leaving a big space between the top of the cabinets and the ceiling.
We’d line all that with newspapers so Prancer Dancer could sit up there
and do her little roosting thing.

I raised tarantulas, and snakes.
People around me learned to be really sensitive to animals
and in their environment and gentle with them.
I talked to animals, going tsk tsk tsk.
These crazy owls were fed with raw hamburger
and we’d have to clean the hair brushes out
so they’d have some hair in the hamburger so they’d survive.
I got written up in the paper as being the youngest Audubon member
that they had in the area at that time.

I trapped dragonflies in mist nets and marked them to watch their territories.
We have dragonflies around the pond.
They’re pretty easy to mark.
You take fingernail polish and you just fill in cells on the wings.
You want it to be on the leading edge near the main vein and near the body
so it causes minimal changes to the mass of the wing.
Use colors, so this guy is red and blue, and this one is green and orange or whatever.

### Skunks and Squirrels

About that time I had been working on training skunks to be gentle.
They could be held by people—both the common skunk and the striped skunk—so they could be taken around to schools.
These skunks were natural so eventually they could be released in the wild.
If you read their language right, you can back off and pet them and scratch them in their favorite place.
So there’s a whole language that you can teach people and work with them.
The only problem is that occasionally something else would happen where the skunk would spray you anyway, which is very messy.
One skunk ended up in a lid type garbage disposal, and I had a terrible time getting the skunk loose.
Ruined my tennis shoes and clothes.
I wore the shoes to a Christmas messiah and then realized they still stunk.
We emptied out that entire rear row of seats of the theater there in Pasadena.

I once caught a squirrel by grabbing its tail.
But it came around the tree and bit me seriously in the thumb.
It wouldn’t let go.
I had to slam that into the tree to get it to, and then I stunned it enough to let go.
I went to the emergency room, and they were very concerned and so they both cauterized it with a strong acid, because it was a very ugly looking wound.
I was behind on my tetanus toxin so I had to take the damn horse serum size.

### Girl Scouts and Kids Groups

I used to volunteer to take kids on nature walks along some of the trails that I had marked.
I used to gentle train wild animals ahead of time so that they weren’t into biting people.
Say a gopher that was through feeding and had never been mistreated by a person.
If it were mistreated, it never forgot and you could never trust it because it would always bite you.
So it could never really be used with kids in a safe way.
I learned how to gentle train animals so that you could work safely with kids,
and save my own fingers too.

I tried to get more education about natural kinds of things in school.
I used to volunteer a lot of my time to work with children and kids.
In the early 50s was the time when I especially did a lot of volunteer work,
and in the 40s when I was a teenager.

Particularly if you’re the only son of a family,
everybody taught that women were incapable of doing many things.
First I volunteered briefly for some of the boy scouts and boys clubs,
but they had lots of help.
But there was this huge hole for girl scouts.
Girl scouts had no volunteers, so I started volunteering for girl scout clubs
and my father would take girl scouts to the top of Whitney and they never had any problems.
We conditioned them on the way up to handle high altitude.
I essentially volunteered time for a group like that and then I took them to other places.

We went at a reasonable time of the year for the temperature for Death Valley.
People at the time were saying girls would be sick, they wouldn’t survive.
They had the greatest time that you ever saw.
They were the best girl scouts that you ever saw in your life, and they loved it.
Anything I could do for women to help them.

How do you work with these animals and kids?
It turned out that if you just included enough interesting things to do, kids would line up.
I provided some very interesting nature.
We cut the trails ourselves, I put in some of the nature areas,
with other people in a sort of a group thing.
I helped cut the trail because they were a beast to cut through the underbrush.
It looks a little like old Tarzan movies.
I found that by giving the children a lot of opportunities, there was almost no problem.

I found that girls were incredibly willing to work.
I volunteered my time both to work with 5th graders which I think was a neat grade
because they’re old enough to have some attention span.
I took them to the local park where I’d turn them loose.
You couldn’t go across the highway because cars were on it and you’d get killed
and I was very blunt about that, but you could go anywhere else in the park,
and then I would turn them loose and they would just run free.
I would anesthetize insects and then they could look at them with a magnifying glass
and we caught every kind of interesting insect.
I would show them how butterflies suck nectar off of a flower, and just turn them loose,
and the teachers and the parents just couldn’t believe it.
These kids ran and ran until they dropped.

They were so enthusiastic about San Marino Park,
and it was a beautiful park. It was half wild and half native,
with a whole lot of flowering plants that would just flower all year around.
It was a neat area to use.
Later I volunteered for the girl scouts because I felt that they had been totally neglected.
People believed that at about 10,000 feet girls would get sick and die of altitude sickness,
and that they wouldn’t be brave and they couldn’t do various things.

I volunteered with Mary Ellenson and quite a few families with all girls.
We taught them how to climb to 14,000 feet without getting sick.
The girls were doing fine. It was really crazy.
So we’d stop at a couple lakes and camp.
Teens have a very difficult time.
I was always volunteering for teen groups with a bias toward girls.
I was in my early 20s, 20 to 25.
At that point JPL suddenly took over my life.

### Birds and Pasadena Audubon Society

I was always raising stuff or doing animal rescue at the Audubon Society.
I was always getting an incredible number of birds that had been tossed out of nests or damaged
and then I would hand raise them and try to feed them enough to do something about getting them up and healthy.
The other trick was to put them out on my grandmother’s line which she would hang her clothes on.

Birds have incredibly strong gripping claws and a fist that will grip properly.
I raised birds from eggs.
When they begin to feather, you have to worry about exercise, so they don’t atrophy.
I put them up on the clothes line, carefully wrapping their claws around it
so they would grip the clothes line and let them balance.
It turned out to be an excellent way of having them learn how to flap flap flap their wings
and someday it would be fly away, the whole schmear.

I occasionally would get woodpeckers.
The woodpecker group was really neat.
I was showing one of them to my friend Laddie and his family.
The family’s cat, which was raising a litter of kittens, saw me and went across the floor
so fast that I could not deflect it.
The cat was on a mission of nailing that bird that I was showing to Laddie,
and carrying it off to its kittens.
So there were always tragedies along the way. 

It was an opportunity to constantly learn more about diet and exercise and release.
I always color banded them because I wanted to be able to follow what was happening on an individual basis.
I managed to band lots of birds.
Indeed, the first bird that got me into all this was a band tailed pigeon
at a time when they were just coming back from hunting pressure
that essentially had run them into extinction in the United States.
Nobody ever saw band tailed pigeons.

I got crossed over with Dan Quattlebaum the president of the Pasadena Audubon Society,
who was my wonderful savior.
I volunteered with Quattlebaum from the Audubon Society
and the MacGinitie's, a wife and husband pair of doctors, at Kerckhoff Marine Lab.
They were superb teachers, and helped me get through a very tough time. 

Quattlebaum taught me birding in the first place.
There was this squab I was trying to raise.
I had gotten different kinds of grains, and would add little bits of boiled egg.
It had to be boiled to be digestible to replace the regurgitated stuff from the mother bird’s craw.
It turned out that I ended up with an incredibly healthy band tailed pigeon by doing that.
I would squirt down syrup many times a day,
my grandmother sometimes helping at night.
Really labor intensive stuff.

I came out with a band tailed pigeon, as identified by Quattlebaum,
and he couldn’t believe what I had.
I put my color band on it and it brought in a whole flock of other band tailed pigeons
later on to my grandmother’s delight.
It ended up living for years.
It would still come down to me and let me feed it individually.
I would hold my hands apart and it would put its legs between my hands like this and rest.
There was something about that position for birds in the dove group, that put them almost to sleep.
I would brush the forward direction, backward direction on the feathers, or the head.
It seemed to just go to sleep in my hand, totally content.
She came with young for years, who were out on the ground;
wisely enough they wouldn’t get any closer.
But that one bird would still do it years later. 

I was getting at gentle training, and now the whole world has gone that way which is neat.
They used to figure that if you just punished an animal enough, they would come around in time.
The first time you’d turn your back, you’re dead if it was big, or it flies away.

I had a special affinity for crows and ravens.
Especially ravens.
I think ravens and the Corvid family were my favorite birds.
Jim Barbieri had a whole bunch of crows at his place in Lafayette.
I was able to feed them and after I fed them, then they got on my head.
I’d stay in there for hours.
Jim was trying to work with eagles, golden and bald eagles,
but they were in such sad shape. 

Between Pacific Tides and Kerckhoff Marine Lab

When Laddie Lamb came by to visit one time,
we were reminiscing over the fact that it was clear back in sixth grade
when I first discovered ecology and then described it to him.
I had just graduated from sixth grade at Jefferson
and I was going to John Marshall High School.
All of a sudden I discovered this thing, which echoed through my life.

It turned out this was before the great Marine book came out,
"Between Pacific Tides" by Edward Ricketts.
The whole orientation was ecological for the first time.
He was a famous marine biologist.
It was interesting because it was the fellow that wrote the book,
Steinbeck wrote about in "Cannery Row".
Ricketts discovered the idea of ecology with marine stuff,
and was working on the book between Pacific Tides.

George MacGinitie and his wife were sort of my savior
going through high school, when I was a teenager.
They essentially filled in the other side of things
from an ecological point of view.
I absorbed from them the idea to take an ecological approach
where you look at habitat, like sand is different from a rock
or a highway that is different from the Pacific Coast.
Three different habitats when you look at them ecologically. 

Look at Ricketts, Ricketts and Calvin.
Ricketts was the famous biologist who led marine biology
and then he died in a car accident unfortunately,
just before his book was to be published.
So Jack Calvin went ahead and finished it because of his sister.
Masterpiece.
They showed me the preprints of the thing.
They said, “Oh you’re interested in ecology.
Let me show you all these preprints.”
The idea was bouncing off of them,
the guy that was doing it said “here, look”.
Wow, far out.
You know there’s been those kinds of things.
I’ve just been totally blown away by the quality of work
and the insight in the work.
I couldn't have such a richness in my life if it wasn’t for people like that.

I went to work for Lars Carpland (?) on a limnology program
that was supposed to sample all the bays up and down the coast.
There was a problem of salinity dependence on rainfall.
You could have a downpouring rain that could be fresh water.
Plus the temperature range was mind-boggling too.
I went around and sampled these things.

At the time I had just left a job where I had been doing glass blowing.
One of the things that they gave me that was so neat
was a whole bunch of transistors that were outrageously expensive
at that point still.
They gave me a whole bunch to do my own thing back at school.
IIt was hardly larger than a C battery because it drew no power.
Man did they draw power and heat.
I took the same miniaturizing technique that I had been doing
and I built a little small sensing unit that would sense the resistance of water in between.

I was the one who was supposed to pick out a boat to go do the sampling.
We were supposed to visit all the main lagoons all the way from their island at Scripps
down as far as we could go.
They rerouted them and dredged it and so forth, and all of them in between.
I went up there with my tool and took samples.

There are a lot of bridges that have been bypassed by the coast highway,
which they wanted to turn into a super highway.
The main coast highway bypassed most of the small back roads.
The small back roads still had bridges that crossed lagoons.
I’d use those to get into the middle of most lagoons.
Then I had the sampler I was supposed to use for standard oceanographic work.
I pulled a sample out and of course it completely mixed up the water
because it was so huge and so bulky.
You could only get one single sample out of it anyway.

I would lower my little miniaturized thing down.
I had also created a feed to a type of battery thing
so I had a neat little tool.
I could calibrate that so it would read either end.
Conductivity or temperature.
Wow, I put mine down there, and here it was filled with water,
radical differences in temperature and similar data.
I went to another with a light breeze blowing
and it was a constant temperature from the bottom to the top.
I went to yet another where they were having some problems
from stuff being dumped in.
You could even watch it being spilled into the side of the bay,
it was in such quantity.
Here was this bright green water
because it must have been going on for a while.

I ran that one and I got a totally different profile
in terms of temperatures and resistance,
totally different than if I used the standard sampler.
Here was this whole area where people were using devices and tools
that were created so they wouldn’t have to deal with the variability.

The one other thing that I did was that I walked and walked and walked
and ran and ran. That was my way of keeping my sanity,
and I loved to do it in places that I could breathe. 

Some people have no problem,
but about 10% of the population apparently inherit a problem with allergy.
If you’re part of that 10%, you’ve got real problems with getting sensitized.
Boy did I ever get sensitized,
both to poison oak and air pollution.
Poison oak was always out there hashing around where it shouldn’t be;
I learned to recognize it in the off-season.
Growing up in the worst of the LA smog,
I almost lost my lungs.
That’s what got me into hiking and running long distances in the mountains.
I would always pick the brightest and freest, most interesting places I could get to.

## Huntington's Chorea

Interestingly enough the most hazardous, most dangerous thing I do in life,
I’m doing that now. [Taking pills]
Most people with Huntington’s Chorea eventually die from choking on food.
Need to keep my hands dry too or the pills get too sticky.
OK, enough about me, enough, enough, enough.
Where should we go from here?

I have developed this squeaking as I breathe in and out.
I can’t really hear that much myself.

Davd Baasch says it’s nothing to be concerned about.
It’s just one way Huntington’s chorea will kick in,
just like I can’t make a constant sound.
My vocal chords get tweaked and it just puts a tone in my breathing in or out,
mostly out I guess.
The progress of Huntington's chorea remains pretty slow.
So that’s good.

### Huntington’s Chorea

<div class="source-block">
1: Dad identified in 1960, biology of HD, Woody Guthrie


26. Huntington’s Disease        hd.1-26

        Present Time / Health        hd.1

        Grandfather Bland        hd.5

        Father Frederick Jr Ewing        hd.6

        Bland’s Early Signs        hd.9

        Bland Moves to Grass Valley        hd.11

        Daily Routine        hd.16
</div>

[Routine of sitting – takes off walking shoes, puts on warm slippers.]
If I’m sitting very long, I need to put warmer shoes on my feet to keep from freezing.
I keep the house as cool as I can to conserve energy
but I find also I’m a lot more sensitive to the heat now.

Two things, otherwise I have a tendency to forget where I am or what I’ve done.
So there’s the physical arrangement of things
where I have my chapstick and my glasses and so on things like that.
I find that if I get things scattered around the house very much,
it very quickly gets so that I can’t find anything
and I can’t remember which things I have and which things I haven’t done.
So I find myself in the process of trying to fight the Huntington’s disease,
I lay out a preordered life.
That way I can get more things done than I could otherwise
by doing them in a pattern,
and look like pretty much of a neatnik
but it helps me get things done successfully.

*Yeah, I’ve noticed that you always have your glasses on the table over there.
I remember that from other visits.

If it’s not where I have them, then I have two or three other places
that I tend to go to which also work well.

*Well I have some of that same problem.
If I set these glasses down, I have to go back and say no, I can’t do that.
I have to put them in my little black bag or in my pocket.

Because there’s just too much of a chance that  if you don’t sit on them, somebody else may.

*Or I forget where they are.

Or where they are, yeah.  So that whole thing,
to make it so that I can do more things successfully,
I find that I incorporate more and more things of that sort into my life.
I guess what I will do now is I will take some vitamin pills and things like this
which I normally take them with my meal,
but not brush my teeth because it just takes too long.  OK?

*OK, go ahead.  Do what you need to do.

Cholesterol levels are good and other things like that by diet rather than drugs.
Saturated fats and partially saturated fats seem to foul me up too.
I try to stay away from hydrogenated stuff.
Notice what they’re extracting here?
These are percentages. (shows butter container)

*60% vegetable oil and 6% sweet cream, yeah, that’s what we were talking about.

Yeah, and it ends up tasting just like butter
I remember from the old days, but it’s better for me than the butter from the old days.
So that says exactly what you’re describing.
Interestingly enough the most hazardous, most dangerous thing I do in life,
I’m doing that now. [Taking pills]
Most people with Huntington’s Chorea eventually die from choking on food.
Need to keep my hands dry too or the pills get too sticky.
OK, enough about me, enough, enough, enough.
Where should we go from here?

*OK, I know that you’ve done a lot of thinking about how the mind works
and we were talking earlier about exercising your muscles and keeping those connections
to your brain and all, mind-body connections and just how the mind works
and how organisms work as intelligent beings.
I wonder if you have any thoughts on that,
I know you’ve read about that and thought about that.

Well, of course.  You can’t do anything.
In life socially. Happy or sad and things.
Everybody thinks about it and come to different conclusions
and different stages and times in their life, their phases of life.
Isn’t that a variable with large component over variation.

I have a feeling that people should be suspicious of things that are too extreme.
Too little or too much.
Mill around and lots of things are pretty dull,
it’s hard to tell after a while.
What probably makes the most sense most of the time would be in the middle.

Like the story of the Long Distance Runner.
I used to for years.
That’s one thing I probably miss the most is long distance running.
It wasn’t just joy, it was a way of helping my mind.
I had a best friend, Bill Pilkington, on the long distance team at Caltech.
Even though we danced around each other a lot at the beginning,
we actually got together.

We started talking to each other, visiting on our long distance runs up behind his house.
That’s when we finally started to socialize and then one thing led to another from that.
He also was into long distance running as a way of thinking and doing and helping his mind.
Great company. OK, we’ve gone far enough, time to turn around, head back.
Got to slow down or I got to walk for a while, whatever it was.

So I’ve always tolerated people but you can’t have a it both ways.
It’s a two-way street.
If you just run your mind without using the body.
People that run their bodies to the limit without the control and direction of the mind yields no healing of their mind.

In my own family there were illegal drugs, like alcohol and nicotine.
They probably could never stop smoking.
My aunt and uncle on my mother’s side could never stop drinking and smoking.
The devastation in their lives, doesn’t happen at once, but the cumulative damage is incredible.
You start adding up 30 or 40 years or 50 years, but very few people make it that long.
If they do, they have this poor health.
Man, where would they have been if they hadn’t abused themselves so much?
It’s obvious that you pay, given a very useful body, a very healthy body,
to have it last that long the way it’s been treated.
I see nothing useful for drugs and alcohol except under limited social conditions.

And I even find that fasting is an interesting thing to do.
When you fast it turns out the first thing that goes is long-term memory
so you don’t have memory of what happened to you any more
than if you’d been drinking alcohol.
By giving people sugar, all of a sudden their memory comes back.
There were people that thought that sugar was too good.
How could it be that good for you and then be bad for you?

###Linus Pauling

Linus Pauling saw that there were some patterns,
by gathering data for analysis.
He was participating in them from the point of view of value of drugs and nutrition and things like that.
Things like smoking and drinking is radically shortening people’s lives
and what they were shortening was the healthy part of the life.
People would come down this curve of health into maximum health at about 20
and then instantly heading to decreasing health that you normally have at 50 or 60.
With all the good part knocked out and.
Pauling put these curves up.
They’re one of the lectures of his I attended at Caltech.
So now you were asking me if I went to some of the classes,
and yes I did.
I knew their public, and it was very interesting to see that point of view.

So Pauling actually made a very wrong decision on some of the stuff he did.
When Pauling comes along at the end of his life
and comes out with another book, sort of looking at the problems of sugar to cholesterol.
It’s a direct synthesis so it becomes this increasing growth,
well he might have picked the increasing growth of foot size
which is also increased almost the same as sugar is.
But he didn’t use foot size.
What he did was sugar use.
But it turned out to have the same correlation importance
as if he had used foot size as an increasing thing.
So I keep some books around because they remind me of the problem
of trying to rationalize.
Even the best experts, seeing right smack in the middle of the field.
And there he blows it.
He blows it totally.

Let me say a last couple of things because it’s an important point.
The first thing you would do for a person with Alzheimer’s disease
is give him some sugar to increase his memory.
I would like to see again Pauling’s book,
"How to Live Longer and Feel Better", his final book on diet and sugar.
So that’s a real good thing to try to describe.
He wrote so many till he finally guessed wrong.

People get anorexia and muscle spasms from the so-called legal type drugs, like tobacco.
What you see is a person waking themselves up because they’re having problems we never had.  When I was in Silicon Valley, a person specialized in two groups of people, interestingly enough, overweight and underweight people.  He specialized in people with their dietary problems and it turns out there are two sides.

### Bill Pilkington, Death, Being Funny, Hygiene

I ended up going to UC-Riverside eventually.
Going after Bill Pilkington died.
So it’s also ups and downs all through my life.
Life spotted with deaths of people, key people.
So there’s been those things of death in my life, for some weird reason.
At the death of my grandfather he was sorry that he hadn’t come back home,
because he realized how universal all religions were later on in his life
and that the grief I was feeling and the difficulty that I was having,
he would have liked to have helped me through.
But at that time in his life he couldn’t cope with it
because he hadn’t experienced any death in his life.
His family and other people were near by him,
together with fundamentalist religion.
So he had to walk away.
So there were lonely times too.

But there’s also that thing in all fairness.
I’ve always been basically an optimist
and I’m an up sort of person
and I’ve always thought I could always do more than I really could do.
Always an optimist and always liked, things were fun or funny.
And I always enjoyed people being funny.
I always loved to laugh.
Sometimes I’d be delighted by some pretty far out kinds of stuff.
Jokes on other people, but kind.
I was always a gentle person.
I was always careful not to really hurt anybody seriously,
but to scare them was fair game.
Scaring others, being weird myself.
I always had a certain degree in weirdness so.
But it wasn’t right to gross people out either.

This really bothered me with the engineers working both there at Berkeley and some of the other places.
One of the ways that the engineers proved that they were engineers
was by how many days they could go without taking a shower or brushing their teeth
and I’ve always had a very sensitive sense of smell.
I’ve always been very much into food and cooking food
and other things like that has always been a thing of my hobby.
So when you walk into a room and it smells like somebody had died in there,
always said somebody had gone sick, you know,
I just never have been able to stomach it.

I’ve had very little patience with anybody that won’t take a shower or brush their teeth.
They get let out of my space real fast.
It’s weird.
Even at this point, and at this time of my life,
and even though many people do lose their sense of smell,
fortunately I’ve kept mine.
So I still have a very good sense of smell apparently,
and it remains a thing that I’m always sensitive about.
I’d never consider engineers were proving their devotion as students to the project
just by not taking any shower or brushing their teeth.
Really, that’s not the way to do it.

C: Part of why Bland is so tenacious
and hangs on so much to what independences that he has
is because he remembers all that stuff.
He just doesn’t want any part of it to go
if he can possibly avoid it,
and I sympathize with him.
Some day he may have to be in a wheelchair,
but we’ll cross that bridge when we get to it.

*He’s not falling down a lot,
I mean Dr. Brasch didn’t seem to be concerned
about that right now.

Well, it really helped when we got him to finally accept the shower chair,
so he could sit down.

*Yeah, I saw that.

Yeah, it really, I mean now he still bangs around some but it doesn’t sound like he’s coming through the wall.  But of course he did fall in the shower that one time and I heard him. That’s when we talked him into the shower chair.

*And the handles.

Well, the handles were earlier.

+Are you able to walk to the store, Bland?  Are you still able to walk to the store?

Yeah, but I can’t do it alone. If you’re going to trip and fall on the pavement, you can really hurt yourself.  People tend to fracture themselves when they have accidents.  The doctor's recommendation is I go somewhere soft. We’ve been going over to a park that has a natural  area.

+OK, so you’re getting out and walking?

Yeah.

+I was kind of wondering because I thought maybe you’d given up walking altogether. You used to do that every day, an essentially part of your day.

Grandfather Bland

*What were your grandparents’ names?

I guess it was Sylvia Ann Corson I think.
Reginald Bland was my maternal grandfather.
And on that side I had lots of lots of family members
and I, on my father’s side,
this is why the Huntington’s chorea didn’t show up
and when it did, they couldn’t, they didn’t correctly identify it
for a long, long time was, cuz I had no relatives.
Almost all were either killed in the Indian wars or the Civil War.
Nobody ever made it through to survive.
They all got wiped out in the Civil War
and then the Indian wars.
They seemed to be a group of pioneers ahead of the rest
who got wiped out.
So I didn’t have, on my father’s side any history of that.

My paternal grandfather he was already showing the disease
when Carmen was born, when I was 7.
I remember him having motion problems
and getting much more onto a wheelchair and things like that.
And at that time it was never properly identified.
He had also been injured where a couple of toughs beat him up in a park.
People just assumed it was due to brain damage
where he had been kicked in the head.

And so life goes and goes and goes.
Many twists and turns.
That’s a very bad sort of sweeping thing.

*Yeah, that’s a good place to start.
We can just sort of talk about whatever comes to mind tonight
and then we can get more focused tomorrow.

The only thing I remember about my paternal grandfather,
and this kind of pertains to where Bland is too,
is he remembers my paternal grandfather being in a wheelchair
and that they came to live with my mother and dad for a while,
when my grandfather got so sick.

My grandfather at the end of his life was a caretaker for the Parks and Recreation,
and one night he was working in the park after dark in the winter time.
He was very badly beaten up by some vandals and kicked in the head.
What they thought later, when he started the symptoms of the Huntington’s Chorea,
that it was from the beating.
But Bland remembers him being an avid reader,
being incredibly intelligent in his own right.
He was old enough to see him start to decline
and be in a wheelchair and all that kind of stuff.
I guess from what Bland has told me,
it was a real traumatic thing for him.
I was so little I don’t remember any of it.

*Well Bland said he really idolized his grandparents.
He wanted to be like them.

Well this is paternal grandparents.

*Yeah, paternal grandparents.

Oh really?  As I say, I only remember meeting them that one time.

Father Frederick Ewing, Jr.

Oh, that was another thing.  My parents did remarry when I was 16.
You know, he just kept coming into our lives more and more and more
and I think he knew that he was sick,
just like Bland knew in some gut way, and I think he wanted,
he knew what a good caretaker my mother was in some ways,
so he and my mother got remarried when I was 16
and then so that would have been.

*54?

54, yeah, and then in 1960 he was diagnosed with Huntington’s Chorea
and then I’m trying to think when, Jim was born in 61.
63 he was in a wheelchair.
So he must have gone into a nursing home in probably 64, 64 to 65,
and he was born in 1906, so he wasn’t very old.
I mean younger than Bland.
Have to do the math on it.
And he was in a you know skilled nursing or convalescent or whatever you want to call those places for,
let’s see, I went to see him before Diana was born.
That would have been 1968, so that’s 3 years.
That was the last.

*He would have been 62 then?

Yeah, and that was the last time I ever saw him, was before,
just before Diana was born, and I didn’t even know I was pregnant with Diana.
I’d gone down there on a family vacation
and Clyde and Judith were living together
but they hadn’t gotten married yet.
So they must have gotten married later on in 68, early 69, I’m not sure.

*So they must have gotten divorced again?

Oh no, you know what happened?  Oh, that’s a whole story in itself.
When he went into convalescent care and the bills became just astronomical,
they started coming back on my mother who had absolute, practically nothing,
and so she went to her attorney, John Josslyn in Pasadena and said, what can I do,
and he said, well number one, let’s just research the marriage records, number one.
Come to find out, my stepmother back in early 50s had divorced my dad in Mexico
and never come back into California and did the paperwork.
So basically when he married my mother, he was not legally divorced,
so her attorney then, when he found that out, had the marriage annulled.
After they’d been married what?  10 years or some such thing.

*But the financial implications were rather profound.

Rather pertinent, yeah.
So anyway, so she was no longer legally married to my dad in more ways than one
and relieved of the horrible financial obligations.

*Now he was an inventor, right?

Majored in physics and minored in chemistry,
and did a lot of work with Linus Palling in, you know, when he was doing all the molecule,
putting together the molecules to look at them,
and so on and so forth that Pallings was famous for.
My dad was helping him then.

*Now was he an x-ray crystallographer?
Did he do that kind of work?

My dad?  I don’t know.

You’d have to ask Bland that one.

*And then he was, Bland said something about he was a playwright and a musician?

Yeah, I’ve got one of his resume, let’s see have I got that in my stuff here,
or is that in storage too?
No, that’s in my stuff here.
I’ll get it out for you.
In fact that’s maybe where that other stuff is, come to think of it.
In my file here.
I’ll pull it after a while.

C: I’d have to think back on the time lines with him
but I know he was diagnosed in 1960
and I was pregnant with the twins at that time.
I’m trying to think.
I know he was in a wheelchair when Jim was two
because we went to see him.
I always called him pop because he didn’t seem like my father.

Yeah, 1960 was the date.
My father was identified as having Huntington’s Chorea.
Up to that time they just thought he might have some neurological problem
from the very his, he’d worked with a number of very toxic source
that ended up being way toxic then they thought the chemists would be.
And for a while they just thought that his neurological problems were based on that.
But then a neurologist who specialized both,
interestingly enough he was a neurosurgeon
and he also specialized in Huntington’s Chorea.
I guess he just took one look at my father’s motion
and things like a little family history,
talked of the grandfather that had the same motion
when I was growing up as a kid, when Carmen was born.
So it was like this, “You’ve got Huntington’s Chorea”.

I read the whole library trying to find something on Huntington’s Chorea.
All they had was just a few notes that were in the Encyclopedia Brittanica
and that was it.
Zero, zip, there was nothing, absolutely nothing in 60.
But also at the time they knew that it was a Mendelian dominant,
was not sex linked,
didn’t have anything to do with sex,
and it was totally dominant, never recessive.
It was character (Jed?), therefore,
and so then one of the autosomal genes,
so it would go down either the female line or the male line
with a coin flip.
Now it would divide as the genes sorted out
as the cells formed gametes for the fertilization
and there would be another coin flip.
So it would go down the male line, the female line,
with a peak probability, coin flip each time,
and then a coin flip as to whether the person passed it on or not.

Needless to say, it’s a real dent in trying to get married.
At that time I was well along in trying to marry Hilary
and we had made our plans and ta-dah ta-dah.
We really liked, loved each other
and almost nothing was known about it.
There was always the chance that some progress would be made
in it identification or things like.
But as it turned out it turned out to be one of the hardest genetic problems
that has ever come,
and they actually had to invent a whole new area of what do they call it?

*Short-sequence repeat.

Well, that was the secret.
The trick was to get long repeats to have the disease.
That’s why it has a spontaneous rate from nothing.
They have about one in ten thousand in the background population
where people have occurred spontaneously.
From that point on it is a full Mendelian coin flip later on.

*There’s a slippage during meiosis and development of gametes.

Yeah.

*Allowed to get longer.

When it’s under say a dozen repeats or something like that, it’s normal.
If it gets into the 20 or 30, guess what?
They had to make real progress in totally new areas of genetic engineering,
of genetics research, fundamentals of genetics research
to make any progress with the disease.

It’s taken from 1960 till now
—- it’s been 37 years since I knew that I had the potential Huntington’s chorea.
The folk singer, Woody Guthrie
—- people thought he was drinking and a theatre pulled him out.
He was supported by his wife and a nurse, a doctor,
through his last year that was so difficult.
She founded the Huntington Disease Society
because, when he died in 67.
Nothing was known still.
Which made her very unhappy.
So there’s been a parallel path in my life, all of it.
It was just too much of a coin flip.
It depends on determining whether you did or didn’t have it.

### Bland’s Early Signs

C: So Bland came in 88.
For my birthday in 1988, he decided that I should have my own computer,
so I could start a bookkeeping business of my own, or something.
He buys me a Mac SE computer with a beautiful radius two-page display monitor,
and an image writer printer.
State-of-the-art for that time, and software programs.

He has me come down to the Bay Area to pick all this stuff up
and I find out that he’s living in total chaos in this apartment he’s moved to.
There’s boxes that had never been unpacked from the move,
he was just wandering a few paths of just stuff all over everywhere.

The bathroom was absolutely beyond description Brian,
the tub had never been scrubbed and so it was growing mold in every color imaginable,
the shower tub, except where the water hit.
I mean it was just incredible with what he was living in.
It was absolute abject filth and it just broke my heart.
I just realized that he just couldn’t handle other than the simplest things in some ways.
I said Bland, you got the money, hire a housekeeper to come in here and help you,
and even that was too much for him,
so this was in April of 1988.

So I pick up the computer and I take it home and man, you know,
I could hardly even know what to do with it, I was such a novice.

The only thing I had ever done on a computer
was a little word processing.
I’d work from an Apple II computer with accounting,
the last job I had in the Bay Area.
It was just so far ahead of me.
I was scared to even plug it in much less use it.

In June of that year, his company realized that something was seriously wrong.
They said, “Bland, why don’t you retire part-time?
We’ll pay you part-time salary
and you go up to Grass Valley and help Carmen with the computer,
because you know it’s way more than she can do
and you can help her get it set up and learn about it and whatever.”
Man, I was elated.
I thought, “Oh this is wonderful.”
He said go find a place for us to live,
just like the old days back when my divorce came about
and we found a place in the Bay Area.

We’re going to find a place in Grass Valley. I started hunting.
This friend of mine told me about this place in Penn Valley,
which is like going back down Highway 20 towards Marysville,
that was for lease. I looked at some other places
and finally answered this ad in the paper,
not realizing it was the same place this friend was telling me about.
It was this beautiful cedar home on 70 acres
that had 3 bedrooms and 2 baths.
It was built by an artist.  It had stained glass windows in it.
It was just gorgeous.  Huge wood deck around it
with oak trees growing through the deck.
I mean it was just phenomenal
and it was in a price range that, you know, Bland and I could afford
cuz his half-time salary coming out of the Bay Area was like wealth over there.
So, and you know I was making some money.

You have to realize it’s only been since 19, it’s interesting ___ 91, 92,
I began to show the symptoms of the disease and almost immediately thereafter
and so I had to go onto, you know, ___ yourself down to nothing
into total poverty under ___ rules and regulations and everything.
So I loved horses, I loved the horses that I had gotten for Carmen.
Beautiful, gorgeous horses.  I loved raising horses.
I have spent ___ loving, raising horses ___ it’s interesting.
I rode ___ Arabian stallion, all over the field bareback yet.

*That was in Altadena?

That was in Altadena, yeah. All those things I had to get rid of.
I had to get rid of the horse, had to get rid of everything.
I had to suck poor Carmen into this mess.
She had support. After graduating, and her ___ mother, that was her main sport.
Here I saw ___ being ___.  I just neutral ___ thing near ___.
I had to spend, take everything down to zero, nothing.
I really had to go to zero. Society forces you to do this.
It’s a difficult time.  I almost committed suicide during that.
Very close to it, perhaps a half dozen times, on committing suicide down there.

I thought that really wasn’t ___. Damn it, I was going to fight.
By this time I had the new neurologist.

The first neurologist ___ sure that I had the disease.
I hated him. He always was putting me on drugs
so it would totally screw up my head.
They didn’t ___ my emotions one bit,
but they sure did screw up my head.
I can’t even say his name right now because I hate him so much.

*I have his name but I won’t look it up.

Don’t even ___ it.

I hate him. He had to be assigned to me by the state to make it legal.
I finally had to spin down through everything and do everything like that.
Here he was feeding his ___ was also screwing up and ___
while I was doing the thing for my emotion problem.
Finally I stopped ___. If there was any difference it was so small it was microscopic.
The reports from ___ the Society for ___ the careful reporting and research
and stuff said none of these drugs work.
They___ and they don’t work.

The guy hadn’t been reading any of the literature
and didn’t want to believe it.
He just wanted to believe the one company, his own drug company was ___.  Whatever.
Boy, did I hate him.

I came very close to committing suicide at that time too, very ___,
and then what did it do?
___ bizarre thing happens.
First the thing goes alright,
you have to go into the county thing, of zero quality and nothing ___ be exhausted
and not to drag poor Hillary.

I’m always trading names.
I’m calling Hillary Carmen and Carmen Hillary
and I’ve done it for an entire life.
To my great embarrassment. Hillary for Carmen and Carmen for Hillary.
Most of the time it’s not a problem
but there always are those occasional times.
Man, was it ___.  So to be brutally honest,
even those kind of things, you know, switch Hillary and Carmen’s name,
boy am I ever glad that Hillary didn’t get sucked into those things.
How unfair is it that Carmen ___?
___ she’s done nothing but work, work, work.
Very supportive of people, helpful, volunteers, everything.
Kids raised by, everything.  She doesn’t deserve it.

At least she didn’t get passed on the disease ___ that she might have,
since it goes down the female side ___ often,
it’s a coin flip with the male side,
and it’s also dominant.
So thank you God, thank you very much up there,
God thank you again and again and again, you ___.
It’s just so ___ but so.  The other side, OK, so.

Another bizarre thing ___ is then they ___ you got the disease,
well after all this time finally you’re ___.
Social security kicks in ___,
all of a sudden they back pay you all this money.
So I used to say that very often many people ___ take that 4 or 5 thousand dollars
and buy themselves a shot of their favorite drug
so much that they would wipe themselves out
and that actually happened with some people.

So then ___ computers ___ work for a little while ___ passed it onto my sister,
immediately ___ worked around most of the problems
and I couldn’t do __ I wanted to do on it anyway ___ pushing it to its total limit.
But I had to help the ___ Creek nature center
to apply first for an LCN, which they didn’t get from Apple.
They also applied for the general grant
because they desperately needed some money to process a newsletter and stuff.
I echoed through there.

The guy that ran the place was just reeling—
his name won’t pop into my head right now
but it was the naturalist of this group.
I knew how to ___ of the computer is so they could use it,
particularly if I got ___ community to supply all the software.
I’d supply the hardware and the printer
and the other people would supply things like Pagemaker and Excel, Claris Works and so forth
so that they could use it, and so it went.
Ended up making me a lifetime member and so on.
So I just thought that was better than suicide.

*Uh huh, it’s a nice gesture, nice way to turn it around.

Better than suicide.
And then after a while I ended up getting Dr. Brasch up there who I dearly love.
___ unfortunate as some nurses __ they were all.

*Neurologists.

Neurologists are __ wonderful, truly wonderful.
I guess there were some doctors that originally came along as early in,
___ actually with neurologists and other physicians who were extremely caring
and extremely helpful for ___ and afterwards Marjorie had just ___ how wonderful those people were.
That they were so supportive and helpful, so ___ for people ___
and for others they’re true assholes, in the whole sense of the word asshole.
Even ___ I usually don’t use words like that ___
but I call the person  that I had there a true asshole.
And so life goes and goes and goes and goes, and the more ___.  So it’s some more pieces ___.

*That blanket keeps slipping down.

Well it’s OK.  I’ll just take it up a little bit.
The thing is, in view of what I talked, are there more questions?

### Bland Moves to Grass Valley

They send him to me in Grass Valley
and he didn’t make it until October that year.
He was supposed to come in July, right.
We rented the place in July and it took him till October
because only then could the Bekins people come in and pack him.
He set the date two different times and they cancelled him.
Finally the Bekins people went out there and looked at the situation
and realized it was way beyond him.
They said, “We’ll come in and pack you.  Don’t worry about it."
They came in and they packed everything, Brian.
Trash, dirty clothes, the whole ball of wax, all got packed and sent to Grass Valley.

*Well, they’re professionals.

He got up there in October.
It was probably just as well because in August of that year
is when they had the huge wild fire that came through Grass Valley
called the 49er fire.
It burned all around the outside of where we'd leased this place.

*Oh yeah, you told me about that.  That’s right.

So it was just as well that he didn’t get up there till October and all was calm again.

*But his life was starting to unravel.

Bland called me and says, “They got me all packed and the van just left
and it’s 5:00 at night.”
I said, “Bland, isn’t there anybody you can spend the night with?
Don’t try to come up here on top of that.”
“No, no, I want to come up there.”
He gets in the car and he’s driving to Grass Valley.
When he gets to Highway 49 he ends up in Plymouth
which is going the opposite way on 49 from Grass Valley.
He calls me from Plymouth and it must be midnight
and he says, “I think I turned the wrong way.
I’m in Plymouth.  Where is that?”
I said, “Just turn around and go back the other way and just keep going.”

He finally arrived at 2:00 in the morning, starved of course,
but fortunately I already had a bed made for him.
I had an extra twin bed and I put it where his bedroom was going to be.
It was all made up so he could go to bed.
I fixed the shower with towels and soap and everything for him.
We got him fed and he went and took a shower and then he crashed
and he slept all that next day.
The movers weren’t supposed to be there for another day after that.
But the movers came in that day and started unloading stuff.
He went out on the porch and he started to put his foot up on the edge
of the seat that went around the deck.
He started to really lose his balance.
I thought, “Oh there’s no doubt in my mind.”
He just sat there for the next 6 months and just stared out the window.

*Cuz he knew it too.

Yeah, he’d eat, he’d sleep, he’d tinker with the computer a little bit,
but mostly he just sat and stared out the window.
He kept saying it was burnout and I knew that it wasn’t.
I kept encouraging him while he still had medical insurance
to go get a physical and go down to Stanford Medical Center, whatever,
and get the works while he could still afford it.
No, no, no, no.  So it went.  It was tough, it was really tough.

He came in October of 88 and then in May of 1989,
or February of 1989 our mother finally passed away.  

*On his birthday.

In the same month, yeah.

*No, he said it was on his birthday, February 13.

It could have been, I don’t know.
I have it written down somewhere I think.
It was close, like maybe 4 days after his birthday.
I think she died on the 19th.
She went into the hospital the beginning of February for hip replacement surgery
for the same thing that I had,
which makes me wonder if she was born prematurely.
I have no idea.
But I know she’d had hip problems, I mean somewhat all of her life,
and I know that one of her legs was shorter than the other.
She used to build the heel up on one shoe,
and it was the right side, the same side that my hip was bad.
She went in to hip replacement surgery,
and supposedly the surgery was successful.
She started to come out of it
and then she developed a blood clot in her leg.
They went in and operated on that
and then she went into shock
and she never came out of it.
That was in February.

In May of that year I went for a mammogram
and was diagnosed with beginning breast cancer in my left breast
and after some back and forth and whatever
went through a mastectomy in June of 89.
When I came out of the anesthetic it was really funny,
this voice said to me, “Carmen why don’t you go back to school?”
I guess part of me said, “Yeah, maybe if I can go back to school
and get a profession ___ and make enough money
that even though Bland’s health is failing,
I can make up the difference and make a quality of life for us both.”
That was my dream.
At first I ignored it.
I tried to go back to work 2 weeks after surgery.
That lasted for about 4 days
and then I got an infection in one of my drains
and was flat on my back for a while.
The doctor said, “No work for 6 weeks.”
I started doing a lot of reading then.
I read You Can Heal Your Life by Louise Hayes
and Bernie Siegel’s book Love, Miracles, and Medicine,
and thinking, “Man, I wish I’d read these books
before I went through surgery and not after.”

Poor Bland, he just fell apart.
If it hadn’t been for my friends in Grass Valley
I would have been in a world of hurt.
The trauma of the whole thing was just almost more than he could take.
One day when I realized I had the infection,
I needed to get to the doctor in a hurry.
He said, “How soon can you get down here?”
All I had was Bland to drive me.
They didn’t want me to drive,
but they wanted me down there in the next half an hour.
It took 3 hours before I got down there
because Bland had to eat his breakfast
and brush his teeth and take his vitamins.
Spontaneity was something that was totally gone by that time, big time.

We got through that.
When I was recovering from this whole thing I thought maybe going to school is a real option.
He and I drove up to Chico and talked to the re-entry concert Chico State.
He said, “Oh yeah, lots of people come back to school at your age.”
He didn’t tell me what the quality was on the other side.
That was fine.
We still had Graphon half-time salary,
and I figured that the living expenses in Chico
were even less expensive than in the Grass Valley area
with a student type situation.
But I was too late to get into Chico State that semester,
so he said, “Go out to Butte.
They’re registering right now.
Go out to the Community College and register down there
and start getting some of your GE out of the way
that you need to take.”

*Oh, that’s just down the hill here.

Yeah, you see the turnoff off of 70.
We went and registered there and started house hunting.

Those were the last few times I ever drove with Bland, letting him drive.
His driving was getting to the point where it was still reasonable
but I did not feel comfortable with it.
I think one of the last times I let him drive
and I sat in the passenger seat
was When we came up to pay the deposit
and get everything satisfied and sign the lease and everything.
We found this place to lease in Northern Chico,
a cute HUD house that was 3-bedroom, 2-bath, too.
We used the third bedroom for the computer room.
That was the last time that I ever rode with him.
I just decided if we go anywhere, I’ll do the driving.
If he still wants to drive, that’s OK.
I’ll just pray a lot.
While we were there in Chico,
he went back to the Bay Area I think just once driving
and then he realized it was too much for him.

*Yeah, it’s a long trip.

Another time they wanted him to come down there
and they flew him.
They flew him out of Chico to Sacramento
from Sacramento to San Jose.
That’s when Graphon was still hanging on by the skin of its teeth.
Early in 1992 when Graphon failed,
like in January of 1991,
they called him and said that they were going to have to lay him off.
We went on his unemployment insurance,
or the things when you’re unemployed.
He really did try to go out there and look for a job.
He really did.
He’d go down there and he’d research it with the computer and whatever,
and there wasn’t anything.
That was just when things started to really flatten out again for electronics.
I kept thinking, “I don’t know what he can still do in that head of his?”
I don’t know what goes on behind,
because he always lived so much in his head.
I don’t know what he’s capable of.
I know what’s going wrong
but I don’t know how much intellect there still is there,
I mean how much he can still do.
So I just sort of let it go
and I kept going to school.
His unemployment ran out.
I said, “OK, Bland,
I think it’s time for you to really have a physical
and find out what’s going on
because I said I think you’re eligible for disability.”
This would have been in January of 1992.

I had been going to a medical doctor in Chico
and I asked him if he’d see Bland and refer him.
He said no problem.
We got him in for just a regular physical
and afterwards I talked to Dr. Westcott.
He said, “Yeah, there’s no doubt in my mind,
but we’ll send him to the neurology specialist.”
Dr. Forner was about as pleasant as that wall.
I mean talk about a person who is in a profession that should be caring.
In order to make up for it has become incredibly,
in my estimation, callused.
We went to see Dr. Forner—this would have been like in February-March of 92—
and he saw Bland for a few minutes.
He asked me to come in the office.
We sat there and he told Bland there was no doubt in his mind
that he had Huntington’s Chorea.
Bland just broke down and started crying, weeping.
It was a very traumatic experience.

From there it was starting to fill out all the forms,
the forms that we had used up everything financially.
He had nothing in savings any more.
Graphon stock was essentially worthless,
so we could apply for Medical,
and could start in on Social Security,
putting that in place,
putting his state disability in place.
I did all of the forms for him,
and did all of the leg work.
I had started back to school that semester
and finally in March I just realized,
“Hey, there’s no way I can do this.
There’s just no way.”
I went to my __ the people you have to see to drop out of school.
I said, “Look, this is what’s happening.”
He said, “Hey, you’ve got more than good reason to drop out of school.”
You just get withdrawals when you do that,
cuz it was within the time frame when I could still withdraw without any penalty.
By that time I was at Chico State.
I took that whole semester off
and that summer off
and did nothing but Bland’s stuff,
put stuff in place and get stuff.

He basically did try to do some of his own cooking.
In fact all of it really.
I mean he ate very simple meals but he really did try to keep doing his cooking.
He walked to Safeway at least once every two weeks, sometimes once a week.
At that point, when he knew you were coming,
he asked Johnny and I to come over there and talk to him.
He said that the cooking had finally just gotten to be too much for him.
I knew it had,
and he said,
“Would you mind helping while Brian is here
and then maybe even afterwards cooking
and seeing how that goes?”

What I did then was, for the most part, to cook his main meal every day.  It’s gotten to the last 6 months that I do breakfast at least 5 days out of the 7.  We take him something over there for breakfast, and also I found out that even making coffee in the morning was just too time consuming for him so we ended up just taking his morning coffee to him, so he didn’t have to do that.  So cooking just.  So cooking and coffee making just totally dropped out of his life.  He tried to keep it going as long as he could but it just, too time-consuming, too, and also the computer came into his life about that time too.  Of course you know what all the background of that one was.  Good, bad, and indifferent.

*Yeah, right.  That part I know.

That’s about where my life story is now.
I guess my dreams for the future are to have him in some type of situation where he’s well taken care of,
but not necessarily an institutional life setting.
Dr. Brasch talks about skilled nursing for him
if it wasn’t for me.
I don’t think he’d survive 2 months in the skilled nursing situation.
He’d come unglued.

You know, they’d have to put him in a straight jacket, I really think.
I don’t know how it would ever come about,
but if for some reason he did have the wherewithal maybe to have his own place,

you know, a nice say 3-bedroom, 2-bath place,
and then have somebody that would live with him
who would assist him.

There are situations like that out there.
There are people like me that are incredibly honest,
incredibly good cooks,
that are maybe getting their nursing degree at Chico State or whatever,
that could come in and do it.
He wouldn’t have to have 24-hour care
but definitely night and help with showering
and help with dressing and stuff like that.
Part of what Bland loves is good cooking.
He was an excellent cook himself,
and he’s incredibly appreciative of the circumstances
that I’ve been able to help him in that respect,
and I, you know, until I got so depressed myself
I was glad to do it.
Now I’m feeling much better.
I guess to have some type of situation where he’s happy
and he can keep his stuff.
He doesn’t have to give it all up.
Even if he doesn’t use it, you know what I’m saying?

*Yeah, right.

It’s still his stuff, it’s just like that computer over there.
He may never use it very much but at least he’s got it.
He’s got.

*And he can think about it.

Right.
He’s got a beautiful telescope over there packed away.
I don’t know if he’ll ever use it,
but at least it’s his.
He’s got a beautiful stereo system.
I don’t know if he’ll ever listen to music again.
Part of why he doesn’t now is because he wants to use a sub-woofer
and that would, you know, drive his tenants crazy
and get him, what do you call it?
Lease breaker the last time you were here.

*Oh yeah.

So he’s never really used his music situation very much, at all here.
And I found that the music was kind of interesting.
He loves it but he doesn’t, doesn’t, the only music that he really tunes into is what he gets off of TV.
When we were living together and I would say hey Bland,

is it OK if I turn on for the stereo for a while,

and he’d say oh sure, no problem,

and he would thoroughly enjoy it.

But for him to go and turn on the stereo,

he just never did.

He’d watch television.

Television is his main thing to the outside world

and mainly he keeps it just on the weekends.

He finds that he sits down in front of the television set

and gets caught up in something

and before he knows it the whole day is gone.

He doesn’t like to do that.

He likes to still read his magazines and his periodicals.

The TV is his main recreation.

He does listen to some music programs.

He definitely watches his computer programs on the weekends,

to keep him up on what’s happening in the world there.

He came unglued a few weeks ago and almost had another seizure on me.

He got a Mac World magazine and the title of the thing

which was one of the last Mac Worlds he got

was “Apple Has Pulled the Plug”,

and in it was, I thought, kind of an interesting article

about how Apple pulled back all their licensing agreements.

For some reason that just struck him.

He was furious, he was just absolutely avid,

and he said, “I don’t want this magazine any more.

It’s too technical for me.

I want you to stop it.”

I said, “Hey, there’s no problem with that Bland.

I’ll just go over and tell them to stop your subscription

and send you a refund.”

I think it went into year 2002 or something.

So we got that stopped.

He said as much magazine in computer knowledge that he needs

is like on Popular Science level.

He can still do that and that’s fine

but the other one was really frustrating the devil out of him,

plus that article for some reason.

I mean I read it later.

*Now a year ago he seemed like he was absorbing it, a year and a half ago.

Yeah, it just got being very frustrating for him, so we stopped that subscription.
Bit by bit, piece by piece.
But he’s hung on ever so much longer than our father did.

### Daily Routine

*You were talking a bit over breakfast about the routine
and how the routine has evolved with Bland
and it might be nice to have that down on tape too.
I don’t know if that.

C:  Ok, I took a break this year
and put other people in place to caregive Bland for a while
because I just got myself into a very depressed state.
We put a lady in charge to do the bookkeeping,
write his checks and pay his bills and whatever
through the general AV Center
which is a center in, they’re funded some by Chico State,
that help seniors in different ways
and one of the ways is bill paying.

The mutual friend that Bland and I had,
my friend originally, Sharon Cohen,
who has done his housekeeping and laundry for the last 4 years
agreed to help him with meals.
From 93 until the beginning of 98,
when I decided to take a break for a while,
I had done meal preparation for Bland.
After that 3 months when I cycled back in,
I realized he was having temper tantrums.
He had a couple of them
where he just got so angry
he just threw stuff on the floor.

*This was in the early spring?

C:  Early spring, right.

*When you were moving all over the place.

C:  I was moving all over the place,
and I thought it had something to do with the Huntington’s.
So I asked Hilary, his former wife.
I said, “Do you remember Bland having any temper tantrums?”
She said, “Not that I can think of.
I said “This is something that is evolving.
I don’t know if it’s part of the illness or what.”

I dropped back into Bland’s life again
after taking a break
and realizing that things were not going well for him.
Just feeling innately that they weren’t going well
but not really knowing what was wrong.
I started first with the bill paying.
I found in the 3 months that I was gone
that what small savings he has accumulated
had totally been dispensed.
He didn’t have any savings left whatsoever.
Realizing if he’s ever going to build back up any savings,
I was going to have to do some volunteer work.
He could pay me a little bit
but not to the hours that needed to be put in place.

I proceeded with living, not in an apartment complex
but in another household,
and just sort of easing back in
to see if my own spirit could take the responsibility again.
It seemed to be going OK.
I first came back in and did the bill paying,
one month,
and realized that the financial situation
had just changed in 3 months time dramatically.
I got that part done,
and then I started in realizing
that the meal situation needed to be changed.

For him to fix a simple meal of cereal and yogurt
and fruit and fruit juice and milk
was taking him 3 or 4 hours to complete.
He wasn’t eating breakfast until like 4:00 in the afternoon.
He would get up, he would shave, he would shower,
and then fix himself some coffee.
Before I took a break, his coffee was being provided
and breakfast was being provided every day.
All he had to do was to heat it up.
At least on the weekends.
During the week he was doing this cereal, yogurt, fruit type thing.

In the spring time I got introduced in the Bay Area to Smoothies
which I knew nothing about.
Thought they were neat,
and talked to Bland and said,
“Why can’t we just take all this stuff
that you love to eat at breakfast time
and just dump it all in together?
You know, the cereal, the milk, the yogurt, fruit, frozen fruit,
the whole ball of wax, and flavorings.
You always mix a little jam in with it
or a little almond extract and vanilla extract
depending on what combination it was.”

I mean he had this incredible diet,
which I got sketched in my handwriting,
but I still need to type it on the computer,
all these recipes.
What I want to do is like make a book
and put the recipes in plastic
so that somebody could come in and do it for him
and just look at what needs to be done.

*Well why don’t you give it to somebody to type it up
and send me the bill?

C:  Oh, ok, thank you.  So anyway that’s what I plan to do
but I’ve got it all written down
plus we need to add to it.
He needs to look at it and edit some of it,
and add to some of the recipes I didn’t get.
I think I’ve got about 8 different Smoothies,
but I think there’s others that we could add
which we’re going to do.

So I said, “Come on, during the week,
let me come and make your coffee,
make your Smoothies.
Then I’ll come back at night
with something for you to eat in the evening
or I’ll come here and make it.
At  least you’ll have something to eat on,
but I’ll come and help you serve it and stuff.”
So we started on that routine in the early spring
and followed through the summer.

At the end of the summer I had a chance
to move back into the apartment complex
where I had been before with Bland
and decided that was the most reasonable thing to do.

A lot of my time was just being chewed up
in transportation going back and forth twice a day,
and energy.
So I got back here and realized
that Bland needed some corrective surgery.
He needed to have a hernia fixed.
He also had fluid in the scrotum area on the other side.

*From his vasectomy?

C:  From his vasectomy that had probably been collecting
for the last 20 years.

*Now he had that vasectomy in the 70s, didn’t he?

C:  Yeah.

*I can’t remember exactly when but it was like 76 or something like that.

C:  Yeah, so it was definitely 20 years.

*Or 75 or 4 or somewhere in there.

C: We got some really good surgeons lined up, both a urologist and a general surgeon for the hernia.  He went through surgery on October 20.  The surgery was a fantastic success.  He went in as an outpatient.  But they gave him general anesthesia because of the fact that the involuntary motion couldn’t be stopped unless he was in deep sleep.  We got him into the hospital at 5:30 in the morning when you know he hadn’t had anything to eat since the night before and I actually picked him up at 1:00 in the afternoon.  It was just totally amazing, that part.

I would have come home and slept.  He didn’t.
He just kept going.  It was like he was on some kind of high.
It was just totally amazing.
But what came out of it was
we had to start giving him medications every 4 hours.
Medications with food.
He had been taking these long gaps.
His usual schedule was to go to bed at 11:00 or 12:00 at night
but then go clear to 4:00, well earlier than that.
He’d start his coffee probably about 1 or 2
and then be eating his breakfast at 4.
We had to just totally turn his schedule upside down.

Number one, you can’t take showers for a while anyway.
We just cut the showers out.
Cut the shaving out.
So he actually went unshaved one time for 3 days.
It was just totally amazing.
Because he had been an extremely fastidious, clean, neat person.
I mean that means a great deal to him, to be clean.
That was quite an experience too for him.

What came out of it was we decided to do the coffee thing first thing in the morning
and to get him sitting down instead of standing up
and walking back and forth to the microwave to do his thing.
I helped with that.
He has to add chocolate to his coffee,
and then some sugar to his coffee,
and you’d have to heat them in between.
He drinks it down some,
and then finally add some milk to his coffee
and he drinks it down.
The whole procedure takes about 45 minutes or an hour,
even with me helping.

*Yeah, I noticed here this morning he had to get the coffee reheated 3 or 4 times.
40 seconds here, 50 seconds here, 40 seconds there.

C:  I’ve almost got it memorized now, Brian.
I mean it’s the old chemist coming through,
you know,
and everything has to be,
I have to measure stuff for him,
and then I finally gave up.
I said ok, you put the chocolate in the coffee
cuz you know exactly how much you want.
I’m not going to do that any more.
I tried to do it for a couple of days
and I thought forget this.
Let him do that part.

Five days a week we do the Smoothies.

*Yeah, I noticed here this morning he had to get the coffee reheated 3 or 4 times.
40 seconds here, 50 seconds here, 40 seconds there.

C:  I’ve almost got it memorized now, Brian.
I mean it’s the old chemist coming through,
you know,
and everything has to be,
I have to measure stuff for him,
and then I finally gave up.
I said ok, you put the chocolate in the coffee
cuz you know exactly how much you want.
I’m not going to do that any more.
I tried to do it for a couple of days
and I thought forget this.
Let him do that part.

Five days a week we do the Smoothies.
The way that works out is
he has a Smoothie after his coffee,
and we save the other Smoothie for 2:00 in the afternoon.
I come back in the evening
and help him heat up his dinner.
We have a special way of heating it,
a really thick glass bowl on a plate in the microwave
so the heat stays in the food longer.
Part of what happens is
that he eats so slowly
that the food cools off
before he can get all the way through it.
So we’ve learned different ways of doing with that.

I serve him ice cream and some low fat, nonfat cookies
like graham crackers or vanilla wafers or whatever
that he has later in the evening by himself.
At least it’s already served.
All he has to do is get it out of the freezer.
He takes his evening meds with that,
when he was on medication.
Now he’s totally phased off medication.
He’s down to one pain pill at night to go to sleep on.
That’s it.

*Yeah, I know he doesn’t like to take medications.

C:  No.  Fortunately what they gave him for pain
was a generic Vicodin and he only would take one at a time.
He never did take two
which boy, after my hip replacement surgery,
for a while I was taking 2 every 4 hours.

*I remember.  You were hurting.

C:  So, but he managed to just take one at any given time
and he’s just slowly cycled off it.
We’re down to a month now it’s only one a day.
Basically what we’ve got him doing now is eating 4 times a day.
What that has done for him is to really decrease the anxiety.
He would have these anxiety attacks
of which he takes a little bit of Valium for,
half a 2 mg tablet.
This will knock down anxiety and let him sleep.
I thought innately that if he would eat a little bit each,
every so many hours,
that it would help his blood chemistry enough
that it would improve things.
I never even thought about the anxiety part of it being improved but it did.
During this time I contacted the social worker
for the Huntington’s Disease Society of Northern California.
His name is Alan Brill
and he was such a wonderful person.
He sent me some pamphlets on Huntington’s.
On feeding and whatever.
And it turned out that innately,
Bland and I put everything together
that we should have done.

*Great.

C:  With the Smoothies, with eating every 4 hours.
I realized that the part of where he is right now
is he has to stay extremely focused
on whatever he’s doing at any given time.
If he’s washing his hands, he’s got to stay totally intent on washing his hands.
If he’s eating, he has to stay totally intent on eating,
and anything background,
I mean you and I talking he’s managing to drown out.
But basically even music in the background
is confusing for him
because of the way the brain is functioning at this point.

*Yeah, I notice I have to be very careful about what I ask him
or it will send him off in another direction.

C:  Right.  So he has to stay very focused on what he is doing at any given time,
particularly walking.
He definitely doesn’t want a wheelchair
if he can possibly avoid it.
But he’s down to just the most tenacious little shuffle,
but he manages to do it,
with lots of involuntary movements thrown in.
I’ve watched.

*Visual checking too.

C:  Yeah, a lot of visual checking.
I watched him and when he gets the most motion going
is when he is stressed.
Going to the bank the other day,
and he was under stress.
Man, his little arms were just jerking all over the place.
I felt so sorry for him.
So if you can keep the stress level down,
if you can keep the situation quiet.
I think part of why he’s managed to live independently
as long as he has
is perhaps because he is by himself.
That way he can stay so completely focused
on what he’s doing at any given time.
Nobody is distracting him
from what he needs to do.
It’s still amazing that he can read his magazines
and periodicals
and get things out of them
and share them back with you.

*I learn something every time I come here.
I learn a lot every time I come here.
New ideas.

C:  So I mean that part of his brain is still working, amazingly.
Although he can still read,
it’s very slow and painstaking for him.
But he can still do it
and it’s a great joy to him.
Public television and so many programs they have on there
are a great joy to him.
He watches television maybe once or twice a week now, if that.
Mainly it’s just when he has some time
that isn’t with a daily task
that he has to do
of just the basics of dressing and feeding
and going to the bathroom
and taking a shower
and shaving
and brushing his teeth
and sleeping.
Reading is his main thing.

He says he does get lonely at times.
I think all the extra people being in his life
since surgery have probably been a blessing.
The home health people coming in and talking to him.
I think his speech has improved.
I think if he keeps using the speech,
it’s just like in walking
that there doesn’t seem to be a slur.

*Yeah, I noticed that too.
Between the last visit and this visit.
It’s better.

C:  Yeah, so I think it’s just use
and he really does need to use it more.
Well, I finally figured out
that he needs help with the shower.
I gave him a shower chair
from my hip replacement surgery.
What he was trying to do
was just use it to wash his feet and his legs with
and then standing the rest of the time,
which is not too wise.
So we put in a hose with a shower wand on it
so he could sit and shower much easier.

We’ve been figuring out new procedures there to just get it done
in a more practical, easier way.
Shaving he still manages to do pretty well with,
for himself, of course with an electric razor.
A really good Norelco or whatever it is, electric shaver.
We’ve got two of them
so if one goes down we’ve still got another one.
We keep rotating them.

His dentist was worried about him grinding his teeth.
I said, “I don’t know about that cuz you know I’m not around when he’s sleeping.”
Evidently he’s doing it in his sleep.
There was an article in the newest Newsletter,
my first that I’ve gotten.
Alan put me on the mailing list
for the Northern California Newsletter
which comes out 4 times a year.
It talks about Huntington’s patients grinding their teeth
and needing an appliance.
Another thing they were using
is some type of injection
similar to lockjaw
in order to keep the motion down
and keep the teeth grinding down.

He sees the dentist in December
and I’m going to tell him that I found out
that this is a side effect of Huntington’s.
Now that he’s got no share of cost
with this new thing we’ve put in place
with the in-home __,
it won’t cost him anything.
Have them put a piece in his mouth.
What happens is they grind their teeth down so much
that they lose them eventually.
So we want to have him keep his teeth if he can.
He’s always been very proud of taking expert care of them
all of his life.

*Oh, I know.

C:  And I had no idea this was a side effect
until I read about it in the newsletter.
I didn’t even think to ask Dr. Brasch.
I should have when the dentist asked about it.

*Well, he may not have known.

C:  That could have been too.
So anyway, just keep learning, learning, learning.
The more informed I am, the better it is I guess.
Although the off side of it is how sad it is
and how devastating it is to family.

*Yeah, I’m glad that you’ve got some support network in place here.
I think it’s got to help to have some more knowledge
just to be able to anticipate things.

C:  Right.

*I realize that what’s going on is not him being.
Neither one of you mad at each other,
but a natural progression.

C:  Back to the temper tantrums.
That finally got explained
after I got back into his life
and we did sit down and talk.
He just got absolutely infinitely frustrated
with the people that were trying to help him.

The lady who was trying to do his bookkeeping
unfortunately was a former clerical bookkeeper type person.
For me to keep his checkbook balanced
and write checks
and to keep track of where the money was going
was just, I mean there’s nothing to it.
Second hand to me.
I guess this poor lady did a very good job
and everything was in place
as far as that was concerned
except it was costing him money he couldn’t afford.
Every month when she would come to help him,
he would just have to start over with her from scratch
about what needed to be done.
He just ended up being really frustrated with that.

Sharon, who has been his housekeeper
and done his laundry for the last 4 years,
does not like to cook.
Never has liked to cook.
Bland was trying to teach her
how to put casseroles together
that he could eat on for several days
so that he could just serve out of them and eat.
It was taking a lot of energy and a lot of time
in order to teach her how to do these things.

*And she didn’t want to learn.

C:  And it wasn’t really what she wanted to do anyway.
So that’s where temper tantrums were coming.
And then his meticulousness, you know.
And she wasn’t quite as meticulous as I am.
So that’s where that is.

(cooking for Bland – discussion of food that I didn’t transcribe)

C:  Ok, are we on?

*Yeah, we’re on.

C:  The other thing that I wanted to comment about schedules now.
We’ve had to add showers in since surgery, help with showers.
I realized that he was trying to stand way too much.
I worked in a care home for 2 years,
working with people who were developmentally disabled
in one way or another.
One of them actually had a motion problem like Bland
but it was from different circumstances.
I realized that sitting down, taking a shower, is so much easier.
And someone soaping up your wash cloth
and handing it to you is so much easier.
You can still be independent and taking a shower,
but just small things like that
make the biggest difference in time, quality, whatever.
That’s where we are.

What was happening for a while there,
for 3 weeks, Medicare would pay for in-home services,
people coming in.
Aides would come in and help him shower
in the middle of the day
because that was their schedule.
When that was no longer available,
I was having to help.
I was still coming in the middle of the day.
It finally dawned on me about 3 or 4 days ago,
“Why don’t I just link this
into one end of the day or the other
so I don’t have to break up my day another piece?”
We decided that at night was the easiest for him.
Now what I do is I come over about an hour and a half before 6
and help him get through his shower.
That just feeds into dinner.
So that’s been an interesting experience too,
but it was beneficial.

Sharon’s going to be helping.
I want to teach her how to do some of this stuff.
I’m going to point out to her
that that makes much more sense
when we’re only coming twice a day
instead of three times a day.
The other thing that we really need to put in
is Life Line for him
which costs $30 a month.
Later on, I guess the Janet Levy Center
will pick that up
through another program for seniors.
He’s on a waiting list right now.
This is where they put either a bracelet or something around his neck
that he can push
when nobody is here
if he gets down and he can’t get up.
It will page me first, and Sharon first,
and we’ll check on him.
If neither of us are available,
then the hospital kicks in.
Both the social workers,
both the one through Medicare
and the one through the county
have pointed out
that this is a really valuable thing to do
at this point.

*Well maybe someone over there can help you get started on that.

C:  Yeah, that’s a good idea.  I think we will.
I don’t know, if I share with you,
Jim and Maxine sent him an ice cream check too.
Bless their hearts.
So we put that into his account
after we get all the information for the county.

*So Sharon is over here a couple hours a day.

C:  She’s going to be, but not yet.
She’s just been so good at keeping the house in order.
Yesterday was her last day with her 24-hour a day care
so she desperately needs the hours and the money.
That job is no longer available,
but the people are letting her stay on in the house
so she will be here in Paradise.
She won’t be trying to commute from Chico.

*That’s good.

C:  The reason she’s staying on in the house is there’s work
that needs to be done to make it saleable.

*They don’t want to leave it abandoned.
They’re trying to sell it.

C:  And the other thing is to see if Mary pulls through,
the lady who she’s been taking care of for all these months,
who had a stroke back in June by the way.
It is so thankful that I cycled back into Bland’s life
because there’s no way Sharon could have done it.
I mean no way.
So I mean it all happened for a reason,
however it was supposed to happen __.
So anyway, Sharon loves Bland dearly
and she’s certainly into helping him in any way she can.
But both of us know that we have to have some free time
so we just don’t totally burn out.
And she really found out with this 24-hour day job.

*That’s hard, that’s really hard.

C:  And if she left at all I mean to come
and help Bland and she didn’t have some other housekeeping jobs,
then she’d have to get somebody to come and stay with Mary
and all the hassle of that.
At least we’re not to that.

*Well it sounds like you’ve been figuring out the little things.
Although it’s been a lot of work,
you’ve been able to examine every aspect of Bland’s life.
Living with him at this time is probably extremely valuable.
Nobody else is going to take the same care
and have the same insight that you do.

C:  That’s it.
Like Hilary says, “Carmen one of your incredible gifts is organization.”
And it is.
So I can organize all this stuff
and lay stuff out.

The other thing I need to do
is get a wipe-off board.
You know, the kind of board you can write,
so I can write notes back and forth with whoever is here
and put a schedule up there.
The schedule and then notes
that need to go back and forth
and what needs to be done.

*Yeah, that’s a good idea.

C: So I’ll just use my good sense organization and get organized.

*Right, and delegate.

C:  Right, you’d better believe it.

*Hey, I’m learning about that.
That’s my big learning lesson this year is delegation.

C: I’ve got friends in northern California.
We’ve got a first cousin who lives in Oregon
who I’d love to see.
I’ve got to get some work done on my car.
I’ve got to get the brakes fixed
and the joints double-checked in front.
They replaced one and it sounds like it didn’t hold.
He said, “If it hasn’t totally disintegrated,
there’s a warranty on it.
That wouldn’t cost very much to fix it.”
But it’s just giving up, you know
having another __ and giving up my car
enough to go get it fixed.

With Johnny cycling in for a few days,
I’m going to be adamant that he help me with that.
Get it to the auto mechanic
and get the work done on it
so I’ve got a sound car.
I’m really looking forward to going
and visiting some friends
that I haven’t seen in a long time.
You know, just getting completely away for a few days.

*Right.  Good for you.  Good for you.  Well, it’s getting close.
Those dogs really do go at it, don’t they?

C:  Oh man, he was really fussing in the middle of the day.
Well anyway, I sure appreciate getting to know you Brian.
I appreciate your friendship so much.
It’s been so incredibly valued.
I just can’t say enough good things.

*Well, thanks.

C:  And Jim and Maxine, they’ve just been precious.

*Yeah, I’m really glad they’ve been keeping up
with the correspondence because I haven’t been real good with that.

C:  Maxine has just been an absolute gift.
It’s cute because when you get to the end of your life—
I always kidded about my mother at the end of her life.
The two main things that made her happy in her day
was a good bowel movement and getting the mail.

*Now you’re starting to understand that.

C:  So the mail is one of Bland’s highlights of every day.
Even if it’s junk mail, you go through and throw it in the trash.

*Yeah.  Oh, I like mail.  Well, anything more for this?

C:  No, I think that’s about it.

I guess Bland’s bliss has just sort of narrowed down to reading
and communicating with people.
I’ve been proud of him because he’s had all these new people
dumped into his life he didn’t know at all,
with home care people.
Yet he’s been totally open to it.
Of course, he has to train everybody when they come in.

*Oh yes, of course.

C:  But it’s been good for him, like I say I think it’s really brought his speech back.

The people have been incredibly empathetic and caring.
They really have, giving us new leads of where we might go
and what we might do.

The main thing is putting him into the system
in case anything happened to me.
People could say, “OK, we interviewed him here
at this point in time.
We know this and this and this about him.”

*Before you have to start over again with a new person, yeah.
That’s real important.
So it’s been about 2 hours for breakfast now.

C:  Yeah.  He doesn’t do that bad when it’s liquid
but you know he’d be done by now but you know he enjoys it so.

*Oh yeah, I’m just noticing.

C:  It’s just painstaking.

*If you want to get onto something else.
But if it’s the focus of your life.

C:  And get real appreciative of the small things that you do have,
to do your own thing, and get caught up in your own thing.
I think the other thing that’s just hit really hard
since this whole surgery, coming back into his life last spring
and everything, is to make me realize how full of gratitude
I am for the health that I have.
I mean the tasks that are so time-consuming for him
I mean, and again, so I give that piece of gratitude back
to the divine oneness on a daily basis
because it could be me.

*Yeah, that’s right.  The toss of the coin.

C:  Yeah.
And it’s really put me in touch with people with disabilities
and having so much more compassion and caring for them
and accepting people where they are and for what they are.
All the titles and all of the education and all of the training.
It doesn’t mean a darn thing when it comes down to getting
into a real disabled situation.
I mean it’s nice that you’ve been there and you’ve done that,
but so life goes, as Bland would say.

*And goes and goes and goes.

C:  And goes and goes, yes.

*Well I mean seeing Bland and my parents have been having challenges
for the last couple of years, and my sister.
Actually I have a friend back in Madison who has got MS
and is not doing well at all.
She has a little gocart to get around her house
from one room to the next.
It’s really hard for me to see her and really be around her.
It’s partially because she’s not open to the kind of medication approach
that my sister is on.
There is something I think could help her
and she doesn’t want to do that.
It’s not clear that it would help her.
It’s also just partially that my sister is doing pretty well
and she’s really struggling and it’s just hard to see that.

*It’s amazing to me how in the last 5 years how my perspective has changed
as I’ve gotten back in touch with Bland and met you
and have gotten more connected with my sister again,
as she’s had disability, and my parents.
Just realizing my own mortality with the divorce
and with two friends my age dying suddenly.
I’m really lucky that the main thing I’ve got
is that I’m nearsighted.

C:  And the other thing you have is that you’re at the height
of your energy and brain power and whatever, really.

*My energy isn’t quite as high as it used to be,
but it’s still up there, yeah.

C:  Just think of all the things that you’re accomplishing
and the gifts that are coming into your life with,
whether it comes __ or not,
just the fact that people have asked you to do such and such,
they are true owners.
That’s wonderful.
Yeah, I’d say probably the two hardest things for Bland right now.
One is walking and the other is swallowing.
When it comes right down to it,
those are the two hardest things he has to cope with.
And just coordinating things of course with all the involuntary motion.

When I first came back in to helping him,
there was a lot of broken glass on the floor
which seems to have stopped now
that he’s getting meals regularly.
The anxiety level has dropped,
and the anger has dissipated __.
He’d just be getting a glass of milk out of the refrigerator
ready to take it to the table or whatever
and bang.
There would be milk and broken glass all over everywhere.
Sometimes it would happen late at night
and so he would call me
and I would come in the next morning
and it was an absolute disaster.
That seems to have slowed down significantly
now that all these other things have happened in his life
which is good.

B:  I use lecithin as a supplement.

C:  A whole heaping tablespoon of it every day.
I also think that that has helped.
I really do.
I’m sure medical doctors would disagree,
but I really do think so.

B:  __ thing is in this too?

C:  Yeah, I think so.

B:  __ things like that.
All the basic is let me fill all my transmitters easily with __.

C:  Ok, I’ll see you later Brian.
I’m going to go back to my apartment for a while
so you guys can visit.
When you get done with that,
he will have to __.

*Ok, I’m just going to look at Popular Science
while he does his vitamins.

B:  I’m all together.

*Sounds good.  I think I’m all together too.

B:  For one thing, __ always cutting __ the damn things create disease,
cut through everything in the amount of time it takes me to do things.
When you and Carmen were talking, I had to stay out of that one totally.
__ eating at the same time, and trying to swallow things
or to chew and swallow food.
I just have to stay focused on that
or I begin to choke on the food.
It’s frustrating in how much it slows me down
in things that I do in life.
But on the other side, I have to be really careful __
both the times and other things that I can really do.
What can I say?  The problem is this damn disease.

*You do quite well.

B:  On the other side of it, if I don’t constantly practice coordinating things __
also movement things, or having to move and use coordination.
Those drop away too because constantly having __ in the midrange
constantly I have to rewire and that constant rewiring
means I have to concentrate.
It really is __ both coordination and movement and things like that.
Also cognition, memory, and things like that.
I have to practice both or I’ll lose them.
I have to very actively all the time do __ to keep stuff.
I find that the older the memories are, the more reliable they are.
The more recent they are, the less I can trust them.
What I did 10 minutes ago, I have to be careful,
because I have a hard time keeping track of what I’ve just been doing.
Everything is just backwards of what it usually is
for most people or whatever, on that one too.

*Although that happens as people age.
I mean that happens with older people sometimes
with other diseases or just aging.

B:  Yeah, anyway.

*My parents are going through that.

B:  So __ host of other things like that
where I have to adjust __ to keep things into some range
that I can actually do them.
So I think that’s the very general thing,
just everything __ everything I did do, still.  Still.
