# Scientific Musings and Modeling {#scientific-musings}

## Scientific Musings

<div class="source-block">
Math

4: math

8. Math                math.1-17

        High School        math.1

        After HS        math.2

        Feller                math.2

        Integration and Curve Fitting        math.7

        Chang, Model Theory        math.11

        Mathematicians and Biologists        math.13

        Fractals        math.14

        Feller                math.15
</div>

I understand How to Lie with Statistics. I  lost a copy a number of months ago and never did replace it but I regarded that as a really neat book because it, because I had trouble with theories, types of statistical analyses and so forth, and not getting sucked in by it.


### Mathematical Biology

I tried to make sense, three-valued logic, multiple-valued logic, the same for, somehow you could factor in the variability of the objects in life systems, ecology. I was always echoing back into ecology. 

I was always tied into individual behavior because I felt that was key for everything, even insects. I read about one of the pioneers of behavior of animals and insects. I was into marking and so I followed them individually with what they were doing because I was always interested in technique. A good model depends totally on generating individual data behavior, which creates a kind of distribution function in survival and breeding and all that good stuff.

<div class="source-block">
MathBio

12. Mathematical Biology        mathbio.1-13

        Mathematical Biology        mathbio.1

        Nonlinearity and Modeling        mathbio.2

        Whitaker        mathbio.4

        Robert May et al.        mathbio.5

        Jerzy Neyman and Flour Beetles        mathbio.9

        Bellman: Theory vs. Computation        mathbio.12
</div>


Another thing that was going on at the time this work was done.  Everybody was an optimization freak.  You had to be optimizer, you had to optimize __.  It was a whole world that was supposed to be optimized.  There’s no way in hell that you __ simple thing like doing a macro optimization.  It put __ level __ wants to behave or go down the tubes and the thing become more extinct because __ long term strategy, and so on.  The point’s made.

+The point is, when Bland was doing this work, we were basically doing it in the heyday of the Robert May group.

*Mathematical biology.

+Mathematical biology.  The 40s was the first time that somebody tried to apply mathematical techniques to biology.  What was very interesting was that they didn’t try to take a look at the biology.  They took a look at the mathematics that they understood and then they forced the biology into the mold.

+OK, now we’re into the situation where we’re talking about a 5-pound box and 25 pounds of jello.  We’re trying to get the 25 pounds of jello into the 5-pound box.  Typical of what mathematicians and physicists do is you chop off the corners until you got the 5-pound box that you wanted.  Unfortunately we threw away all of the biology.

*Arms and legs go.

+We threw away the arms and legs, the eyeballs, the ears, all of that was gone.  We’re back down to a skinned ameba and we’re saying, “OK, now we understand the biology.”

*You had the guts left.

+Yeah, we had something like a beating heart not connected to anything and not being triggered by anything.  What finally happened, and what we realized pretty really on, was that if we were going to try to do what we wanted to do, we had to take a complete reversal of the ideas.

+We had to take a look at the biology.  They applied the appropriate mathematical techniques to it.  The problem was that the appropriate mathematical techniques didn’t exist.  There wer no techniques for handling small populations.  There was no technique for handling the population of more than one.  When we got two interacting systems, we were screwed.

*You could do some ___.

+Yeah, yeah.

*__ time series that were correlated, but that’s about it.

+Yeah, when creditor A at ___ B, the problem was over.  But that’s not a simple problem.  Well it is a simple problem.  It’s one single event.  So we spent a lot of time trying to solve that particular problem.  We tried to come up with a mathematical technique where applicable.

### Nonlinearity and Modeling

What I would like to talk about is the problem of linearity and nonlinearity.  Models and the reality in models and it’s good stuff.  Testing models and model design, things like that, because the problems seem to have not gone away.  They have not been __ by time.  The issues that were standing 20 years ago when we built our first set of models are still with us today.  The people that want to throw out their deterministic models and things like that, I want to throw a challenge to them.  I think I haven’t pulled a chemistry book but do you remember what, isn’t it femto-seconds, what is that?  An incredibly small thing that __ manage __ in certain optical systems, isn’t that right?

*That sounds right, yeah.

So they developed __ basis for prediction of systems that are optically based and experimentally based __ into that measure.  Why not give the people the abilities kind of __?  Let’s give them a full second.  Let’s give them a full second to __ experimental __ into the __.  What I want to know to the nearest second is the time that the red spot on Jupiter will disappear.  Ok?  I want to know to the nearest second.  I factored with the kind of resolution and the kind of resuscitation today experimental __ just is mind-bogglingly large.  I want them, before they give me any __ modeling and __, give me to the nearest second when the reddish spot on Jupiter is going to disappear.  Is that ok?  Is that a reasonable question?

*It’s a well-defined question.

So does that make one point at least.  Because one problem, there’s a quasi-__ that keeps resurfacing.  The last time I went to the library and I actually dug through, I found the people busily working on the concepts for competing risk structures.  The rate for the alpha beta things and the modeling of the deterministic models.

*The growth models?

Yeah, the growth model stuff.

*The r and K?

So that’s the other aspect that needs to be considered is not only, that was 20 years ago, but it’s true today in terms of what’s practical to do.  Whatever time it seems that if you try to throw in much real biology, or real evolutionary theory, or things where people or animals or plants evolve in a natural system, you end up with some incredibly heavily high structured __.

You sure won’t be able to solve it.  At least the techniques for __ and the modeling __ was in the paper from LBL. I mean the original one in Livermore lab was the original __ together with Forest Service and also Dave Wood.  At this point it seems to still be a viable approach.  It has the potential of creating buffer experiments on the one hand that used those models of that type to do some relations.  On the one hand you would be helping to design experiments that would be a better structured, more quantitative and better, by the use of the modeling __ and at the other end, you __ models as a predictive source of __.  Ok, that’s a big sweep of that stuff.

*Well, it seems like a lot of the modeling until very recently was looking at things between these nonlinear events you’re talking about.  So you assume that they’re far enough part that you can predictably model in the middle.  It seems that in the last—well in the last 5 years, less than 10 years—that people have been developing models—toy models—where they’re interested in the properties of the nonlinearity and in trying to get it to structure like what you’re talking about.  Structure the models, structure the nonlinearities, not trying to predict when the next tornado is going to be and where it’s going to hit, but trying to look at the pattern of tornadoes and what happens under different situations.

*So it seems like that kind of modeling is very much in its infancy.  People are doing weather modeling, trying to do very sophisticated things with it.  I guess what I see what you’re talking about is sort of looking at a much bigger scale.  Looking at a lot of different scales at the same time, all the way from what’s happening in a few seconds to what’s happening in an organism’s lifetime to what’s happening on an evolutionary scale.

Yeah.

*And how these are all tied together.  There may be some things that an organism does which don’t make sense in terms of its lifetime but might make sense when you look at it on an evolutionary scale.  When it has to deal with flooding and natural disasters, it had to respond to that in order for the species to be here today.  It had to have the ability to disperse or move quickly under adverse situations.

*The kind of sense I’ve had from reading and from thinking about how people think about models is that to think, `Oh well, we don’t have the data for that,’ or `You know that’s too complicated.  Let me look at something where I can do all the pieces.’  When they get to that point, they often are getting to linear models or a very simple type of nonlinearity.  That doesn’t seem to constrain your thinking.  I mean that’s more, well let’s look at what’s going on. Let’s look at what reality is, and then let’s think about what makes sense in terms of modeling reality.  Then we can step in that and see where can we collect data that is going to help us model reality, where we might choose to do that.  I mean it doesn’t make sense to try to model all of reality.

Watt tried to model first all the country and then when he failed that, he went out to model the California for his deterministic model for all of California.  Remember him doing that?

*Who is this?

Watt. He was one of the early deterministic modelers that was in the same group with Holling and Slobodkin, that’s another name.

*Ok, that one I know.

Slobodkin is another and so what happened is Watt looked at what Holling and Slobodkin were looking at and gee whiz, I will take these __ these model and deterministic models and model all of some county which I can’t remember which.  And then it was a disaster.  So what did he do?  He applied for a grant for all of California for his model.  You wouldn’t say that he, he didn’t have any trouble of ego.

*I don’t know this person’s work, so I’ll have to look that up.

I think, that’s just totally off the wall, ok?

*That’s probably right.

### Whitaker

Totally off the wall, but so there was also a time when everybody was jumping on the bandwagon and some people were doing really quite sophisticated both __ experiments like Slobodkin, and other people were __ biology like Holling.  He was more careful of biology, and there were other people that came along that really were very good biologists like Whitaker that just lived as best he could with normal distribution and so forth.  That’s all the guy gave him.

*I have an interesting story about Whitaker.  So this student from Vietnam that I mentioned earlier who is working on the Mekong Delta.  He is using a package for canonical correlation and one of the justifications in the package is that it allows you to get away from linearity, from linear relationships, and to look at unimodality.  Unimodality.  So this kind of a shape.  And thinking with linearity, you know if you’ve got a certain range, you can think of it as linear.  But if you look at his stack of counts, species counts, over the whole range it’s going to be low and then high and then low again.

*I was thinking this is very strange.  Where is this coming from? So I asked him to bring in the manual.  Well it turns out that there’s a paper of Whitaker’s from the 1950s.  He’s basically talking about species densities over an environmental gradient, and how you’re going to tend to have an area where the species can’t really live very well, you get low counts, and then there’s the ideal area and then it drops off again.  He used the normal distribution as a convenient approximation for this.  These people seem to have taken that idea and totally turned it inside out.  If you look at the math of what they’re doing, it’s totally linear, so they’re claiming it’s nonlinear but it’s totally linear and behind it they’re assuming normality.

That’s what I found in every paper that I actually fought through to the end.  People would always claim __ linearity, multidimensionality, heterogeneity.  Heterogeneity was a big paper that got thrown at me by the group __ Washington while we were applying for grants and stuff. You know I dug the paper out and there are, what are they called?  Without loss of generality?

*WLOG.

Thank you.  Without loss of generality.  After you thrash everything out, they would throw this thing where they threw it out all like having __ one dimension.  Of course it was horrendous math but ok, so none of the business people I ever thrashed it through __.  So it was __ if you were willing to dig.  __ so many times over I got very discouraged with that sort of thing.  I was burning up too much of my lifetime without meaning much.  Especially not getting any useful tools.

*And that’s fine in certain situations and over a certain range of conditions.  But it’s when you get to those nonlinear events that it breaks down.  You either need to make assumptions to get around that or else actually build that into your model.  It seems like there are some of those ideas that are coming out now in some of these Markov chain models.  There’s some models of individual behavior where people are actually tracking.

It’s ingrained, it’s basically a Markov chain that I basically throw out as a starting point and then from that __ history and evolutionary information going to keep true Markov properly.  Am I right on that one?

*You can’t have arbitrary information back into the past.

Right.  Yes, with living things, or __.

*Yeah, you can define your past as far back as you want but at some point it ends.

So, this modeling technique in another sense was a fix for Markov-Chains.  Not only __ dimension.

Robert May et al.

Critical mostly makes an experiment, the whole idea behind this can make a situation detestable.  That was my great fit, with a group of people based on the stuff that Robert May used to do.  I’ve yet to see an experiment that could work, or if it did, it was some gigantic artificial chemostat type of experiment where you have a huge population, a rapidly stirred beaker or sitting for a while and it seemed like any time you’d try to hang on, try to hang on to one of those for 10 years.  Try to hang onto your chemostat for 10 years.  Watch what happens.  You know a few people did.

*Right, in England, yeah.

They just want over the map because you have all sorts of weird stuff and awful type of genetic mutation and new strains and everything.  It was crazy.  So no matter how long you thought you could hang onto something like that, but the longer you hung onto that, there was no variation save.  There was supposed to be this __ failed totally.  I can’t, can you talk of a single exception to the contrary 20-30 years.

*I think people are starting now to look at some models but the stuff that went on in the 60s and 70s and even the early 80s.

I ___ enough time.

*Yeah, no.  It would often be based on things that weren’t measurable.  They made nice intuitive sense but then there was no way you could investigate modie.  Yeah, I don’t think there’s much out there, even at this point.

OK, so how do you call that science?  How do you call what Robert May did science?  I thought you were supposed to be able to develop some theory, from the theory a hypothesis, from the hypothesis a series of experiments, from those experiments data, from the data, analyze the data and have a clue on the original theory.  Show me where they’ve done it?  Anywhere.  Find where that group has closed the loop of what you normally would call science.  Anybody else would insist on something like that for science.  Why shouldn’t they be held to do that for science?

They even taught me that in the introductory course on general science in high school.  They pounded that into me a hundred times over.  What was it, 7th 8th grade general science course pounded this into your being along with everybody else because  it’s absolutely fundamental to doing science.  That’s yet to be seen so that’s the other side of some, and I would really like someone to show me the contrary somewhere and to the world if you’re ever going to publish the thing, as a challenge.

*I hear you.  It’s a very important point.  I know one wildlife ecologist who is doing what he calls individual modeling.  He’s trying to model individual behavior.  He’s a wildlife ecologist, he goes out, he puts tags on animals and has followed them.

Then I’d put him back in the same loop that we described, of complexity.

*Right.

And then how would he go from there to the next step?

*Well, I want to talk to him and he’s at Madison and I want to show him this stuff.  But he’s a wildlife ecologist.

Holling did really nice work and creative biology and he had a biological intuition. He had lots of really nice experiments and the problem, he was always so constrained by the fact that he felt that he had to come back into the same reality things like that, cuz he had no other tools to use as an alternative.  And we had some interesting discussions off to the side.  He very much wanted me to come back out.

I think I already mentioned the fact that he had new problems of trying to have a monitoring system and it was killing his computer in terms of compute cycles. The thing he found most intriguing was the complete aside on that special method of getting away from calculating trigonometric functions for working out distances, say to trees or how would their animals and plants interact?  But also you know you could use his same kind of tables.

He started measuring individual animals daily and other things like that. In every case, if you moved to measurements on individual animals then you came right back to the things that we were describing in this paper, or that Jim was describing in his illustrations using different games.  All the images by Jim were just beautiful. I loved it. I really loved it, because Jim found himself right smack in the middle simulation on the one hand and then a bunch of numerological things.  He told me he had gotten into a whole new set of them.

It’s easy with Robert May’s stuff.  All I see are gotchas.  If you try to take it one step forward like Holling did . . . Important people in my life. The stuff he was doing I thought was really neat.  

I wanted to say something about how it’s hard not only at the deterministic level of Robert May and so forth.

*Yes, May and MacArthur.

May and MacArthur’s approach, but also the fact that I wanted to discuss something about the people that I thought did wonderful work.  

*I wanted to read you something here.  This was the Royal Statistical Society, their newsletter, it comes once a month, and there is a picture on the front of Sir Robert May, who is the, he is the science advisor, the key science advisor for the British government.  He gave a talk, he first gave some much needed advice on the role of statistics in science and society and then launched into a highly stimulating and enjoyable talk on nonlinear problems in ecology, evolution, and immunology.

Do you realize __ that we had with him in his __ students and so forth the time we were trying to do some nonlinear stuff?

*No.  Why don’t you tell me about that?

Wasn’t he one of the key people that was pushing for linear systems early on?  Early on.  Young person.  Early on.

*Could be.  You know, I know that he got into bifurcations which is a nonlinear system, but this is before that.

Yeah, before that.  And then when you start looking at systems that bifurcate __ there’s a simple system that I could write, the simplest system that involves say a couple of words, it just hasn’t, one has to __ squared, and here was this wild behavior.  That’s where you __ get religion.  A different kind.  So many of the people thought __ systems were against everything and it would provide adequate, there would be some transformation of the kind of modeling technique that would provide them a way of describing natural systems in a reasonable way.  That was really __ and then later on, pretty soon of, who’s the guy at Cal Berkeley?

*Oster?

Yeah, right.  He had intriguing ideas __ and he’s the one that passed the thing back to the other finding some wild behavior for the simplest fossil system they could bring up.  __ from a totally linear system and it, I still have that open question to you.  Is there any form, is it possible to form a __ that __ infinity and yet __ infinity of linear distance.  Is there any way you are creating the simplest nonlinear system like you just __ bifurcation type thing?  Ok?  Did you ever resolve that one?

*No.

I’ve run it by you a number of times.  Over the years.  Over the decades actually. __ that one worthy of a model theory prism __ small simple __ problems that are easy to pose, that are simple, not screwed up.  So why don’t you hit him with that one?

*It seemed that if it’s going to work, it would have to be a system where you have some system that’s not regular, where you’ve got something that’s getting vanishingly small or vanishingly close to an end point at some rate that leads to a pathological case.  I mean you can get degenerate systems but that’s not what you’re talking about.  You’re talking about truly nonlinear systems.

Yeah.

*I don’t know.

Why don’t you pass __ a friend, model stuff.  Didn’t you have a friend who was into model stuff?

*Yes.  Keisler.

You had a friend who was into model theory.  Why don’t you pass that one on to him?

*Good idea.

Pass it on to him.  It’s been __ for my entire life.  I haven’t been able to find a thing __ find a way to prove it otherwise either.  So give it to him __ keep it clean and neat and see what they say.  Anyway May __ back and forth each time if you just niche it a little further or went to a little higher value or things like that or __ whoa.  If __ find a way of __.  But does he ever get shifted in his points of view and realize __ biology reality.  But there was a lot of __ they really believe that the __ at least first approximation.  And __ we do even today is straight linear theory __.

*Well __ approximation if you don’t know anything?

Not only that but there are many things that have __ a statistician like __ and even __ that are not going to become stable and not part of the plant here.  It hasn’t been __ in place during their time.

*Right, or over a certain range of conditions.

Yeah.  However, if you want to throw something into the __ asteroid belt is in between Mars and Earth where the asteroid belt is, I’m sure you can find some there __ unstable __.  So which piece and part of the universe are you talking about?  And also what __ it’s mind boggling __ shot say to Mars are, almost no correction.  Or how they missed satellite that didn’t have a, the last part didn’t fire, put it into an orbit that was nonfunctional and I guess eventually that would burn up.  What did the people do?  They __ each time make a further correction in it and finally get it out orbitally by __ the correction of the moon __ into nothing.  __ pure linear theory, isn’t it?

*Yeah.

Pure linear theory, all that was done.  Built some incredibly clean and __ things like that and some things in correction for mistakes and other problems, you’re able to come back __ all linear theory __. __ you know __ linear approximation to occur like a linear theory, approximation type thing.

*Yeah, local linear approximation.

Whatever.  And you pretty much ignored the other third body thing out of that one too.

*That’s what I was thinking about.

__ that one, you could pretty much ignore it, can’t you?  For __ time over __ space.  Or __.

*It’s not solvable.

That’s what I mean.

*You can approximate it to whatever precision you want but you can’t get an exact __ three point problem.

So really I’m throwing a bunch of things like that.

*Interacting system.

Because they are constantly interacting __.

### Jerzy Neyman and Flour Beetles

You have to be talking about events being the total orientation and time as a dependent variable, and the next moment you’re telling about time with events coming in as a dependent variable.  Does that make sense?

*Yes, and then it’s really complicated if you try to model it in terms of time because then you’ve got all these interactions.  You have a whole bunch of stochastic processes that are going on at the same time and they’re all interacting and you got to model all that jointly.

And if you don’t do it jointly, you lose all the biological reality.

*Exactly.  And then you’re back to mathematical biology.

### Modelling / Neyman

You know it was interesting to go to, what was the incredibly neat statistician who pioneered a lot of use into biology.  He was up there at Berkeley too, in statistics, but.

*Neyman.

Neyman, Jerry Neyman.  I went to one of his lectures one time where he was showing how to model biological systems, stochastic models of a biological system.  So I was very intrigued because I was also looking into probabilistic models and here he was putting on a whole lecture just treating the whole issue of problems that came out.  And he was also doing a lot of pioneering work on calculating life data and things like that, statistics on life tables and stuff like that, kinds of thing from a sophisticated probabilistic point of view.  So I go there and right off he says well, the egg and the pupa are both inactive, they don’t move, so they’re stationary. Any the larva and the flower beetles.

*Yeah, it was flower beetles.

Flower beetles, wonderful.  You must know the example I’m talking about.

*I know the paper.

Well, incredibly small world.  So I went to this lecture.

*I took the course and we went through the paper.  I took the course from him so I know the work.  He had me come to the board and work stuff out.

And you couldn’t be in his class without going to the board.  He nailed everybody.  He was very careful about nailing everybody with some amount of time, up in the front.

*Right, Socratic method with a vengeance.

So anyway, here he is describing first the statistics he was gathering from the beetle.  It was an active form and the larva was an active form, OK.  They both moved around.  You had to deal with spatial movement and other things like, and pupa and eggs didn’t move out from under you so you’re going to have to deal with them moving around in the system, like wherever they got laid or whatever, they stayed there, they didn’t budge.

So the thing is, here he is working on flower beetle eggs and pupae that don’t move out from under you, they just lay and so on.  So then he goes on to fully develop the stochastic model, this single model will lump them together and since these two move (and its and larva) go on from there, to simplify the calculations and statistics in the two cases.  So that’s what he did for the, anyway the lecture that I went to, OK?  That was the lecture.  This is a wonderful statistics, just terribly sophisticated and neat, he’s just garbaged all the ethology in the system. Ethology just ate it because what he had done.

The eggs, may be stationary but they have a death rate, and all sorts of different predation can happen on them and that predation that will happen to them is totally different than what happens with the pupae.  There’s a group of hyper parasites that knock pupae out that are totally dependent on them.  They can’t live on eggs, the ones that take out eggs can’t live with pupae.  Exactly the same situation for larvae and adults.

And also the other thing was that it garbaged time in the model.  They’re very careful not to schedule any events.  It records the development time, which is very dependent on temperature and things like heat and humidity and things like that.  They hatch in circumstances that we can measure—that is all scheduling larvae.  Larvae then goes through a series of instars, growing, requiring certain periods of time to the next instar.

And they also have a behavior with parasites that are totally different from the egg.  Then you have to schedule time, the ones that survive.  You’ve got to schedule the formation of pupae, but the pupae though is exactly the thing I’ve just been describing, and so on.  The details of the adult can be laid out with the same ethological approach.

*Right.

So beetle statistics, but as far as I was concerned, it was garbaged over biology, especially the ethology of individuals.  Does this make sense to you?

*Yes it does, and it was beautiful statistics and beautiful mathematics and one of the things that he was able to do by ignoring some of the details you just went through, was he was able to use moment generating functions.

Linearity assumptions.

*Yeah, and collapse things down and come up with a nice way to look at multiple individuals using generating functions.  When you have independent events you can multiply probabilities which means in the moment generating functions you’re adding things, so it makes really nice mathematics. That was one problem I had with that material was that once you stepped away from those nice assumptions that he worked with, you couldn’t use that mathematics at all.  It broke down.  You’re stuck.

Am I right that this, in terms of stochastic modeling, is another gotcha that hopefully we’re working our way across?

*That’s right.  That’s exactly right.

The stochastic literature is riddled with what I’ve just described.  Am I right, does it appear at least at this point to you, you’ll have to cogitate it more I know, but it at least appears to solve it in a more reasonable and biological way and yet we haven’t eaten it mathematically, have we?

*No.  The mathematics in this, in some ways is really very simple in your approach, from event to event.  The complication is all in the relationship in the scheduling of the events and in figuring out how to simulate it, but the structures is elegant.  I’m biased of course.

That was another path I wanted to treat because I’ve been there a number of times in my life already.

### Modelling / Neyman

It was neat stuff, but it was nice that you had the same experience, we even walked through the thing, the paper on flower beetles, so I guess it puts a new dimension on the test for it, huh?

*Yes.

It’s coming to that again.  There are so many types ___ and everything comes all to pieces, busts it up.  But at least at the time you don’t see, do you find that also a problem to you that the particular mathematical convenience that Neyman used makes for great mathematics.  It makes for neat statistics, and it makes for some interesting applied problems where it’s better than nothing.  It had problems along the line I just described.

*Yeah, and it makes progress on a problem that wasn’t solvable before, but it’s kind of sad because you can’t, you can’t generalize it, you have to go to a totally different approach to generalize it.  I thought about that a lot and I couldn’t figure out how to generalize it in the time domain.  It’s just too complicated and you can’t use something like the approach he did.  It was kind of frustrating because he was in his late 70s probably when you talked to him. Let’s see he died in 81 and he was about 87 I think.

I also talked with him, you know, when was it?  Well the talk about the stuff we were doing 20 years ago.

*Yes, so that was probably 5 years earlier, so he was probably in his early 80s at that point, late 70s or early 80s, probably his early 80s.  Yeah, I worked for him a couple years.  I was his RA and his TA, yeah I was a TA in that course where he had the Socratic method.

Yeah, I thought he was a wonderful teacher.

*Oh yes.  One of the best teachers.  But it was frustrating because I couldn’t see how I could use his methods on the kind of problems that we encountered together or that I encountered working with you, or the kind of problems that I encountered with ecologists that I worked with. Looking at predator/prey systems or plant/insect interaction is actually more what I was working on.  I couldn’t see how to use that stuff and I still can’t see how to use it.

Because this is a way of describing why you can’t.

*Yeah, yeah, right.

This is the part where the order __ things to happen, this is the part when __ it was the only thing around with numerical __ at that time, the.

*Flour beetle.

Yeah, flour beetle it was called, and then __ put together active adults with active larvae __ because __ and the trouble is when you do that, you’ve just blown the __ everything has to take place and to evolve right.  In garbage everything in time.  So that’s the other point.  You can’t, you’ve got to, __ you’ve got to __ open-ended type of environment so real biology, you can actually happen.  And you’ve got to be able to tie to some kind of statistics that you can be formal about in some reasonable way also.  So that’s the idea of __.

Bellman (?) / Theory vs. Computation

They always caught it when the people are very famous and very talented.  Was it Bellman who was a numerical analyst at Bell Labs that was fantastically good at writing all sorts of very good programs and other things?  I think his name was Bellman.  Numerical analysis person at Bell Labs.

*I don’t know.

I’m really off the wall but he had just come out with a new book and it had some really neat techniques and some new proofs for some new mathematical.  He was a very innovative sort of person, some day I’ll get the right name and the right person.  I’ve garbaged his name.  But so what I was doing is I was sent to use one of the techniques that he had and it looked proofs, the proof looked great and I ran some numbers through it and it gave me garbage.

Then I forget the name.  He was the primary numerical analysis person there at Cal-Berkeley at the time we were doing this work, but I can’t think of his name.  So I went to his office and brought him the book and said do you see any problems with this particular proof?  I have a problem with it.  Can you find any problems with it?  So he sat down and rederived the stuff and said no, Bellman’s stuff here is right on, perfect, no problem.

The problem is that Bellman and I got in myself, all made the same slip on a kind of a mathematical kind of error that is easy to make and was wrong, and you only get garbage when you retry, put the real numbers into something.  So I said OK, you’ve just proved it by, why don’t you put a few numbers in it?  And he said, `I’ll be damned, I’ll be damned.  Well, you know, Bellman does this often.’  Bellman __ because he’d just been sucked in by the same one, you know, publicly there.  Real story.

So if you think the __ you had better be real careful of that being really filled with __ and it also has the other point.  It’s very much, it’s really crazy, the other aspect was that they’re always throwing around the stuff about mathematics is so exact and so precise and so all this good stuff, except they have, it takes real people to do real math.  Real people with limits.

*Make real mistakes, yeah.

So it’s a bit like you demanded a programmer go out there and write lines and lines of programming and never test it.  Never run it on a real machine.  How well would you __ formal, equally well defined, equally precise, equally.  Would you believe that that would work in __ or do we really prefer the guy actually __ debugging software and test programs?

*Yeah, it would be nice.

So that’s another whole piece of, another comment about because of the, and there’s always this, they’re always just discuss the __ for things that are __ approaching heter__ and yet when you find out that you __.  Sometimes everything is there but it’s an error, so be careful.  You should always __ be careful.

*Yeah, it’s hard to teach people that though.

You have to get burned a number of times to get it.

Papers

________________

13. Modeling Papers        papers.1-12

        Finding the Papers        papers.1

        Book Plan        papers.2

        Writing the Papers        papers.3

        Model Building Blocks        papers.7

        Missing Pieces        papers.8

        Jim Barbieri and Bob Luck        papers.11

        Miscellaneous        papers.12

Examples

14. Model Examples        examples.1-14

        Bark Beetles        examples.1

        Orange Scale        examples.4

        Neurons        examples.6

        Ecology        examples.9

        Weather Prediction        examples.13


### Bark Beetles

The person that did the modeling for the forest service was in Berkeley.  Berkeley was one of the first ones to get heavily computerized.  The fellow that was doing very sophisticated work on __ from a basis of linear programming model and that estimates the trees and tree growth and __ all that good stuff.  The linear models were for increment or growth per year and so on.

He used to call them prognostication models at the forest service there in Berkeley.  Do you remember his name?  I can’t remember it.  __ especially struck was his honesty about their limitation.  I think basically they were linear models that used all sorts of temperature and growth and standing formation to estimate how much timber wood would be harvested if you went in and harvested in any particular year.   It projects that model into the future.  The only problem was one of the areas where we went and did __ when we were doing this work was actually up here right in the Monterey Mt. Shasta.  It was the McCloud __ study, wasn’t it?

*Yes.

__ they had a wind throw __ a whole section of forest __.  There was a whole bunch of trees, part of it pine stands.  This wind burst had just knocked out pieces of wood flat on the ground.  It was quite something to see.  In that case, those things would crumble and it was __.  And of course then he would have to go out and __ the areas that actually they say was wind thrown to try to figure out what they might be able to harvest out of it.

He would then factor into his model what the result of that had been __ and partly by ground survey and a mixture of things like that to get the whole system back on track again.  By the time they’d gotten the information to effectively calculate out the very __ system of wind throw, they __ a growth model again until the next thing happened.  Might be fire, whatever.  So it was an ongoing problem.

They would have to bring themselves back to some reality of what the world was like again with a linear programming model in an extended form that incorporated a lot of the biology, the trees, and all that information about just general horticultural techniques and so forth.  They estimated some money and cost of harvesting __ thing.  That’s both what I see as a good model, a useful model, and one that __ had to be when there was some problem like __ running like that.  What’s the park that had that horrendous burning just a few years ago?

*Yellowstone?

Yeah, Yellowstone.  __ maybe go back and do some __ recalculation and that kind of a kick.  You see, then you would be faced with even a __ problem of how you make some predictions of that.  At that point you’d get some other kind of mixes of stuff coming back, and you would have a completely different competing system that was going to be establishing itself.  Part of it was supposed to be not managed, especially the part within the park itself.  They were supposed to let go and so it was natural.  That makes it even more of sort of an __ biology problem as to what was really going to happen.

It would take a lot of the __ truth kind of thing __ out what had been lost.  What indeed would be coming back would be another problem.  It would depend on basic biology knowledge to make much progress.  It seems to me that there’s sort of an open-ended kind of problem like that where the modeling that people have done over the years, __ hit by something that really knocks it down.  The systems very often in their own right have not only properties of their own.  It may be a tornado touching down or water spot in the ocean, perhaps.  Those are very structured things so they regard very special circumstances to happen.  But when they do, they result in incredible amounts of both human and other animals’ lives are changed and suffer.

The other issue was about this stuff you tie back to biology in any and every way that would make the real life biology more realistic in terms of animal behavior, in terms of evolution of plants and animals.  At one extreme __ scale, and in terms of physiological evolution or physiological systems think that the bark beetle uses this as __ attraction.  One of the resonant components then becomes part of the __ of the beetle __ to mass attack a tree.  You realize that also has to be evolved and programmed at a detail vastly __ that just didn’t happen by accident.  Can you imagine __ from accident __.  So also you have to have __ biochemical physiology and physiology scale.  Behavior scale and the medium, evolutionary scale under geochemical __ and __ other extreme for millions or hundreds of millions or even billions of years.

Somehow this model has to deal realistically with all 3 time scales, the scale that is basically __. It is also __ has no reversible processes like for __ and physics.  By the time __ even a simple __ is reversible and any finite number of __ by ten.

*So you said 3 time scales.  What did you mean by that?

Biochemical time scales for physiological and biochemical __, behavioral time scales for the evolution of animal and plant behavior and now they’re finally on a __.  It just runs __ but that doesn’t mean the plants don’t do real elaborate kinds of attraction __ chemical warfare in nature and all those good things.  __ about chemical warfare __ what is the __ in the desert.  __ kills any of the plants that come near it, dead.  It’s even an air attack as well as a ground attack.  So __ poison gases long before people did.  So this is the kind of behavior that I mean, just we factor in a realistic __ by real biologists.

Then the geochemical and geophysical type of system, man is that one ever full of a lot of __.  How do you like __ most of it’s disappearing down there in the Yucatan Peninsula but you can still see a little piece of the fragment and now you know right where to look for little pieces of __.  Boy did the __ ever get zapped by that one.  Now after watching the same kind of event happen up on Jupiter, people __.  So that’s another whole issue because it’s both the __growth and upthrusting and then winding it down.  Somehow animals and plants, individual species, have __.  Somehow you’ve got to factor in the appropriate kind of geological information from the __ geologist or a physiologist with somebody __ plants __ that deals with __ reproduction in the desert area or __.

How often is that thousand-year flood that redistributes the seed into new areas?  __ flood, not the ten-year flood, the thousand-year flood.  When I saw the __ you can’t believe what that __ or dispersal thing must be for that.  Every __ there’s one of those __ that just sits __ systems.  Every so often, they call them stalled out.  Now they’re recruiting those things and people are getting zapped by them.  So that’s the kind of thing I mean.  Even those things aren’t nearly __ people __.

*Yeah, and even if it’s on a thousand-year basis, if you’re talking 50,000,000 years, that’s 50,000 events.

Yeah.  Same scale as we were talking about on the other things.  So __ those 50,000 events, so finding the range where lots of __ so small you can’t study it.  That’s what I mean.

*But, so now I’m thinking about your cascade of models.

That’s what that was supposed to represent.  That’s why that was in there.

*Yeah.  So at any particular span and resolution, you have to abstract from the other scales.  So you want.

You’re constant __ buildings.  You’re probably doing your physiological low level processing on the neural cells of an individual, not picking up all the molecules and going bing bing bing.   That level looks __ to behavior.  That’s the point to be made. Infinite __ of behavior.  Yet you have to do the accumulated thing.  That is where you need 3 __ compete with each other.  There is no way in hell that they can be simultaneously optimized.

*Right.  But you have to use information from one to study the other.

Exactly.  The more biological and the more realistic that is __ mathematical __ come to hate the __ doing math for the convenience for them __ create.

*Well, it’s the antipathy of evolution.

I’m very __ today because it’s been a long, hard life to this point, and I really would like to dump on some things like this pretty hard.

*Go for it.

Dump on them pretty hard.

*I’m listening.

The next thing that I did was I looked at all different ways of __, ok this is a whole new idea.

You see now in terms, say of a cylinder __ tree, yet __ are you all __ the gallery type to look __ subtrees __ and you have __ of the bark beetle __ the legs and the __.  If the tree has been shut down for __ with the fungus disease.  If it __ the tree __ the young and the old and everybody else goes away.  That’s __ another dynamic that has to be factored in and __ real biology.

### Orange Scale

+Bob Luck has a really good example that he’s been talking about wanting to work with scales, scales on oranges.  One orange is an entire biome.  You can basically do a lot of things on a single orange, which means that you can get a lot of replication off of that.

And lots of structure.

+Oh yeah.

___ you can’t ignore it to ___ biology.

*And of economic interest too, so.

+Yeah, oh yeah.  Ifact we’re talking millions of dollars a year in terms of  just loss.  It’s interesting because the scale on oranges don’t hurt oranges.  They just make them look ugly but the fact that they look ugly—

People won’t buy them.

+Yeah, I mean they end up being juice oranges.

*Or they ship them to the Midwest.

+Yeah, Wisconsin.  They’ll eat anything.  Sorry.

*It’s true though.

Another comment that probably, Bob Luck, is that right?

*Yeah.

__ other things on __ had __ the same pressure problem as Dave’s problem.  My guess __ developing his work __.

*Yeah.  Well, Jim Barbieri was going to talk to him.  I sent Bob some email but he hasn’t responded back yet.  When I see Jim, I’ll talk to him about Luck.  Jim wanted to do some modeling with Bob Luck to see if he could get back and do some modeling in __.  I don’t know if he’s made any progress on that but that would be good to check out.

But of all __ those kind of systems because you see now you __ tree will last many, many years, then you want to keep alive.  Easier __ manages to breed fruit and all that good stuff the next year.  You can’t go scrambling time or the same problem that he has.  It was the sort of thing where you can’t make his __ punch a bunch of things back into the system from __ point __.  Boy is this true of the bark beetles.  You can’t spend more than a few __ I think it turns out to be 2-3 __ per year of __ on the forest and not have the end results being less timber than you’d harvest under ideal conditions.

You can’t model __ very much after it anyway.  But boy is that not to say of a conventional annual crop where you can make, lay down several times within a single year perhaps and harvest it __ fiddle with it this way and that way.  No system __ conventional math __ conventional type of system.  I think that is __ conventional agriculture in a conventional field for your __ this thing across several times.  You can __ a huge percentage of __ several times a year and still come out ahead economic __ .  You can’t do to mature, you can’t be throwing, he isn’t burning much resources on an annual basis.

__ then the system needs what you’re going to __ and even the more valuable crops, say like oranges or citrus, like again is a __ in place to have all experiences incredibly __ the behavior that’s going on between both the plant and __ pollination that kind of stuff or once they produce fruit, that it has to be done and there are all sorts of things that can go wrong or go right for the __.  You also have to manage to keep that tree going from year after year to realize the value that you were to put in it.  It’s not one of these sort of __ so I’m saying __ structure __ bark beetle does.  So I think I need to clarify that too.

*Yeah, that’s a good point.  I hadn’t really thought about that.  As you were describing it, I was thinking about some of the changes that are going on with annual crops.  With genetic engineering, you start like putting in BT, a gene for a toxin.  It’s fine when you’re doing it in a small area, but when you start doing it in 100,000 acres, you start affecting the biology of the.

Surrounding area.

*Yeah.  You start having the pest start evolving.  The pests are always evolving, but they evolve so that they can eat this food.  That’s something that accumulates over years.

Just like ecology.

*Yeah.

Just like ecology.

*Right.  That’s exactly what the scientists are trying to tell the companies.  You have to pay attention to the ecology of these critters, to their life history, when you design the placement of these engineered crops.  If you don’t pay attention to that, then your engineered crop is only going to be good for a couple of years.  If you do pay attention to it, maybe you will get 10 or 15 years.  But ultimately—

You get clobbered anyway.

*Ultimately you’re going to get clobbered.  So even with annual crops, there is this feedback and you have to be careful how much you alter.  But it’s a different kind of altering than what you’re describing for trees.  You may still only be able to alter it so much when you’re talking about genetic engineering or some sort of biological control system.

### Neurons

The only alternative was building neural models without getting—you see I always interact with a little bit here, a little bit there—bang, bang, bang, bang—and at any one instant just a few crucial pieces and parts fall in place.  If you took this into a neural model, but instead of years or months or days you had it in milliseconds and microseconds and use the same technique in milliseconds and microseconds and micrometers, whatever.  I don’t see why it wouldn’t work.  Do you?

*No.  I felt that way 22 years ago, haven’t changed.

You noticed we already have all the scaling programs in there.

*Right.

The scanning parameters are tied to actual experiments, things you can actually measure in the real world.  This neuron, that neuron, neuron A, neuron B, they’re different.  They’re not average, you don’t treat neuron A neuron B as average.  They’re individual and they have their communication, which is very precise, it’s turned out you just don’t sort of vaguely talk with each other.  There’s an incredibly complex chemical message system to do this and so, and so, but that third parameter already handles that.  Rates on entry already set up rescheduling to bring it back to linearity, already there.  OK, am I crazy on them?

*You’re right on.

What about the parameterization problem?  Are those fine?  That pretty much rowed in?

*As far as I can tell.  I’ve got to look at them in more detail and really worry over them.  I can’t, I can’t find any problems so far.

No, but what I mean is they’re off, you haven’t hit any, you know, any big gotchas?

*No, no.

+After Bland went to Graphon and I retired to the mountains, I got interested in small populations.  The small populations that I got interested in were populations of neurons.  In other words, you have a group of neurons that perform a particular function, say like in the inner ear, cochlea, or in the retina.  It’s basically assimilating data but what is it doing?  It’s really projecting out the solution that it expects to see.  That’s what the retina does.  It literally, if you take Carver Mead’s explanation, it’s a great edge detector.  That’s what it does.  It detects edges and then it fills in the spaces later.  Well what are we looking at?  Well, we’re doing the exact same thing.  We’re projecting out a solution in a small population and we’re taking a look at those things that we think are critical to the problem.

Do you realize how well ___ statistics ___ you’re ___.

-Oh neuralness.

Neural ___.

+Yes I do know.

It’s crucial to that.

*Oh yeah, it’s built into the study.

+One of the things that is really amazing is that when you talk about the interactions of small populations of neural systems, just small neuron groups that perform a particular task, you find out that it has many of the properties that an individual has.  It’s hopelessly nonlinear.  Each neuron is doing its own particular thing.  It’s doing its thing based upon information that it has received in the past and where it received it.

+One of the most amazing things is that Shepherd has shown that there is a thing called a dendritic spine that sits just before the soma.  If it fires it shuts down the rest of the system so you’ve got this hopelessly nonlinear interaction going on in event space.  Yet when you go to model it, how do they model it?  Well, they model it by solving a set of differential equations.  That’s how they model it.  Guess what? That doesn’t work?

+I’m beginning to think that there’s a whole class of problems, not just population ethology.  This is a good term by the way.  It’s a population of individuals.  Those could be individual neurons.  They could be individual people.  They could be individual coyotes and rabbits.  They could be individual anything.  It’s a undefined population.

-But moving.

+Well, or functioning, interacting.

*Network.

+The network.

*Dynamical network.

### Ecology

What I’m talking about here is this sort of ongoing thing and a modeling effort of keeping some kind of reality where a linear model, or a regular growth model that wasn’t based on linear series, worked beautifully for a while.  Then all of a sudden it’s disrupted by something coming in and completely modifying the system.

*Are you talking largely about rare events?

Not necessarily.  For example, let’s say I was in a deep canyon.  I did a survey of deep canyon and then it became a part of a __out there in the university at large.  The thing that really struck me about the big canyon was when I got in there, in some of the narrowest parts of the canyon, there was a canyon polished at least 100 feet up the walls.  In some areas there might be more __ that’s a big flow of water that turns up a big canyon also drains a huge area of mountainous area.  Like a reason for it being so deep.

But it also meant that the __ canyon, if you’ve got some sort of a __ or rainfall in that region, then it really __ life and some things survived it and some things didn’t but many things have.  Say seeds and other dispersal things were like caught in what, apparently have a whole lot of __ widely dispersed in flood time.  It seems almost seeds depend on floods to be able to keep as normal kinds of distribution and the 100-year flood that may be needed to get into areas and it’s the 1000-year flood in the desert that redistributes plants into new habitats.  But 1000 years is not that long an amount of time in terms of geologic time.  Even evolutionary in terms of plants it is not all that much.

A 1000-year flood can make an engineer pretty miserable if he’s sitting down in L.A.  You hope that towards the age of the 100-year floods, not the 1000-year floods in L.A., particularly the way they’ve rearranged all the __ down there.  Nature is always happy to rearrange it back its own way.  It’s own self, usually on the scale of a 1000-year flood.

So in another sense, I don’t mean to __ at all.  In fact __ the plants seem to depend evolutionarily on the dispersal on real events, highly nonlinear events, to be able to maintain their access to all available habitat.  And meanwhile, they’re getting __ theory by __ predation, __ by disease and so on.  Take on some other like climate change that doesn’t swing back in a more favorable way but how __ theories __.

Depend on some past __.  Of course, one of the effects of dams is it totally interrupts those natural processes too.  I guess there are very few water systems in the world today that aren’t dammed.  There are a lot fewer now being dammed.  In China __ ends up going down through what was the last big green system, that goes down through Vietnam and Cambodia finally.

*Yeah, the Yangtse River.

That’s the one in China, isn’t it?

*Yeah, they’re damming that now.

Yeah, but they’ve dammed their own stuff for __.  No, I meant the one that runs between Cambodia and.

*The Mekong.

Thank you.  It’s finally being dammed.

*I have a Vietnamese student who is working on wetland ecology in the Mekong Delta.

About the only other fragment that’s still left intact is that internal lake that feeds out in the middle of Africa, and Lake Chad, is it?  Part of it.  Is that right?

*Yes.

__ it’s the one that also __ Timbuktu or places like that, way off in the middle of nowhere.  It was an __ there was one in every __.

*That’s probably Chad, yeah.  That’s in the middle.

That’s where I mean also the whole issue of plant and animal dispersal is a very nonlinear one and especially a nonlinear one you consider things like that.  __ it seems that if you feed a system back into itself, feedback, and then you feed any __ at all, you have a hard non-linearity you can’t transform out.  Is that correct?

*Right.

Is that so a hard non-linearity you can’t transform?

*Right.

__ of course you can pick such a narrow level.  There’s always some priority-ing.  This one will behave normally and won’t be weird, but then there’s always a __ delay in intensity that will just cause it to blow.  With any more than just feeding, with no other information, just feeding it back into itself.  Am I right on that one?  Is that being a non-linearity you can’t __?

*I believe so.

I appreciate, because it seems to me it’s as simple a case, you just couldn’t do anything about.  Now consider what living animal with an evolutionary background is having to do.  Talk about __, talk about structured __, talk about memory.  Whoa.  To be alive, to be alive.  To not have those kind of __ you’d be dead real quick.  So that’s the flip side.  I never could see another way.  The __ of including it in their real life __ without that kind of thing.

You had to include evolution and then when you consider it under itself, it had all of its own internal structures that had to be maintained and different levels.  It was a network of things that were, things were __ one to another.  All of we.  It was that way for __ into the nervous system.  It was really interesting that Jim then dug out and showed me stuff.  __ actively maintained so far from equilibrium system, the active feedback was incredible.  But I see no way of doing those __ system.  They have to be __ in a reasonable way.  Part of them, part of the time.

Maybe many pieces or parts can behave, some piece of the parts can be considered as a linear system.  Or a linear proximate or another scale to consider constant.  This thing didn’t change over time.  They __ time.  So sometimes __ a constant again.  But again I __ picking an appropriate time scale to reveal the things of biology and the kind of information that’s appropriate for what you’re looking at, or physical __ too for that matter.

You got a system that’s got to be 3D for the way the __ and it’s got to have a time parameter in there too to make sense.  It was an absolute __ you’ve got to consider 4 variables.  Three dimensions out of __ time and __ to the appropriate amounts of resolution on the thing.  Appropriate because if it’s too fine, everything will __ constant around you in time and if it’s too coarse then it will all vanish 10 times over without you concentrating on the interesting dynamics.  For dynamics always has to be considered in the setting that makes it deep dynamics.

Then the __ the chemostatics I meant was what people used to love to throw at was an example of something to be modeled and looked at where you would set a rapidly stirred system with some species of microorganisms in it.  Some kind of food source.  If it was a plant type thing, then some kind of __, and you stir it rapidly, you siphon it also and they’re siphoning randomly.  The siphon would __ how would a system, how would it evolve against that system, because siphoning supposedly a mechanical removal at random.  Distributed at random across the rapidly stirred population.  The large population you know tens of thousands __ was in a single experiment, rapidly stirred.

And yet when I go out in the real world, what I would find is the absolute extreme.  The animals had lots of structure.  Very often the microorganisms were even worse because look what happened, I’d go out to something like the bark beetle __ and there was a lot of good stuff in the articles so don’t think I __ because we were __ number of times and also the modeling stuff.  So they just talked at random as if it was there.

You got a bark beetle flying along. Needless to say, it has a state space and a piece of the environment that it’s occupying.  If you unwind __ pick a resolution on a time scale, they find __ the result you want.  Then you look at the state space __ transition over all possible random, all possible walks through the state space which is some, it’s some kind of some ridiculous, what is it?  It’s some end to the something power of a power of something saying all possible paths.

*It’s huge.  Astronomical.

If you were to make __ flow thing __ all possible paths, talk about a lot of zeroes.  And __ tied to biology.  If you know biology you can deal with them in a very intelligent way.

*They’re extremely low probability events.  

What?

*Are you talking about extremely low probability state space or states for nature?

Consider the microorganism, I haven’t looked it up again, but the one that that used to shut down the circulatory system of __.  I can’t recall it but I remember when I asked the biologist, they indicated it was a very specific species evolved just for that one purpose.  For that one beetle, for that one thing, that would be __ by that beetle to shut it down.

Guess what?  The bark beetle was sparsely dispersed, but here maybe in the __ of a bark beetle primarily, if you were a little piece of a bark beetle and here that’s being __ in a meaningful way.  Yet the microorganisms in the space actually would have to be a whole __ to resolve it in some meaningful way.

If you were looking on a scale of a microorganism, it would need a much finer space and a much __ time scale.  Microorganism by microorganism __ as individuals.  So you’re going to __ each microorganism __.  Do you realize how directed that one is?

It goes back into the tree where it may or may not survive depending on how much resistance the tree is able to bring up in terms of all your resin __ and things like that.  And in terms of __ to compete to kill the interruptedness on its way in and then another whole group within the tree itself.  Really in a way defend the tree by being part and prey, preying on the bark beetle.

Then you have the same thing established.  If you look at that, here would be the cylinder eventually of a piece of bark where it was the sickness of what living foreign tissue was very, very thin.  Say in a Ponderosa Pine.  What would it be?  That living tissue I guess a tenth of a millimeter, right?

*Wow, I didn’t know it was that small.

No, what I meant was the actual living tissue.  The living tissue.  Immediately surrounding __ associated support __ on either side of those cells and other ones that laid on __ ones that laid on bark in the other side direction.  You have this incredibly structured system occupied by this thing.  It’s a bunch of __ empty cylinder, a cone-shaped cylinder, radically thin scattered here and there through the forest.

Depending on the __ of a colonization of the tree, it would be __ at different rates and then after you say __ to the layer __ air pollution is going on so bad.  What __ become so thin the beetle can’t even establish itself, __ food.  In that case, you __ I guess those trees can end up even though they’re standing, they look alike sort of, but in __ effectively stopped growing.  If you measure octal rings __ it requires a microscope to even see because the growth is so much from the oxidant air pollution.

That would be the kind of __ coupling you would need to do to __.  Man, talk about a structure, if you think the bark beetle has a sparse system, a structured system, look at some of the microorganisms and their interaction with the environment distribution __.  It’s even more structured and more filled with zeroes and space.  If you look at the full state space, it was unoccupied.  Does that make sense?

*Yes.

No matter what system you look at.  You got tornadoes touching down in Florida like this weekend, and this normally doesn’t happen this time of the year.  That’s a very __ event.  __ to the degree you’d want to be able to model it.  You would like to be able to say something about the structure of the nonlinear parts of the system to the degree that you could describe what was going on, gather information.

### Weather Prediction

I really don’t feel even __ weather prediction and all that __ ever-increasing number of satellites up there and graphics and computer __.  Here is a thing __ tell me exactly what the __ generate.

*I saw a talk on that very subject about 2 months ago.  A fellow, he’s from Switzerland, and they were modeling the weather in Europe and he put up about 50 projections of the weather over the next 6 days of what the weather would be like 6 days from then.  They were based on slight perturbations and they were dramatically different.  Now 90% of them were fairly similar but there were some which were wildly different and you couldn’t tell which one was going to.

Which one, but you __ points in the system.

*Right, but the neat thing is they’re trying.  They’re now trying to build that into the forecasting, of actually, they have fast enough computers now that they can actually do that forecasting.

__ in real time.

*Yeah, do it in real time, fast enough so that they can actually use it.  I mean it doesn’t take them 6 days to do a 6-day forecast but it might take them a day and a half to do 50 of them.

That’s still better than one that would take a month or two months of calculations to do a few days __ of the system would be computational.  I can remember when the computer was that kind of speed and it __ they had that kind of quality.

### Computers, Speed and Modeling

I never programmed that stuff in COBOL __ although that was __.  Honeywell bought Synertech and I was employed by it, for real time control yet.  Interesting.  Honeywell even programmed a real time control because you see they’re very much into air __ and control is likely, __ COBOL.  All in COBOL.  So life goes.  But __ where you want them, no problem, and they insisted documentation of that too.

*Hard to do when you’re in the dynamic phase of development.

And everything was then __ for the fact that one thing, it just, __ point just never seemed very real because __ way when you __ often you __ where you take __ become twice as dense.  Has a very peculiar property that way __ great for kinds of continuous systems and deterministic __ but this system just, it just integers made sense. There were a couple of __ there were some machines __ followed 40 byte integer and __ because get a double precision 64 byte easily, it was always old chips.

Yet on 16 byte and incredibly bad __ spline there wasn’t enough precision to keep you going.  It didn’t give you enough precision to be able to model things in an adequate way.  __ limited number system but you only had 256 values that you could distinguish.  What is it 65,000 __, 16 byte __ too many other facts.  __ was 32 byte integer over different dimensions and any time that any, I think it was dimension got too troubled, made more sense to __ people to figure out how to split some other dimensions and just stay with 32 byte integer.

So also all these models were both conceived and then implemented at different times. It ended up being that the 32 byte integer was the ideal underpinning.  __ IBM thing __ what you need to do and __ but that was the basic building block __ effects, and that was overkill I felt in terms of 60, 40 byte or 64 byte.  So that would be in there too because of, that was another aspect of model optimization.

*Right.  You’re talking about actually running a model and having it have enough range of values for.

Being able to drop in, have a __ and have it run from link __ and being able to drop __ having where you drop in __. __ but you’re crazy we’re mapping time also.  Timing to an event space, event space back into time.  __ as many __ we could.  Looking at the middle event and of course __ we had a __ normal expansion.  Some of them were ridiculous, things like that, regardless of how big we got, so if you had a very small __ it got a little bit bigger __ Leftist trees or something like that, is that what it was?

*Yeah, that’s right.

Leftist tree?

*Triply linked Leftist trees.  Doubly linked or triply linked Leftist trees.

So __ Leftist trees is __ we just __ the numbers are for.

*I programmed that up.  Remember?  Yeah, triply linked.  About 25 years ago.

So how life changes, huh?  In some ways it hasn’t changed at all.

*I don’t know if I can do that now. Well I imagine I could but I’m not sure I’d want to.

You’d probably rather explain to someone else what was needed and how to do it.

*Exactly.

What was needed and how to do it.

*Yeah, what I want to do is be able to write about this and explain it so that someone else can figure out how to do it.

And there are always people, that whole thing in life, they’re trying to __ something.  Their whole __ gee I did this __ cycles where the best he could do it was 17.  I could do it in 12.  __ this huge thing where somebody rose a dissassembler for the 65__ assembly.  Somebody devised a very sort of a clean that used something like 12 or 15 cycles to do his thing.  So somebody else came in and knocked it down to about 9 and he just about shook whatever because he had __ disassembler for disassemble the 6502 code.  It was interesting how, they make awful things like that and other people.

There because it’s not my forte.

*Well and sometimes it really makes a difference.  I heard a talk a couple days ago about trying to reconstruct phylogenies, evolutionary phylogenies.  With this one approach where you reconstructed everything at every step, it would take half a year to do this.  With this other little trick that these people did.  Basically any calculation had only to be done once and so they basically would figure out a subtree and if that subtree came up again any time later on, they could reuse it again.  They cut down from half a year to 4 days.

___.

*Yeah, right.  Yeah, you can actually do it and make some changes, come back again.

But that’s really what was the start of this whole modeling thing was that __ that sort of thing.

*Well we were struggling with such slow technology at that point that we had to.

But even now.

*Even now it’s, yeah.

It makes sense.

*Yeah, because it’s an exponentially growing problem when you look at an interactive system, a living system.

So the more efficient it could be laid in there __ most level, the better.

*Yeah.

And there’s always somebody, and then once you get the basic framework up and running, and show what’s supposed to be done, then somebody go and greatly improve it from there.

*Well, I think about how many interconnections we have in our brains and I mean you’re talking about what, a trillion neutrons, neurons, and all.

And someone never calculate on a scale of at least 100 to 1, other ones that are even on the scale __.

*Yeah, and we’re not anywhere close to that in terms of computers.

Boy, is that ever true.

*Maybe we’ll get a lot closer, well we will get closer but it’s just mind boggling how much our brains do in that, how much processing goes on.  The idea of trying to do calculations on a computer, just the amount of calculations you’d have to do to try to model a complex system, even a simplified complex system. This guy was talking, there was a visitor and this guy works on DNA sequences so he’s a computer scientist and  what they’re doing is trying to put together overlapping sequences of DNA.

And where they really don’t, where the __ are and it’s broken apart kind of arbitrarily.  Is that correct?

*Right.  Yeah, except in this case they can have breaks but keep the ordering for a piece, so they might have a tenth of a chromosome intact with breaks and then they’ll have another piece over here which may overlap 30% with that and breaks.  So the old technology was that you broke it up and you didn’t know how the pieces went together.  But this newer technology, they can now keep at least some of them together and build up from there.

Boy, does that save you both in terms of computational problem and also in terms of experimentalling of what you programmed the damn computers today.

### Genomes

*Right.  And they’ve been able to reconstruct whole genomes in say a month for bacteria.  Work that took years before.

I understand that they did them for tuberculosis, genome for tuberculosis.

*Right, four megabytes.

Quite remarkable, huh?

*Yeah, it really is, and in another year and a half, they will have finished sequencing the first plant, Arabidopsis, which is about 150 megabytes or 120 megabytes.  Within 5 years we’ll have a human done.

And where do you go from there?  All sorts of things that have opened up, that you knew __ now you can do before or even think about doing __ can be arranged __ no __ had to play god before.  They’ve never had to play god.  I think the people are going to be facing after the human genome and most other genomes have been completely decoded, they’re going to find themselves facing __ playing god.  Which things make sense and what things don’t make sense or what things __ absolutely want to do.

*Yeah, and those aren’t black and white.

Boy, is that the truth.

*And what seems to make sense and what seems right and wrong today will be laughable 10 years from now.

That’s true.  But only just a few years to where that’s going to happen.

*Yes, it’s already.

Just a few years.

*Yeah, I mean some of the discussion is going on but it’s an academic discussion right now.  I mean there’s a place where it’s real is in terms of say whether someone should know for a test of some disease, but like prenatal testing, but that, as we stand now, there isn’t any for most diseases there isn’t anything you can do about it.  So you know that information, that doesn’t really help you, and that’s going to start changing.  It’s already changing for some diseases.

But also do you realize that this is going to open up say the genetic engineering plants and all those plant-animal combinations and diseases in animal plant combination, all blend together.  What do you call the blend? __ which is __, which is E. coli, and which is __ all spliced together in one glocky thing that runs and breeds and does its thing.  We’ll be facing that very soon.

*Right.  I mean we know that that kind of thing can be done.  They’re finding some genes that are highly conserved across all organisms, with a functionality.   Even the DNA sequences are highly conserved because they are so necessary for life, and then other things that aren’t as well conserved.

Are related.

*They’re highly related, yeah.

Because they have a common ancestor and a common history.  Common ancestor, common history.

*Yeah, and they’re finding that the parts that are related—as they’re getting a better handle say of the 3D structure of proteins—tend to be the pieces of a protein that stick out that are functional.  The stuff in the middle can change, can be quite different, totally unrelated.  But the functional pieces, the pieces that stick out and interact with other proteins and with other structures, those are highly conserved.

Now you’re talking about two __ structure of protein as well.

*Exactly.  And not only three-dimensional but four-dimensional.

Yeah __ in time.

*Yeah.

Over time.

*Yeah.  But one of the things that’s puzzling right now is that there are multiple copies.  There can be 20, 25, 30 copies.  I guess the __ is about 25 copies that are almost identical of the same gene in an organism.  In some cases they have been able to identify these.  In a plant you break down ATP to ADP and you release a phosphorous group and there’s energy released.  That’s the main energy source for plant cells.  The ATP-ase, the gene for that, there’s about a dozen copies, maybe 20, in this plant.  Some of them are activated in the roots, some of them are activated in the leaves, some of them are at a very early stage in development, some of them later in development.  They don’t really know why or how they’re turned on.

Off and on and off and on.

*Yeah, right, but they’re starting to get clues.  Starting to uncover this.  How the geographic position of those, how that might be important.

And I guess with things like Parkinson’s Disease __ comes from, I guess it’s __ Parkinson’s is the disease that causes __ missing functional, the production of one of the, what is it called?  The things that cause excitation for the rest of the brain, but now what they found was that part of patients __ a pattern or flickering a light.  They could do something where they were paralyzed by the disease.  Otherwise __ provide the right kind of flickering thing or movement thing.  __ their behavior is __.

They’re bringing in a whole lot of almost similar ways and then you have to be careful when you go in and grab one.  Hope they’re grabbing the one that’s appropriate for the situation you’re doing.  So the brain is having to go through __ of stuff almost related but not quite but also conserve __ and so some diseases end up showing up __ your things, that behavior, because the way it interacts with the __ of the brain.  I just throw that one out.

There’s so much __ it’s so open-ended, its complexity __ average was doing some of __ first time, you go in and __ what’s going on.  Some of this copying and some of the copying of other things may be a way of a very efficiently including information.  Gee, this is the information you got after root __ thing.  However, this is the piece you need to grasp if __ be a reasonable seed one to germinate.

You want to send a little root hair to the outside world, which may be different than the __ coordinates something they can germinate, germinate the seeds that will be viable.  But you have different from a leaf producing showing green using collective store energy from the sun.  So similar but different in these things.  So __ way of dealing how to decide who should run off things like this in a meaningful way because boy, the whole problem of, whole problem more for that __.

*They’re learning a lot with plants and with animals about the early development, about say root tip development or marrow stem development, about the sequence of genes that get turned on.  Not the why, but the how.  It’s pretty fascinating what people have been coming up with the last couple years about that.  Just being able to come up with mutants where they can turn off individual genes and then see how that manifests in terms of the developing flower.

*The guy at Caltech who is doing that.  He probably has about 20 genes now but when I heard him talk, he had about half a dozen genes that had to do with the development of a full flower.  He was able to turn some off and instead of sepals and petals and stamens, he would get two sets of stamens and no petals, or two sets of sepals and no petals.  Different combinations.  Figuring out the sort of program but that still leaves all sorts of questions about how that came about in the first place.

*I guess the thing that fascinated me with the discoveries that are happening is how much can be controlled by one gene.  We’re talking about a bunch of different genes that control different things or a bunch of copies of the gene. One regulatory gene can influence so many processes in a living system.

Not very __ system.

*No.

Not very long.

*Well the interesting thing from, one interesting thing from a mathematical perspective.  There’s this idea of epistasis which is that the two genes that are at different locations can interact.  When you have data say on some process, some measurable process.  If you have the genotype of both of those genes, information across the population, you can get at the interaction.  It’s the statistical interaction so you can measure whether there’s interaction or not.  Then interpret that as a biological epistasis.

*In some of these systems, what’s going on is really a very discrete event, a very nonlinear discrete event.  You have one gene cuts off a pathway and then this other gene, its product can never be used.  If both genes are operational, if you have alleles that are active in both genes, then you get proper flower, proper response to stress, or something like that.  But if one of them is cut out, then it can affect the other one because it’s blocking the pathway.

*This is back to a nonlinear interactive system from this linear model of statistical interaction.  So maybe there’s the connection.  If you don’t know what it is, you use a linear model with interaction.  And when you do know what it is, it’s a nonlinear compartmental model.

### Model Theory


15. Model Theory        theory.1-19

        Five Parameters        theory.2

        Birth and Death        theory.3

        Models Based on Measurements        theory.4

        Hilbert Spaces        theory.5

        Event-Driven Paradigm        theory.6

        Span and Resolution        theory.9

        Non-Homogeneous Poisson Process        theory.10

        Physics        theory.11

        Population Ethology        theory.12

        Modeling on a Budget        theory.14

        Building a Model        theory.14

        Running Model        theory.15

        Dave Baasch        theory.15

        Small World Networks        theory.16

        Follow Up        theory.19


+I look back on that, I look back at the time that I spent with Bland up at Berkeley, the times at Giannini, as probably being the most golden, the most productive that I’ve ever had.  Not so much because of the papers, but because of the ideas.  They were all new.  Everything was new, and in a sense we were sort of doomed to immediate failure because they were so new that they were for the most part reasonably unaccepted.  If we’d have been Robert May or if we’d have been you know somebody working ___ Voltaire, we would have probably ended up.

*It would have been published.

+Yeah, we would have published a thousand papers and, but we would have also not done the problem.

*A gotcha.  We were talking about gotchas the other day.  You get so far with a particular approach and realize that there’s some key assumptions which are untenable.

+Oh yeah.

*You can’t make the measurements, you got some assumption with independents where there isn’t any independents and.

+Well that was another thing that we agonized over a whole lot, again in this paper we talked about.  What you needed to get a Poisson distribution, you had to make assumptions that were biologically not what we really wanted to make.   But the alternative was no solution to ___, so we made assumptions about that.

Bill Hawking(?).

+Yeah.

Sometimes they’d ___ sometimes by mathematicians, sometimes by biologists, but mathematician and then ___ way of tightly ___ the two by doing in a time space and an event space where appropriate.  We could do formal math to the next event, the entire event came to a screeching halt.  Most of the systems untouched because most of the systems, we don’t have to do anything with it, it’s already been defined and prescheduled, right.  But the ___ the event came ___ to the reproduction.  No 1, 2, 3, or 5.  Just like a pregnant woman ___.

*7.

7, sometimes, if you take fertility drugs or something ___.

The point I wanted to make was that this general discussion of broad things like this and some of the things __ want to do interaction __ obviously __ some of the things __ because some of the stuff is probably less clear why certain things were done __.  Now there’s some fill and still __ mathematical which is unfortunate __ at least a little bit more into some of the first implementing __ too.  Because that could have been an interaction between a natural __ and the mathematical world and the world of __ assimilate on the computer in some reasonable way.

Five Parameters

There was that other piece of the work, where we were looking at a different way of parameterizing the space.  I think we had 5 parameters in that parameter space.  And they related to things like position and rates and all sorts of stuff like that.

Like gee, 5 parameters to characterize a multidimensional system.  Boy, are you even cutting it loose in hopes of making any sense, 5 loose parameters arbitrarily shoved into the way that they’re dealt with in the one non-stationery poison process.  So it would yield so you would think that, woah, how can that many loose things in there, just make any sense?  You can draw the universe with that amount of degrees of freedom.  But the whole idea was to pick parameters that were closely tied to biological meaning.  That was the idea.  Biological meaning in a behavioral sense of what was happening in the rail. 

You’ve got to talk about goals playing on those, and you’ve got certain numbers and events and other things.  This tree has got to be born sometime, and  it’s going to die some time and has some expected lifetime.  But you also have bark beetles and other organisms.  They live and die and so on.  These parameters have to then be a bridge to the natural biology a person measures anyway and failed in terms of natural things.  At least as I just reach back, that was the idea behind them.  Does that make sense?

*Yes it does.

And that has the big potential problem that I need to bring up.  Is it really there because all those degrees of freedom you have to build in the structure of the problem and the behavior of the animal.  Partly structure, partly location, partly temporal stuff, partly hy-age, partly getting born, partly dying.  Who, people, animals, they have to get born, they have to live some life they have to develop, they have to reproduce and reproducing they don’t stay around very long, and at some point they die and none lives forever either.  And so that’s the idea of having parameters that are tied to things like this.  Does that make sense?

*Yeah.

So the free parameters are not free at all.  They’re tied to the biology a person measures in their natural experiment hopefully.

Birth and Death

You see, I remember the process and the things that let you set birth and death, life span, scales of time, scales of space, and things like that.  Now usually a reproduction of that then would schedule some kind of sub-event because for most higher animal’s reproduction is just a little bit more complicated than simple cell division so you have to, you need a compiling procedure at that point.  For example, it’s a scheduling of the reproduction based on the state of the system and the distributions that you measure and of course that’s a trial of Monte Carlo type simulation and then it, I lost my thread, damn.

*We were talking about, you were talking about birth process and the scheduling of birth process.

Oh, thank you.  Birth process then for most animals then you got to figure litter size, sex distribution, maybe even, maybe they’re all one, sometimes you get just one sex in a particular animal at any one time, all female or all males, or whatever.  And so that kind of information is crucial to factor in too.  But guess what, that biology is directly measurable.  This is appropriate to be factoring from ethology or animal behavior anyway.

The whole idea of keeping, treating what happened to plants as an exact analogy to the way that you treat the animal, you see.  They have a birth, a growth process, a reproduction process and eventual death.  No plants live forever it turns out, and so blue-green algae has a different lifespan than bristlecone pine.  And so what has to be developed are the equivalent  statistics but again, measurable.

You can measure them, like you get any other statistical data, and also then to tie you in some rigid way to what you were sampling from and you see that was the other thing that was driving them up the tree.  We had this big plot of Ponderosa Pine.  Here is this beetle interacting, now we’re going to stress it with air pollution, oxidant air pollution, with ozone damage, how do we model this damn plant?  We might measure how many trees and what kind of spacing, what they ate.  What, you can do aging by boring the tree and so.

And then you follow the actual death.  The tree is alive you load the smog levels, all statistical and then you couple them by the actual beetle biology.  You find that Dendroctonus doesn’t just get attracted to any tree and it does this only in a certain direction.  If it gets stuck in the phloem, it doesn’t even develop because the larva starve for lack of food.  At some point the oxidation of pollution probably makes some marks susceptible to beetle damage but at some later stage that it stalls it by starving the larvae for lack of phloem food data, the food, for the parents of larva.  The parents are there and then the larvae don’t develop apparently, I remember Dave saying.

Some of the sense that we’re describing here, quite measurable from biology, looking at it as an animal, like applying animal ethology to plants.  People who love plants will like that surely, the very thought that plants should behave more like people.  People even hug a few occasionally.  So, am I totally off the wall there?

*One thing you’re talking about is that you are looking at things at different scales, depending on what aspect you’re looking at.  If you’re looking at the bark beetles, you look at them on a scale of days and weeks and years.  If you’re looking at the pine tree, you’re going to be looking at a totally different scale, both in terms of space and time.  The resolution is totally different, and the span is totally different.

I think when things actually start in real time, ___ all parameters are there.

*Yeah, I think so.

Anyway, that’s what I had in mind anyway, 20 years ago.

Models Based on Measurements

+The other thing that we learned and this is something that Bland picked up on earlier is that you can build the best model in the world, OK, it doesn’t make any difference.  You can build the absolute best model in the world.  If you’ve collected the data wrong to drive the model, you’re dead meat.  You’re not going to go anywhere with that, and so from the get-go we were trying to design the database in such a way that it would derive the models that are in this book, in these articles.

+If we were to do it today I think we’d do it in a whole different way, because the tools would be so much different.  You have to remember back then, we were archiving data in these little cylinders, that they had this arm that would come out and go chunk, ___ the cylinder dah dah dah, kachunk.  You’d read the data in and then it would go kachunk dah dah dah, kachunk.  It was really beautiful.  Stupid but beautiful, you know, and archiving data.

*Slow by today’s standards.

+Yeah, archiving data was horrible, you know, where if we had, at that time that particular piece of equipment cost something like $50 million, just to archive data.  We’re not doing anything with it, we’re just going kachunk dah dah dah kachunk.  That’s all we were doing. Now we could buy a CD Rom Writer for $5,000, hook it up to a PC and we could archive the known universe, literally.  We never had that capability back then.  We were premature with That kind of modeling.  The way that we would do it now is probably very amenable to a network based system with appropriate databases in different locations.

You’re right.

Hilbert Spaces

+I should preface that.  We’ve never explored it and I think we’re probably 100 years ahead of time.  In that first paper where basically we’re taking a look at projecting out solutions to a biological system from some sort of a Hilbert space, an incomplete Hilbert space. But the idea that we have made a measurement on a system is going to tell us what the solution is going to be because we made the measurement, and if we’d made a different measurement, we may have gotten a different answer. In a sense it’s kind of like, and again Bland and I spent a lot of time eating these French doughnuts over at ___, talking about it’s kind of like a Heisenberg uncertainty principle in some ways as applied to biological systems.

+Well that brings in essentially the measurement thing that we have never explored and we really need to go back.  We, collective we, really need to go back and take a look at where that’s going to take us at some time in the future.

*Depending on what you choose to measure and how you choose to measure.  Examine the way the process works is going to determine what you actually see.

+That’s the difference between us and population biology and the ____ equation.  They don’t measure anything.  They’ve got a population here, they got a population here, they got a coupling constant, they solve a differential equation and guess what, differential equation blows up on them.  Why does it blow up on them?  Take a look at some of the stuff that Bland was looking at back then.  We were taking a look at catastrophe theory and at fractals, and at solutions to NP-complete problems.  What we were finding is that the continuous variable techniques that were developed for population biology were totally inappropriate.  It’s not surprising that the solution didn’t converge.

*You can’t work with interacting processes.

+We didn’t have to.  Now there’s a whole field out there that does nothing but chaos type of stuff.  We’re sitting there looking at chaos and we didn’t have any idea what the hell we were looking at.  But we knew that the techniques that were being applied by May—the predator play parasite models which you know really are pretty.  They make really nice paper, didn’t solve one biological problem that we were aware of.

*Well the stuff that’s going on at Santa Fe doesn’t necessarily. It gets close.

+It gets closer but the point is.

That coin-flipping used for.

*From Feller.

Feller did was ___ and that, the data, and then the statistical analysis of that, even the expectation is unstable, infinite ___ much less var___ so I had already been looking at chaos theory by way of Feller’s work and I had to factoring that in all the way along, interestingly enough.  That was one of the things that so turned me off, the fact that these people are ___  precisely predict the biological statistics, that they were applying grants for, writing papers on, dah dah dah.

Event-Driven Paradigm

One of the things that really caught my attention was switching from thinking about time to thinking about events and scheduling events.  The whole concept involves scheduled events.  Between right now and the next scheduled event you have a Poisson process.  At that next event there may no longer be a Poisson process and it may be totally different.  Things may go on at that event.

But then you don’t go back.

*Right.  Then you reschedule things and take care of the bookkeeping and then you’ve got a Poisson process again.  That’s brilliant.

Of course that’s the core of the whole thing that makes it work.

*That’s right.

You have to be talking about events being the total orientation and time as a dependent variable, and the next moment you’re telling about time with events coming in as a dependent variable.  Does that make sense?

*Yes, and then it’s really complicated if you try to model it in terms of time because then you’ve got all these interactions.  You have a whole bunch of stochastic processes that are going on at the same time and they’re all interacting and you got to model all that jointly.

And if you don’t do it jointly, you lose all the biological reality.

+I think one of the things that Bland did which is really important from a philosophical standpoint, from a philosophical and mathematical standpoint, is the simple fact that when we started to do this work it was really clear that we needed a major conceptual change.  How do I relate that major conceptual change?  Probably the best way to relate it would be that Albert Einstein in 1905 made the conjecture that time and space were related and that is the basis of special relativity.

+Bland ___ the completion that the measurement and the state of the given small population of animals to relate it and you couldn’t diverge the two of them, that you had to work within that arena to solve a problem.  If you didn’t, you may be solving a problem but it had nothing to do with the real world.

*Yeah, so you move from a time-driven paradigm to an event-driven paradigm.

+We moved to an event-driven paradigm for a number of reasons.  One of them being that if we had done the time-driven solution—I mean it was like to the three-hundred thousands, and if you multiply that times the amount of compute power that we had, we’d still be doing the first time step.  Just for ten individuals.  So we moved to an event-driven domain for the very simple reason that it got rid of the time variable.

*It also gets rid of the interacting process structure which kills you from an analytical point of view in the time domain.

+But if you think about what it does, it projects out the solution.  You literally project out the solution that you’re going to be working on.

*That’s beautiful.

+One of the things that Bland did was the chess and backgammon games.  Basically we used those 3 particular analogies to define how a biological system worked.  Even if the system was completely deterministic like chess, something worse than an NP-complete problem, then you’re dead meat.

*So the ___ does pretty well but, yes, having to project so many pathways.

There had to be real biology in some way ___ for measurement in a very direct ___.  You exercise all the complex ___ and then all the link ___ they were tied to ___.  And guess what?  You’re right back to a purely defined currency ___ stationery ___ to the next event and parallel with 10s or 100s of thousands, even, you could even carry 10 a thousand ___ incredibly enough.  So that was the driving force behind everything else.

+That was our key.  That was our key.

*That’s a brilliant, that’s one of the brilliant points.

+That was our key.  That was the key to the whole thing that we did, ___ Poisson distribution and the idea of independent events.  We could treat each individual as essentially an individual until he interacted.   And that interaction was basically defined in the event space.   In fact, I remember going through that.  We looked for the minimum of the minimum of the minimum of all events and the next sucker that got it, got it.  If he died, he was erased from the rest of them and the whole event structure changed at that particular point.

+But we weren’t tracking individual times for each one of the persons out there.  When I can remember going through discussions. “Bland, is he doing anything yet?  No.  Let’s go to the next time step.  Is he doing anything yet?  No, let’s go to the next time step.”  And in the normal solution for time-based systems, that’s what you would be doing.  Most of the time you would be just iterating until the next event occurred.   

+Think of the distinction of basically what was being done by Robert May and groups with basically the population biology sort of system.  Everything was a continuous event, so things were changing based upon a set of continuous variables that may or may not be semi-continuous.  There were spikes that we were allowing and things like that but the point is is that’s not how the biological system works.

+The best example that Bland ever gave me was the rabbit and the fox example.  In a physical system, if the fox moves toward the rabbit, the rabbit takes one step back.  If the fox takes one more step to the rabbit, the rabbit takes another step back.  That’s what it would be in the physical system.  Some continuous function would describe the relationship between this fox moving and this guy moving, and it would be a continuous function.

*And linear.

+Yeah, linear.  What normally happens is the fox goes tick, tick, tick.   The rabbit is seeing him but then there’s this zone where the rabbit says I’m out of here.  Boom.  He doesn’t run two steps.  He runs to Fresno. That example tells you that you’re in an event-driven system.  You know the fox is not going doink, doink, doink, has anything happened?  No the fox is moving, but in terms of the interaction biology part of it there is no interaction at this particular point.

*We’re not modeling the interactions happening, cuz there’s perceptions going on, but we’re not modeling the perceptions, we’re modeling the movement.

+No, but at that particular point where the fox gets to the point where the rabbit says OK, I’m out of here, we’ve had an event.  We have not had a continuous function.  We’ve had an event and from that particular point we have a new problem, so what we were looking at.

Span and Resolution

+The other thing that was really key, and I’ve used this the rest of my life because Bland and I have had some amazing discussions on this, was the concept of span and resolution.  Before you do the problem, you ought to know what problem you’re doing.  If you plan on doing the problem from the ameba to the gorilla, you got a problem.  You have to limit the time and space that you’re looking at.  In this third paper there when we basically started to take a look at the Blodgett data and the distribution of fees and draw ___ functions.

+That was the first attempt to really defining a problem that was amenable.  You had stochastic events coming in at one end, because your resolution was not short enough, and you had constant problems coming in at the other end which changed the dynamics very, very slowly.  Like weather conditions, or maybe climate conditions, something like that.  Something that had a 20-30 year time frame, or 300-year time frame.  If you take a look at most of the work that is currently being done in almost any field, the first thing they forget to define is this time, the resolution and span of the problem.  It’s like the two words never got invented and we were looking at that 20 years ago.

*25 years ago.

Then the other thing is it’s about that time you start looking at this thing a little more closely and I’ll be damned all those things out there __ you’re now finding __ systems __ on  bunch of truncated __.  When you notch it down one thing and __ revolution.  So __ here pops out another kind of structure that’s really important to deal with and if you just randomly assign things across the entire __ you have a mind-blowingly big __ there.

Also I just very, very, very faintly remember.  I used to go __ model theory too from time to time, to go find out what made sense in terms of this or that or other things in mathematics, all kinds of things __ doing in the world.  There was this one, what do you call this thing?  __ problems __ pathways or all possible pathways, a set of all possible pathways over all possible events, or all possible ways to think __.  It’s __ problems __.  What do you call them?  They’re __ fact of life.  You know you can do them for 2 or 3 or 4 and then you __ go to a hundred and the other part __ and the number is so large there’s no way of ever presenting them.

*Common torque problems?  NP hard problems? [Not solvable in polynomial time—they take exponential time in the number of terms.]

Yeah, sort of like an NP problem, things like that.  That class of problem.  So, that’s the other thing __ because __ immediately this would be __ into a problem that is so uncomputable it just blows your mind.

Non-homogeneous Poisson Process

And so part of this whole trip was to __ let’s take a look __ non-homogeneous Poisson processes.  Have I got the right thing?

*Yeah.

I can’t believe it.  I really can’t __ non-homogeneous Poisson process __ the woman that was head of the whole program under __ and said was invalid.  In spite of the fact.

*Christine Shoemaker?

Yeah.  In spite of the fact that we had all the detailed proof in the papers that we gave her.  So life goes.  But at any rate, the idea there being that you could have done __ intervening by taking a minimum __ find that the minimum __ in computationally pretty and then some of the heterogeneous algorithms ___ graduate students to work out just on mind-bogglingly __ using priority cues.  So you have a very small group __ biology could make more sense to process it as __ information, go at it from the direction __ you process without getting __ say in the thousand range or the two thousand range, you __.  Because it grew exponentially or something absurd like that one, or something close to that. Exponential plus some small factor.  

So that was the idea but then you would simply __ linear math, with improved linear system __ because it was a non-homogeneous process it meant that you could feed into it __ data from other statistics, the other __ completely distribution free.  So all the time usually had enough of tying everything together that was __ sensitive, you could actually run on the system in terms of efficiency.  It was __ cost of all the intermediate events and even if you had a huge problem __ rather than using __, use priority queues __.  So then you __ guess what you have to do?  __ of millimeters __ by using just __.

But it’s an __ the consultation and __ but at the same time you’ve got to __ what things you got to, you’re going to end up eventually being able to have to put it into the form of a linear system, what do you know, sooner or later __ generally.  So they would come back to linear systems.  And then you would have to __ is no longer a linear system.  It’s been __ reality.  So __ going to have so many young, it could have zero young, or one young, two young, probably won’t have a hundred young.  __ it does that, __ a hundred young.  How many beetles will have a hundred young?  So you see how crucial it is to start factoring things into real biology, real reality at this point, to make things work right.

This is the part where the order __ things to happen, this is the part when __ it was the only thing around with numerical __.

### Physics

+You see that the problem is that Feynman had it easy.  Feynman really had it very, very easy. When he wrote down the Feynman path integral, as you know, he basically integrated over all possible paths that a particular particle could travel.  He essentially used the classical action and basically through interference processes everything sort of dropped out.  He got the classical paths in the extreme.

+We don’t get that.  We got 10 individuals out there, all of whom are interacting, none linearly, in time-delayed systems.  We’re screwed, so we can’t use the standard techniques that even Feynman used.  We need to have essentially the event-driven system that we came up with.  The problem, and the cornerstone of the second paper, is the fact that we basically merged biological information with mathematical technique, showed the limits that the mathematical techniques could take us to, and said from this particular point it has to be calculational technique.

+If you take a look at the solution of the four-color problem, it’s the exact same thing.  They took a look at the four-color problem which is a classic problem in mathematics, they found a mathematical solution which doesn’t work but ultimately the problem was solved on a computer and what Bland was proposing was that biological problems are not amenable to analytic solutions.

+Again, to go back to the only thing I really know and that’s physics.  If you take a look at what’s happened in physics, you see the same sort of thing about the time that Einstein was doing his stuff. You saw these various ideas of explanations of how to handle systems that essentially went relativistic on you, with the speed of light.  What you found was that everybody had a solution for it.  But in each case that they found a solution, they also found something that wasn’t a solution.

+Then along comes essentially Lorentz.  He says “OK, I don’t know what the hell is going on here but I’m going to invent a thing called the Lorentz transformation,” which Bland is very, very familiar with.  And guess what?  All of a sudden everything that had to do with Maxwell worked and everything that had to do with classical mechanics worked, but he had no idea why.  All he knew is that it worked.  It took somebody like Einstein to come along and say this is what you did.  We are going to relate time and space together and everything falls out.

### Population Ethology

+Bland has said you cannot divorce the measurement technique from the answer that you get.  If you do, you get population biology which is by definition the wrong answer except in those wonderful cases where it just kind of happened to work out.  Or you get something where you can’t do anything.  Basically what you’re faced with then is doing the Charles Darwin routine of collecting a lot of data and hoping this thing works.

+Bland gave an intermediate point.  You can take a look at small populations.  This is what a biologist looks at, not 10 to the 23rd animals, but you can look at 20 animals, 100 animals.  You can put collars on things.  You now have a technique developed where you can basically start some sophisticated analysis, not just doing means and standard deviations.

-What Bland puts in this paper is also individual, how the individual in the group relates to all of it and without that individual’s own ___ characteristics.

+We define the individual ___.

-__ applying this to like ___ what is community and why people exist in a community by looking at this paper so that’s pretty far out but I found it fascinating.

*Interacting individuals and each individual has its own uniqueness.

-Because I just studied this same.

+You remember?  You remember when we drew up the list of what an individual was?

-Yeah ___.

It’s right there at the bottom.

+We spent something like 3 months over that stupid list of what an individual was.

-But that is a really important list.  I wish I would have had that list just about 2 weeks ago, I’d put it in my paper.  Because what I was studying was the difference of law in China, China’s law base and ___ law base.  One’s based on the individual, one’s based on the group, it’s two different basic concepts and it’s right here in a whole different way.

+We’re so cool.

-I could have plugged all that stuff in.

I’m totally cool.

-Yeah, you’re cool Bland.  That’s right.  It’s fascinating.

We are a group, and yet we’re four interacting individuals with a totally different mix of skills and personalities.

-That’s for sure.

How well does that match your, the idea that ___ the entire population ethology ___.  Ethology is the study of individual behavior at the individual level ___ the uniqueness of animals interacting with people on a one-by-one basis ___ each individual is unique in his own way.

-And there’s the dichotomy.

*Yeah.

___ that first ___ how many ___ out there ___ deterministic ___ so I ___ the entire world but it’s also very true ___ with all living organisms, all with living systems.

+A lot of what we have gone through has in some sense just been taking the fundamental ideas that we’d developed here and then sitting there doing the Dutch boy and the dyke routine.  We plug this hole here and then we plug this hole here because we didn’t have the techniques available to do it.  The philosophical and theoretical stuff I think for the most part is reasonably complete here.

It’s from a biologist’s perspective, Bland Ewing’s perspective.  It is not from the perspective of the mathematician, though Bland is probably a better mathematician even now than most of the people that work in the field of mathematics.  I just think that we’re getting to the point, probably within the next 5 to 10 years, that this kind of a technique is going to become one of the most valuable techniques out there.

*See the explosion that’s happening with Markov chain Monte Carlo that’s moving around, which is a lot of the same aspects of what we were doing.

+Of course all of what I said has to meet with Bland’s approval.

No.

Modeling on a Budget

Yeah, sounds great to me.  It was interesting to have talked with Jim about some of the issues. he’s also __ from a conversational point of view, a computer point of view.  That’s the other thing that eventually depends on ___ at a very low level, probably ___ assembly language or ___ machine where somebody’s going to be using ___.

Because you just can’t take much overhead, you can get debugged ___ but you’ve already seen the problems, at very high level languages and trying to get any efficiency out of it.  And the thing is that it’s not your job ___ to do that ___ and not really Jim’s job either or anybody, or mine not even, it’s, we’re going to have to find places and pieces and things ___.  Actually the ___ thing was laid up and all the pieces are there and.

I could even use this machine right here ___ have such a problem with trying to type or getting, like buying ___ overtime.  There’s a lot of  work that I can’t do ___.

*Yeah, well you’ve got the ideas and that’s the key at this point.  It sounds like Jim wants to take a crack at it, the computing. I assume he’s got some support staff that he can use to help out.  I mentioned earlier that I have an ecologist friend who has a student who wants to work with me.  I’ve given him a copy of that document to look at.  I gave it to him about 2 weeks ago.  Actually I gave it to him just before I left on this trip and so I’m curious what his reaction will be about this stuff.

Building a Model

__ how that could be implemented.  But the thing is that that, with Don Dahlsten’s data, and also some of Bob Luck’s data, you see they were both also involved with generating numbers of counts, where counts were really the basic data that you had to build everything else from.  It was a quantitative anchor into the world.

*Yeah.  Well Bob Luck and Jim Barbieri have been talking and making some plans to do some modeling, particularly on the scale on the oranges.  Orange scale.

It would certainly seem to me that would be another thing they would have probably would be, if you can do it for the bark beetle, then that should just be a small thing to __.  The bark beetle wouldn’t work right for his system.  OK, so the other question I have is that OK, let me, trying to pull a number of things.  Things, what I want to pull out is __ but there’s also.

*Gamma?

Gamma, thank you.  Gamma function, and there were also some other general kinds of __ that people go to __ over as I remember.  Everybody has their own favorite linear distribution for numbers.  There used to be a blood issue a long time ago.

*Yeah, I think it still is for some people.  I think the computing power has.

Made it totally silly.

*Yeah.

Running Model

I actually got it up and running later on, showed that to Jim.  It was also a time that the evolvement __ trained to do the first things, again plots of this stuff over things like both their own data and also things like the, what was that?  The moose wolf predation thing that we were using as an example in the first place.  But that part, yeah, part of it got out what needed to be done that never got done.  Where the parts I did get done were some of the summary __ shaped curve and manipulating error and so that __ generating hand numbers for people like __ really wanted to work with.  People like my major professor Justice wanted to work with too.

Dave Baasch 

Basically that’s why I got started using the CDCs on campus, and that’s really where I got started doing the modeling with Bland.  We started working on new models that weren’t just regression analysis models, and really working on stochastic modeling.  I liked it because it made sense.  

With this we can build a model that says this is how we think the system works.  Now let’s see if the model works.  If the model doesn’t work, that means we don’t understand what’s going on.  So we need to change the model to reflect our learning and our new understanding and see how it correlates to the real world.  The whole idea behind this, to me, was that the models were a test or a verification of our understanding of the system as opposed to well, I can measure 2200 things and come up with a prediction based on who knows what.  This is the correlation.

There was some interesting stuff going on with taxonomy at the time.  Numerical taxonomy was the big thing where you don’t weight characteristics.  You just measure as many characteristics as you can.  Give them all an equal weight and then compare them to get a measure of differences.  Well, in one sense, if you can measure enough things it probably matters.  But people were measuring 20 things, such as has feathers or doesn’t have feathers, and that’s a significant characteristic.  It’s probably more significant than has red feather shafts or has yellow feather shafts.  People would just choose the things they could measure.

I had a problem with this kind of correlative modeling, I guess.  The stuff Bland was doing and the stuff he was looking at with stochastic modeling and stochastic processes made more sense.  Everything I know about stochastic statistics and modeling was driven by Bland and the modeling he was doing.  I liked it because it made intellectual sense in terms of trying to describe the system.

He was only using it for small populations and he wasn’t trying to use it to model the Pacific Ocean.  He was using it in a relevant manner that intellectually appealed to me.  The idea behind the models and the reason for using them, and the reason for doing them that way, felt intellectually clean to me.  It made sense and it was really different than what everyone else was doing.

Now he went off on a lot of tangents.  He did in terms of data representation.  I mean he was always amazing me with what he was trying to do.  I had never seen stereo photography before.  He used stereo glasses to look at aerial imaging and played with that.

### Small World Networks

So all these things going in parallel(?).  But also at the same time, this thing of fractal stuff, not only that but __ as though the theory of nearest neighbor and other things like that.  __ run a lot of things but there’s the type of theory that __ like to do model theory and things like that.  Some of the far out mathematicians __ proof for lunch.

And for people like __ I guess the whole thing where you __ nearest neighbor thing and it turns out that the thing about the fact, that all you needed is one strange linkage into a system and it will totally shortcut distances, interconnecting ports.  So __ all these strange linkage, compared to the rest of the world out there.  Or it’s the old hairdresser type thing where the hairdresser seems to be the center of gossip and __ cross-connects stuff.

*Small world networks.

Yeah, small networks.  Beautiful.  And it turns out that if you have a totally random system, it doesn’t do zip if you have a totally, even __ not do that, but if you have a system that had all the __ and bits and pieces, and __ connection, it makes it a very small world.  So it’s going to be interesting to see how some of the __ kick this stuff around in the future too.

*Well, that’s being used for comparison of protein sequences, DNA.

Oh, I didn’t realize that.  So you have a practical application, I’ll be damned __.

*Yeah.  Also with fractals, I’ve heard a couple thoughts of using fractals to model internet traffic.

Yeah, and I bet it’s going to do an incredibly better job.

*Yeah.

Especially if you’re go __ any type of selecting process __one in human brain, where people have tried to emulate that and it’s been a total disaster in terms of any real quality of the work, you know, even Jim Barbieri __ some stuff.  I looked at the number of mathematicians.  Boy they like to throw a lot of curves at __.

On the other hand, he showed me a book by the guy down there at Caltech.

*Carver Mead.

Carver Mead, thank you, Carver Mead.  Sometimes I can grab his name, sometimes I can’t.

*Yeah, it’s funny.  That’s one name you have a lot of trouble with.

Yeah, Carver Mead.  Anyway.  So the theory __ his work and some of the things that that was __ and so they, I guess they found some interrelation of stuff, but the main thing __ what the system really needed was a completely nonlinear __ stochastic for some problem, and certainly deterministic __ nonlinear systems to chaos.  Chaos, build a system on __ selection, then based on, then my guess was that they __ systems that actually worked __ so that was when I pretty much lost Jim on that kind of stuff. __ I’ll be damned __ chaos again __.  Chaos and practice __.

*Yeah, well sometimes, yeah, chaos and complexity.  I’d like to go down to the Santa Fe Institute some time.  That would be, you’ve heard about the Santa Fe Institute?

No, I haven’t.

*Uri Gelman set that up and he got a bunch of people together, including Metropolis who was one of the original Monte Carlo people, and they studied, Holland, a guy named Holland.  Anyway a bunch of people who, he brought them together to study chaos and complexity and they got together I think it was about ten years ago or less than that.  I don’t, maybe about ten years ago, and they have been meeting ever since and they have conferences and it continues to be an interesting hot bed of ideas in this area.

This is interesting also because Monte Carlo was one of the key pieces of making his modeling technique work.

*Right.

There were about a dozen __ and he keeps __ Jim Barbieri.  There was a stack of at least a dozen fundamental pieces, any one of them was reasonably simple and standard within its own field and __ something a little off the wall, where the second __ type thing.  Like __ using the simple Monte Carlo, I mean simplest thing we are using the generalize __ processing center __.

*Right.

__ rather than just a simple __ generalized integral type form of it.  Is that correct?

*Yeah.  Sounds right.

__ that wasn’t just in the first form but still it was something very straightforward.  It wasn’t very off the wall either.  But then it took a __ all put together at the same time to make a modeling system work.  Of course, you were one of the first people that took some of the __ math and then of course Jim Barbieri was the first person to try to program some __ and also __ writing disability.  He __ if I had that __ writing disability __ and no matter which technique or any, I had a writing dyslexia that just, I’ve always had to find somebody else to help me do the writing because I never could.  At any rate, so it based these on Jim.  He takes after __ going after that meeting, where was it?

Follow Up

*Yeah, I think that concept of modeling to the precision of your system is really, I don’t think that’s well understood.  I don’t think, you know, if you have, if you can’t measure things very well or if it doesn’t even matter, I mean if there’s enough.

One or the other or both.

*Right, if there’s slop in the system, you know, so that, I mean the environmental system or animals or plants can adapt to it a 10% or a 50% slop, then maybe that’s the way it should be modeled to.

Otherwise you end up with a __ that has no relationship to the system you should be modeling.

*Yeah, right.

To say nothing, it may be a little harder problem than you really need to have.  The problem many of the existence __ logarithmic __ of an order of magnitude __.  And a high precision system might, you might have some that can say you really could measure, it’s a heavy duty, whether __ system but 10% or something like that.  But I just couldn’t make it go much beyond that.

I’m rather curious though about one thing I would like to __ the question.  Have you seen any glitches in the system?  Any problems with the system __ into and so forth?  Or does it all seem to hang together still after all these years and decades?

*It all seems to hang together and I think there are people doing something approaching aspects but I’m not aware that anyone has really picked up the depth and the subtleties of what you developed 25 years ago.  I haven’t seen that and I don’t.

Model Components


* Hexagon

* Splines (also Adobe Acrobat)

* Sample Splitter


16. Model Components

        Splines & Bayesian Statistics        splines.1-15

        Splines        splines.1

        Bayesian Statistics        splines.9

        Hexagonal Grid        hexagon.1-17

        C.S. Holling        hexagon.1

        Programming Style        hexagon.1

        Hexagonal Grid        hexagon.3

        Computational and Biological Issues        hexagon.5

        Random Numbers        hexagon.7

        Stereo Pairs        hexagon.9

        Zeiss Microscope        hexagon.12

        Sample Splitter        splitter.1-9


Splines and Bayesian Statistics


Splines

OK, what I did is after we had covered most of the stuff last time.  I had sat down last time and reread the entire report and it blew my mind the stuff that’s in there ___ and there’s even a bunch of notes at the very end where, that were never transcribed.  They had all the notes though, I was wondering if anybody got ___.  There was even that.  Those notes were there.  The only thing that’s missing is some of the ___ stuff where I chose some much nicer ___ to work ___.  ___ with, you say hey, what do you call them?  Escalating functions ___ they go exactly through data point.  Is that right?

*Interpolating.

Interpolating functions, OK.  Interpolating, thank you, interpolating functions, they go exactly through data points are really a whole lot ___ that I would work, was working, insist that your data move exactly through your own data point.  It was crucial to them that the data points that they had measured on their own stuff was that the point ___ had interpolated went exactly through their data points and these interpolating functions then, be they polynomials, that was traditionally used at that time, whatever ___ you needed to get a degrees of freedom, but go through the points.

But that sort of ___, first find out about ___ unstable polynomials because you could get a sudden 7 or 8 degree or 10 degree polynomial to ___ or log the function or ___, try to use the same function on biological data and ___.  And that’s, I had already gotten into using APL has laid down, most APL ___ and some script ___ my dissertation and it turned out while I was writing with it, and why ___ figured that I could just do the, you know try ___ type of interpolation on piecewise smooth, third degree equations.

And it was, I almost thought I had something publishable and now it turns out that 100 years ago ___ came out with ___ because somebody finally dug out of the literature.  So ___ were the same, they were describing ___ or also interpolating functions.  But the smoothness properties are really important and some of the other ___ like that is really important and the thing, if you, I ___ the, had calculated the statistics for what made sense if you let the functionalism up a little bit and ___ in terms of the ___.

*Common Graf.

Statistic.  Then it said it much better.  And that was your real distribution free method, or figuring out how to bring your data points ___ so using that ___ type of function for doing the fitting, I found that I could get a better ___ using, well at times they were called B spline and also under those circumstances I could then have a very ___ metric ways that a biologist could easily understand it cuz they’re both visual, need to view the data, because the B spline you ___ Koppel or coincidence points and there was a spot ___ points ___ without having the functions ___.

But the B spline, that actually frees up the direction so if you got ___ that you really can’t do it, and yet you ___ that you know from the data, or the nature of ___ the direction ___ or maybe the ___ the distribution ___ so what you need to do is just put one extra point in the direction you want to go.

And also you don’t have to be fooling around, I absolutely, I hated, hated this busy ___ because they have all these nasty properties, I don’t know how you have to line points and do internal things and point things internal to the points ___ very natural thing I just described.  And that’s why I had gone there, I had such a fantastic argument ___ the fact that he was insisting on using a basic building block and postscript but ___ been using the ___ in terms of using ___ that wasn’t technical and I was already onto that point, on to ___ which ___ already described.

And it looks like that research paper ___, nailed it perfectly on where ___ should be ___ of B spline and if you don’t have ___ computer graphics, ___ be the way to go.  But on the other hand, ___ overkill for them.  So B spline seemed to be just the right combination, which ___ lightly so it didn’t have to exactly interpolate the data points because that made no sense in the statistical ___

We were describing anyway, in spite of people’s beliefs to the contrary, and it also gave you the ways of working the control, additional control ___ in a very natural geometric way that biologists can quickly understand.  And I also ran some ___ and it’s relationship to the ___ statistic or the ___, what is that?

*Well the common Graf statistic.

OK, that particular one, OK, you know Common Graf statistic.  And the other thing is that I had been looking at the truly blew my mind ___ and had ___ and the techniques related to ___ statistics, am I saying that right?

*Uh huh.

___ statistics, and percentages of all the sample based on the order of  statistics, you have ___ totally distribution free ___ where you hadn’t given ___ sensitivity.  ____ as the absolute best and most fabulous normal distribution when you have an exact normal distribution or a completely linear system, or complete normal system, what can I say.  You see even, ___  plus the sensitivity if I remember it, of the task.  They don’t take much contamination to totally screw up the normal distribution, is that right?

*That’s right.

So on the one hand, here I was finding everywhere I was looking in the real ____ mind boggling and ___ I just realized the piece I wanted to say something on, because it involved generating normal distributions later on.  We can come back to that, I won’t forget it.  So anyway, the normal distribution even was a ___ contamination, you end up ___ that for sensitivity with ___ normal, and yet these other say perfectly ___ and they, as I, that statistic I just described would totally ___ you didn’t give up anything on fractal.  It could be a pure fractal distribution ___ and the ___ the sensitivity of a normal distribution with no contamination.  Is that right?

*Yeah.

But just, cuz you see, all I’m trying to do is yank some of that ___ there at Cal Berkeley, OK?  And the stuff that never got into the notes because of that.  But they’re like I say, notes of the point where we got on track further into the older statistic stuff but ___ binomial technique of searching for the next, for the false value, or ___ statistic for, no, whatever, anyway it was the one that got in the.

*Bisection.

Yeah, right.

*Bisection.

It was an ___, just one niche away of making it so you have a really good ___ way of looking for the smallest value in the set.  Less history, less history, here’s a diagram ___, less history,  I want to cry.

*Volume 2 I believe.

It was less history.  It gave you a log, order log ___.  You get an arbitrarily large sample and get ___ just mind boggling.  At the same time if you had just a few ___ then the directed rings they were using turned out to be ___.  All that work had already been done, the ___ the work, how that worked out ___.  If you had a small sample, a small population, or small dimensionality, the ___ that ___ for the minimum, the minimal of the set.  If you had a thousand, ten thousand, a hundred thousand, a million, you could push a billion population and not have it nailed on that one because it’s so in a ___ function. 

Anyway, so Knuth did them again.  What was all to blame on mine, right in that very last time when I was sorting through the ___ up there, the math department, the computer science department, their ___.  I thought I’d just describe them to you.  From the way you’re nodding your head it looks like that’s sort of the way that the long-term things had actually held together.

You know sometimes people will claim or try something.  Then there is a mistake or it had very limited range of value to work in.  At any rate, the B-splines so because you see the ___ their data must be exact or has to have an interpolating function to ___ and I guess, you’re thinking about it in terms of, like a ___ system in ___ Robert May?

*Robert May.

So ___ I just, OK, I could see why the people with that kind of an orientation ___ would indeed insist on interpolating function.  In view of things measured ___ exact, all you need is just the differential equations ___ describing population __ population, rates of ___ and blah blah blah.  Had population parameter played ___ this is exact.

*But you need to know it exact all the way up.  Not exact to three decimal places.

I guess that’s part of the reason why I was sort of  ___ go back to interpolating functions for any of the data that I had to do the experimenters with on the program.  It didn’t seem to matter what the program ___.  But it turns out, then in terms of a completely ___ that doesn’t give you as a good a fit and the B-splines actually work better.  And all that junk as distribution ___ each level.  Blows your mind.  You could probably ___ because ___ you couldn’t ___ gee it works so maybe I’m, where is the other tenth percentile or ___ tenth percentile, so is that right?  Is that?

*You were talking about interpolating splines and that you do much better if you don’t interpolate.   You were talking in terms of evaluating using a Kolmogorov statistic and how biologists wanted to have curves that went right through their data points, but you did much better if you didn’t interpolate.

Yeah, and it turned out that I could get a better bound by using the distribution. OK, and the thing is that so, the underlying statistic was the ideal statistic for, it was the ideal statistic for characterizing bounds on the thing.  Then the interpolating function.  The hermite spline which is, one reason it didn’t do as good a job as the B spline.  To say nothing of the fact that, and the B spline had the other qualities I already described in terms of laying it out in a manner that would be geometrically intuitive easy for say a biologist to make use of.

As I’ve said before, and it’s interesting that Jim remembers also my getting up, running, or adding, before you get together ___.  What do you call, the cubic spline?

*Yeah.

And the interesting other side though is what I remember, I tried a variety of things at different times.  It turns out if you start moving into a higher degree equation, but of course trying to invert now is expensive and sometimes it doesn’t even work because you reach unstable things in the process trying to calculate orthogonal polynomials, for example.

And was it Bellman, who was the numerical ___ I think of AT&T’s ___.  Was it Bellman?  I can’t remember.  But at any rate, he came up with the idea of approximately ___ function.  He noticed what the process was doing was to space or ___ out ___.  He could do almost the same thing by assigning fractions to the roots that were easy to calculate and that also in ___.  He had almost a ___.  That was good enough so it wouldn’t explode in the calculation, which is also sort of an intriguing idea.

Interesting but still what do you do when you got 20 items, 20 animals in the population?  It gets a bit cumbersome again, so there’s this problem of bridging to the ___.  The cubic spline seemed to have the best properties that I can see and it doesn’t seem to blow up anyway with the larger numbers of samples.  

*And there’s been a lot done with cubic splines.  There’s a lot of nice theory and it’s been used in a lot of different settings very effectively.  So it’s very adaptable.

Nice to work with.

*Yeah, it’s a nice system to work with.  Good code.  I actually worked on cubic splines in Madison.  I have a couple papers on splines.

__ engineering shouldn’t be all the __ to factor in some that maybe your pluses or other thing __ and should be put aside for some case __.  Cuz when you get out there and you’re finally in the, and you’re looking __ mathematician you find you almost never do __ proofs.  You almost always do it the contradiction of applying __ with the middle.  Am I right there?  Boy am I __ which maybe be totally fallacious.  But as I remember, that one of the things that made it because of the __ you could set up a contradictory condition so you yourself wouldn’t be __ and then move through the steps of a proof that would then you would prove the thing out because of the __.  Once you start to include an e in the single piece in the middle, you’d then have to do a bunch more general constructed proofs and you would be surprised all the mathematics done in a constructive way.  That’s another just off-the-wall sort of thing.  But it’s a problem.

Somehow you got to factor in the appropriate levels of __ you’re really looking at and __ you’ve got a big __ for a log function.  So what we had already done was the transfer, a pre-transfer of this variable from, the __ statistics approximated was a smoothing type of interpolation to get a metric, a triple, what is it?  A triple?  What’s the spline function? Spline function.  We were basically interpolating these things then with a spline function that had a smoothing property.  __ these things were a bitch in terms of crookedness.  Basically if you plotted and just arbitrarily __ and yet all that __ and you’d look at it __ doing an underlying process or see a complete __ process as compared to __ for a year, for births and deaths of people that __, that’s very jagged.  You accumulate tens of thousands or even millions of people, it’s a pretty small function.  So __ is also using the appropriate type of order statistics across things that are like the statistical techniques that are safe, used in demographics.  Demographics, that’s right, isn’t it?

*Yeah.

So that’s another fragment that’s supposed to be in there but it also was a way of __ parts of that so you wouldn’t have __ some reasonable way.  And then what you did is you took the spline function, you plotted this, you took the logging of data or the exponential, I mean the exponential of the data, and that’s the one that you’d actually compute with.  So __ wasn’t even hard to compute a log or exponential function in the process of running the model.

By the time you had transferred into this low __ dimension, high multi dimensional, 32 byte integer across all dimensions that you needed, you’d use the right amount for biological reality.  You’d then hop across the things like gangbusters because you’re doing computations that were really fast, they were the simple additions.

Lot of history.  And __ very important piece of the modeling technique but how to tie the detailed information where we put out that one example say of the depth of the __ what was this thing?  It was on the __ problem from biology.  It’s in there.

*You’re not talking about the flour beetles?

No, the flour beetles are another whole issue.   Not what I meant was.

*No, that’s not it then.

Because the flour beetles were another whole direction.  The name __ people they all thought we were wrong.  They really disagreed very strongly with the __ the fact that the direction we __ biology.

*Elegant mathematics.

Elegant math, yeah.  And __ tricks just really made them go like gang busters.  Also very, it seemed to me to be very particular.

*Are you talking about the bark beetle problem?

No, what I’m saying is that we __ an example for the cubic B spline from classic data from biology.  But at any rate, there’s a whole issue is the thing that we also need to __ .  It’s easy for people to use the kind of data that __ collected for the bark beetle.  It’s just mind boggling how numerical and __ check __ just incredible.  Cross-disciplinary data collection.  Something that’s never done. Some __ on the same system.

So we had __ structure, we had data, we had __ behavior, we had__, we had maps of the forest and their distribution and on and on, __ goes on forever.  Part of the thing is how can you have this detail, a beautifully done study, with all of the numerical stuff and yet have the __.  If I put these two trees __ close together in our spacing, I would expect an increase in the rate of the root disease to move between the roots.  Or if I had this increase in the population I would expect a kind of death of trees unless I’m down in an area __ where you have __ pollution __ so thin that it destroys the beetles so they can’t go to healthy __.

How do you then factor in the direction and problems like that?  That was __ was aimed at also.  You see very often you have some pretty good ideas of the general shape of birth rates and death rates, you know, of some animal __ boy it won’t be very young before it’s born.  It won’t be very young after he dies.  Very often things __ have a tendency to obscure that kind of information because of the way __ time on top.

*Yeah, it’s collapsed across space and time.

And the way that, because it was, the way it was collapsing stuff, it was __ data from two totally different times and spaces __ animal __ history, __ the age and __ with and egg and pupa __ if I remember.  Is that right?

*Yes, that’s right.

Just off the wall remember __ long time ago.

*Yeah, cuz the eggs and the pupa don’t move.

__ together and larva, adults do move so __ together.  You totally combine the egg structure __. If you were a person that did statistics on people, what’s the study of that stuff, demography?

*Yes.

For example, and you were collecting all different kinds of birth data, death data, and so on for human population, and then you, somebody did something like that to your data, would you __?  Would you __?  How about the whole __ totally?

*Right.  Yeah, but it’s hard to do anything analytical unless you make those kind of simplified assumptions.  Then you need to go to some sort of Monte Carlo method because you can’t really do the analytical work if you build in a sufficient amount of biology. 

Yeah, at the very minimum you’re going to need a Monte Carlo.

*Yeah, unless you’re just looking at physical properties of the environment.  Soil properties.

And all of a sudden that turns out to not be simple either, has it?

*Yeah, that’s true.

Has that turned out to be so simple?

*No.  I have a geology thesis in my car that I’m reading on this trip.  No, it’s very complicated.

And when you get off on that part of the world, circles are not exact circles any more.  They are maybe a __ sort of round and may be centered on the system. You may be very interested in say how far you are from the __ of a tree to tell you how likely they are to pass on disease onto some __, right?  Or how far you are from a given tree in terms of behavior, both disease and behavior say for the bark beetles attacking and so on.  Then once they’ve __ the tree __ rising.  

Boy is that structured.  And structure on a system indeed is sort of a polar system.  It is a polar system.  But it sure is not an exact polar system.  And the trouble is if you try to move over and it’s just like that normal distribution, is a real pain in the tail to structure exactly.  You can __ pain in the butt to try to connect exactly.  And the more precision you need, the more hit you get on trying to calculate them.  So to be very exact mathematics, boy it costs you dearly __ machine __ you’re going to need to make things work.

That’s a whole other issue but also is a very important one in terms of what’s reasonable and __.  Not only a mathematician __ but the biology ought to figure out what they’re doing too. __ modeling effort in a reasonable way and then __ runs be able to look say at the Monte Carlo run and say oh gee, this combination with these other ones __ where this other combination hardly hit any trees at all.  And if __ air pollution __ gee that’s __ bark beetle __ food resource, and so on.  So __ linear problems to deal with __.

Bayesian Statistics

So that is my general inclination there, OK?  From what I’ve seen, that I can remember and the other thing is anything ___ supposed to be doing is getting some reality checks on your actual data.  It’s supposed to be, the way that you’re supposed to be plotting the data, you’re going to need an interactive system that can also plot the ___ or that data.  And then you’re going to need to factor in deviant type statistics to then weight it and ___.

*Yeah, it is either heads or tails.

What?

*It actually is either heads or tails.  There’s no chance about it.

Well it’s a, ___ write about the ___ distribution ___, if you’re not, if you don’t take the days in assumption and you let a classical approach, which is really ___, I am right that it’s a U-shaped distribution for the ___.

*I think that’s right, yeah.

So anyway.

*You know I didn’t get much training in Bayesian methods and I’ve been learning it, learning by doing and learning from students over the last 4 or 5 years about Bayesian methods so I’ve gone into some problems in genetics where Bayesian approaches seem to be the natural approaches to take in a lot of them ___ technology, so.

Cuz you have both, in the genetic thing you have both.  Sometimes you can have larger amounts of experimental data already collected available to you.  And you also have some ___ ways ___ combine genetic rules.

*Right.

So how do you put the two together in a reasonable way?  ___ classical ___ are great for that.  I don'’ think.  It’s been a long time, you know, you’re going to have to see.  Case by case.

*There’s some things that you can do readily and some, but then more complicated things get tricky.  It depends on who you talk to.  So I’ve been learning about those kinds of approaches and I sure hope that we can find your code on the recent implementation and from what Dave Wood said, it’s quite possible that Don Dahlsten has the stuff because he said Don Dahlsten has all the population dynamics stuff, so he may have it in some box down in Giltrect so that would be nice.

But at any rate, those together ___ meet the end there, because somehow you have, it seems if you’re going to look at a possibility of a woman having a child and know when she might have it and given that she ___ you know the distribution for children, all the kinds of stuff, where ___ statistics have been collected on that stuff, you know, for years.

So how do you factor in a reasonable way, that kind of ___ information to a particular set of problems?  I couldn’t think of any other way other than Bayesian statistics to do it.  It also was the, so are you going to be ___ to draw and ___ and in some cases ___ draw points out because the simplified ___ mix of other earlier data for that ___ situation and the ___ you’ve done because the ___ and that was actually drawn on a particular type ___ interaction ___.  If you’d drawn that same thing on the same statistical ___ at least ___ assumes you sure wouldn’t expect ___.

And it’s amazing how many biologists seem to think that you should, but how far is it reasonable to move and what kind of writings does it use and how do you use it.  So I think there’s a whole area of sort of, it’s a graphical approach that would just sort of ___ being able to be done 20 years ago but now it’s easy to do on a computer like I have there in the other room which is a ___ we could buy at that time.

Small model, lower speed, it just wasn’t ___ memory, and that’s it.  But we completely had ___ to do ___.  And so, so that sort of approach needs to be factored into it and ___ distribution ___.  You can split the data some rather than following it slavishly because that problem just isn’t ___ so that’s sort of where it’s at ___.  Is there anything else?

*I can’t think of anything at this point.  I think we’ve covered a lot of ground and I think it’s perfectly fine to stop right here and pick this up at a later time. I was describing to him the things that had gone wrong with our computing.  First the original ___, after they screwed everything up telling me ___ none of the stuff could be changed.

*I think Don Dahlsten has that data.  He has all the population.

+Is Don still alive?

*Yeah, he’s still at Gill Tract.

Just some pieces are in there, of some pieces that I consider what needed those things ___ and those are almost the last work I did on pieces, on a single piece.

+Well, we’ll just have to reconstruct it.  There’s enough talent here to do that.  It’s all sitting right there.  I’m sorry Bland.

If I do a coin flip, what’s the probability of, what’s the prior distribution for coin flips?  You both got something in mind?  Do you have something in mind?  

*Yeah.

OK, tell me what your’s is in your mind?

+The prior distribution.

*Well, 50-50, heads or tails.

OK, 50-50 and what kind of ___?  50-50.  What’s your prior distribution?

+Bland, I don’t have a prior distribution.  I don’t have a prior distribution.

Same as his?

+Yeah.

What’s interesting ___ you are both Bayesian statistics, did you know that?  You just gave it away, Bayesian statistics.  You just applied Bayesian, interestingly enough.  One of the other things is that the prior distribution is a classical theory looks like a ___ U ___ goes to infinity at zero.  Infinity ___ and the thing is you’re essentially assuming that ___ is a totally dishonest ___ that means that half the time you’re going to be ___ a two-headed coin or half the time you’re going to be ___ a two-tails coin, like the gamblers like to use.  This is the way that ___.  Do I remember that piece right?  Do I?  I’m curious.

+Yes, you do.

OK, what I’m trying to say ___ to set up prior distribution to do the next level adjusting all that stuff I had done has vanished, and do you realize how important I consider it by the game I just played with you?  Because I also always considered myself a ___ I’ve go this ___ population data, the death rate, birth rate, and I don’t use it to influence the way that we work between sample distributions and what we’ve got going is madness, madness, pure madness, so the next iteration on interacting and ___ with the computer was to factor ___ into everything.

*I wasn’t around.

+Yes you were.

Pieces of it.  I just wanted to throw that out there because it’s so crucially important and it’s all vanished.

+Yes, that was part of the stuff that went south for the winter.

-How did it disappear?

*It might be in Dave Wood’s log cabin.  That’s one possibility.

Now I ___ exactly the two pieces.  One was ___ and the other ___ stuff for weighting things.

+I’m going to start building the Blodgett stuff.

*I’ve got it on tape here.

+I’m going to start building the Blodgett ___. If I say it loud enough, it will ___.

-Better give the day’s date.

+It’s actually going to be, you know, taking a look at this stuff that I have now, and this is going to be really valuable.  I think I can probably.

Do you realize how well ___ statistics ___ you’re ___.

*I tried to find your notes on the Bayesian stuff, the Bayesian modeling.

That would really be neat to have.

*I couldn’t find it.

That’s too bad.

*Yeah, so.

Because you see I __ only half __.  Sometimes I’m on pure Bayesian if I’ve got a very small sample and I’ve got one that’s supposed to be __ random.  __ cases it’s about the last __.  But as I remember, what I had __ was the Bayesian equivalent to the curves that we were estimating so you could look at a Bayes __ the graph and curves of that B spline. I had moved on to B spline stuff __.

Once you need, if you’re going to __ do a projection in space, and then you have to recalculate.  You can calculate __ your one time and __ stay in place __ B splines __.  But B splines really are much more appropriate for the type of thing we were doing for kind of scale and also for time to __ the kind of triple type of things that we were using to estimate __ that won’t pop into my head either.  What’s the triple three things that we were putting spline, or the triple, the spline functions for triple things?  Having __ things together.  Do you remember?

*Triple things?

These things we were using for the degree of smoothing we needed.

*Cubic spline?

Cubic spline, thank you.  Some days these will come and sometimes the other will not.  So somehow you’ve got __ cubic splines that were typed as the data and B splines that were typed to __ information and the harder __ information __ Bayesian method.  That’s what I was thinking.  That’s where it’s supposed to fit in.

*That’s mainly where it fits in, ok.

That’s where it’s supposed to fit in.

*Ok, I can reconstruct that I think. Jim knows some of that stuff?  Was Jim involved at all?

Yeah, discussing some of that with him, and we also had the first cut of __ adding groups of normal, of straight places together to get our single hunt function.  That was radically faster than __ distribution __.  He was helping me with that and we got some of that up and running too. In fact __ nurbs, norm uniform rational B splines.  Does that sound right?

*Yeah, well you introduced me to that.

NURBS.  So anyway, and indeed the first paper appearing on it was a research paper from IBM while we were right smack in the middle of doing this modeling work.  NURBS not only were stable into transformation, rotation scaling, rotational __ but they were even stable under projection that you would do for, in 3 dimensions, say projecting something, and you didn’t have to recalculate everything.  But the other thing that was remarkable, it also let you do circles and ellipses and hyperbolas and parabolas, exactly, not as an approximation.  So those fundamental shapes were exact, not approximate.

So all of a sudden, now you’re talking about a line machine out there that’s supposed to __ to the umpteenth detail.  You’re trying to describe numerically in a machine so you can do the __ control, or you’re doing architecture on a building where on the one hand you want down to the last rivet and yet at the same time you’ve got a building of significance.  Guess what?  You can’t, even single precision probably isn’t enough to hang onto that kind of detail onto that large a system. So all of a sudden you’re going to find notes and double precision under those circumstances for many __ in architecture and numerical control.

They do a beautiful job of giving you fundamental shapes if you want, and not of approximations __ undergoing even production without having to recalculate anything.  So __ go with those, it’s overkill because how exact of a circle around the tree, how exact a circle are the root pattern(?), how exact a circle are the beetles flying, how exact a circle is the trunk __ of the tree?  Is it an exact circle?  Or is it even an exact ellipse?

Or you even look at the fine structure __ yellow pine right out my window here, doesn’t seem to have many kinds of structuring __.  The bark and everything else.  Basic shape is __ but sort of like an ellipse, the bark is a lot of other things too.  But it’s not an exact circle by a long shot.  On the one hand the kind of mathematics is very appropriate and necessary for architecture, numerical control of devices which are going to become more and more common because computers driving everything is going to be __, computer everything, because it’s so cheap and so dependable.  People get tired, computers grind on day and night without getting tired, which is to some degree an advantage.

At the same time, it probably makes sense to have at least B spline __.  Again this whole thing of precision means again the factoring in the hexagonal system and __ by into the hexagonal system with just simple __ in order to make a very fast program for the computers, bottom level.  This means that somebody’s got to __ program at the bottom level make word processing.  Make all these pieces work right too.

At the same time this world out here is splitting a lot of different directions because people’s needs are radically different.  An architect tends to lay down a very precise system of a building or so on, trying to get very exact numerical controls.  I guess all these generations of computer design, no paper at all, zero paper into his design.  So in a computer abstract objects worked on.  No paper.  Remember the reams and reams of paper that used to have to be done to build a plant?  And so on.

*It’s complicated to do it by paper.

I know, and slow, and clumsy.  And imprecise to say a few things like that.  That’s why __ paper too eventually.  Forgive me for __ why not.

*That’s all right.

Give a little __.

*I agree.  It’s a very conservative organization.

With a lot of history.

*Yeah.

C.S. Holling

*There was one time you went out to UBC and you talked to Holling and his crew.

Yeah, Holling___  told me to talk about some of the stuff I was working on.  I thought they wanted me to do more for ___ analytical presentation.  I said I would be utterly delighted to do the technical presentation.  It would be kind of neat and ___ but for the general one I had some real things ___.  The technical underpinning at this point doesn’t make a whole lot of sense, that’s my feeling.  Later on it turned out that ___ got caught ___.  I was ___ what happened was ___ and the popular meaning was ___.  It wasn’t bad.  It wasn’t real great either, but the technical ___ was a blast.  It turned out that a whole host of ___ like how you do calculations.  They were running a ___ how can you do calculation and direction and distance and ___ because that movement of ___ 

So I told them ___ try to form the system using hexagons, like another way of walking ___ would ___ their machines could handle that.  So I said ___ right in the middle ___ when they ___ power and the difficulty dealing with spatial information.

It turns out ___ exactly a bitch to do.  It turns out it doesn’t make any sense ___ distribution ___ of the system.  You always have moments of  ___.  You don’t need that kind of ___.  You need that kind of precision if they’re going to try to separate say a specter of two distant stars that are double star, they are coming in on the ___ from a different view of earth.  200 light years away or something.

You find that you ___ perhaps separate the double. Boy, does that comparable point of view not make a whole lot of sense ___ sense ___ so tend not to ___ happen ___ one of his problems.  Some of the others felt also that they were ___ but not with the kind of ___ echo I kept having.  Here I would be ___.  Gee, this piece is in the side that we did, to be able to solve this problem having ___ solve the problem.  That’s what happened there.  I found that ___ or that ___ we can do sort of things ___.

Programming Style

Except he was ___ world’s worst program I have ever seen in my entire life.

*Holling?

Yeah, Holling.  You know these thousand line programs or two thousand line programs without a single break in them.  It really is work.  They weren’t very efficient ___.  They work you know sort of by guess and by golly.  ___ until you finally get them to do something that you want them to do but the ___ biology.  But from the point of view professional program, they’re a bit of ___.

The problem is that reading most professional programs is that date we’re doing the same ___.  How could you blame him for doing something all ___ professional program is doing anyway?  Just about the ___ who’s the guy who was saying old ___ shouldn’t, you shouldn’t have thousand line programs, more than a thousand line programs ___.

*Dykstra?

Yeah, right, Dykstra came in and pointed out some real problem in trying to manage ___ what happened, I ___ after he came out with it.  What’s a ___ taking a program and every thousand lines they’re chopping to pieces. ___ solid block ___ lines means ___, ABC, and then A there would have all kinds of ___.  But in B they would have all kinds of ___ to A and C, OK.

That’s the way they dealt with Holling’s, the rules ___ letter, but somehow not quite entertaining the spirit of that.  That was having ___.  How can you blame Holling from doing something sort of similar, ___ his machine.  It seems awfully hard to read to make any sense out of.  He was done by ___ in the position __ now.  It’s sort of like taking __ sort of ___ paragraphs.  The ___ came to the ___.  So that was how that went.  That was sort of our interaction.  

Basically I felt the work he was trying to do, his efforts to ___ biology and ___ and trying to get computering to the process is one of the first ___ interestingly enough.  The ___ he called 1430 machine. I went back and ___ exact ___ so there’s a 1430 that I made it ___ an APL terminal.  The 13 was the hardware APL ___ interestingly enough so, but ___ too so ___ England, they abolished ___ out of the country where he used to live and work on, take some of his buddies and he used ___ there ___.  When he then returned, he ___ but it really ___ that much ___ give away, you know come ___.

*And then he gave it to you?

Yeah.  He gave me the first APL terminal that we used then to make a ___ emulation, even down to his most detailed hardware plugs.  That’s one of our ___ guarantees, it runs this.  We even emulated its hardware plugs exactly.  So it was ___ 12 which was just a regular half-piece storage type thing.  The 13 had the APL graphics inside it on an APL keyboard, and a storage tube.  Holling had the first graphics up running for population data ___.  ___ APL.

*He didn’t have a thousand line code of APL?

He never used APL.

*But he used that machine?

Yeah.

*Oh, OK.  So what about this.

What did he, I think he used FORTRAN but I’m not sure.  I just can’t even remember.  No, it wouldn’t have made sense to have ___ he couldn’t read it.  Can you imagine a thousand line?  ___.

*It’s hard to read 5 lines of APL.

So I don’t think ___ cuz they’re so wildly unreasonable, OK?  I think it was FORTRAN.

Just like the ___, what’s the ___ hexagonal way of doing, that was his favorite piece in the whole paper.

+Yeah.

But __ in both directions and area ___.

Hexagonal Grid

+That’s an interesting aside.  The hexagonal technique that we used is now very, very common in doing nearest neighbor calculations to within 10% when you really don’t have to be exact.  As opposed to calculating the square and the square roots of something to get the Pythagorean distance, you just add and subtract.  On a computer that’s an incredible savings in time.  I’ve used that.

The other thing is you see ___ graphic ___ tense ___ up to 45 and then ___ see you get by reflecting ___ is that you can’t ___ octagonal shape.  You can’t ___ because there’s no easy relationship between ___ based on ___ even though you may ___ in terms of directions.  Something that approximates the octagon ___ better than a hexagon.  The crucial thing is that we had put together is to ___ get areas too really ___. 

+One of the reasons that you took a look at hexagonal ___ system is it’s very, very easy to do the nearest neighbor sort of thing.  It’s probably the most biologically efficient system to do nearest neighbors that we’ve ever had.

Like a honeybee.  A honeybee is ___.

-Yeah, that’s true.

*There’s a database being set up, a national database on endangered species using gap analysis.  Have you heard that?  That’s all set up on a hexagonal base.

I didn’t realize that.

*Database across the whole United States on a hexagonal base.  Landscape and environmental parameters to try to use as a database for endangered species.

+See the problem is that if you take the normal (Cartesian) coordinate systems, you’d have a really bad problem with nearest neighbors.  You really don’t get nearest neighbors.  You get nearest neighbors and second nearest neighbors and third nearest neighbors but they’re really not.

*It’s very unstable.

+Yeah, it’s very unstable, exactly.  Take a look at the standard geographic databases that you have now.  I know this because this is one of the things I’m working with.  You can put things into a hexagonal structure, whether it be a vegetation definition or something like that.  The idea of what is a nearest neighbor now becomes trivial. Using Bland’s technique you don’t do a calculation.  You just basically count the numbers.  You don’t have to do square roots or anything like that and that is really important.

+I’ve been talking to ___ Walker.  We’ve been trying to convert from the topological databases that we get from the government, no topographical databases, into hexagonal structure.  Otherwise we’re dead meat.  We lose too much time doing the computation of what’s downstream.  Downstream, in Bland’s case, if you were accurate to 6% you were close enough.

+In most of the cases that were of atmospheric importance, if you’re within 10%, you’re home, you’re close enough for government work.  We don’t need to know down to the last inch where we are.  We only need to know that we’re somewhere in the ballpark.  When the cell resolution is a half a kilometer, we don’t need it to a half  a kilometer plus or minus 12 centimeters.  We waste a lot of time doing that computation.  That’s just another product of something that Bland came up with for the Blodgett study.

+Incidentally, I think that Blodgett data is really important so when you see Dave Wood—

Really good illustration.
